-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "userspace-defaults",
        version = "1",
        release = 1,
        homepage = "https://example.invalid/userspace-defaults",
        license = {
            "CC0-1.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "bash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\nprintf '%s\\n' \\\n    'mode = \"declarative\"' \\\n    'generation = 1' \\\n    > userspace-defaults.conf\ninstall -Dm644 userspace-defaults.conf \\\n    \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/userspace/defaults.conf\"\n"
                    }
                }
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Declarative userspace defaults"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/userspace/defaults.conf"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}