-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "atlas-sensor-module",
        version = "2.3.1",
        release = 1,
        homepage = "https://example.invalid/atlas-sensor",
        license = {
            "GPL-2.0-only"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "make"
            },
            {
                kind = "binary",
                value = "modinfo"
            },
            {
                kind = "binary",
                value = "bash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/make",
                            requirement = {
                                kind = "binary",
                                value = "make"
                            }
                        },
                        args = {
                            "KERNEL_RELEASE=6.12.28-onix1",
                            "KERNEL_DIR=/usr/lib/modules/6.12.28-onix1/build",
                            "modules"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        args = {
                            "packaging/install-module",
                            "6.12.28-onix1"
                        }
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/modinfo",
                            requirement = {
                                kind = "binary",
                                value = "modinfo"
                            }
                        },
                        args = {
                            "build/atlas-sensor.ko"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "output",
            value = {
                package = {
                    name = "linux-lts"
                },
                output = "devel"
            }
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Atlas sensor module for the selected LTS kernel"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "linux-lts"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/modules/6.12.28-onix1/extra/atlas-sensor.ko"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/atlas-sensor-module-2.3.1.tar.xz",
            hash = "456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}