-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "telemetry-runtime",
        version = "3.4.0",
        release = 1,
        homepage = "https://example.invalid/telemetry-runtime",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DBUILD_COMMAND_LINE_TOOLS=ON",
                            "-DBUILD_DOCUMENTATION=OFF"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {
        {
            kind = "pkg_config",
            value = "zlib"
        },
        {
            kind = "pkg_config",
            value = "libressl"
        }
    },
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Telemetry service and configuration"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "telemetry-runtime"
                        },
                        output = "libs"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/telemetry-agent"
                },
                {
                    kind = "any",
                    path = "/usr/share/telemetry-runtime"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Telemetry runtime libraries"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/libtelemetry-runtime.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Telemetry runtime development files"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "telemetry-runtime"
                        },
                        output = "libs"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include/telemetry-runtime"
                },
                {
                    kind = "symlink",
                    path = "/usr/lib/libtelemetry-runtime.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib/pkgconfig/telemetry-runtime.pc"
                }
            },
            conflicts = {}
        },
        {
            name = "tools",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Telemetry diagnostics"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "telemetry-runtime"
                        },
                        output = "libs"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "ca-certificates"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/telemetry-inspect"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/telemetry-runtime-3.4.0.tar.xz",
            hash = "cdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789ab",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64"
    },
    tuning = {
        {
            key = "harden",
            value = {
                kind = "enable"
            }
        },
        {
            key = "optimize",
            value = {
                kind = "config",
                value = "size"
            }
        }
    },
    emul32 = false,
    mold = false,
}