-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "device-broker-integration",
        version = "1.4.0",
        release = 2,
        homepage = "https://example.invalid/device-broker",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\ninstall -Dm644 integration/device-broker.service \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/systemd/system/device-broker.service\"\ninstall -Dm644 integration/device-broker.sysusers \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/sysusers.d/device-broker.conf\"\ninstall -Dm644 integration/device-broker.tmpfiles \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/tmpfiles.d/device-broker.conf\"\ninstall -Dm644 integration/70-device-broker.rules \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/udev/rules.d/70-device-broker.rules\"\ninstall -Dm644 integration/io.example.DeviceBroker.rules \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/polkit-1/rules.d/io.example.DeviceBroker.rules\"\n"
                    }
                }
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Device broker operating-system integration"
            },
            description = {
                kind = "some",
                value = "Service, identity, volatile-state, device-access, and authorization declarations for device-broker."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "package",
                    value = {
                        name = "device-broker"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "polkit"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/systemd/system/device-broker.service"
                },
                {
                    kind = "any",
                    path = "/usr/lib/sysusers.d/device-broker.conf"
                },
                {
                    kind = "any",
                    path = "/usr/lib/tmpfiles.d/device-broker.conf"
                },
                {
                    kind = "any",
                    path = "/usr/lib/udev/rules.d/70-device-broker.rules"
                },
                {
                    kind = "any",
                    path = "/usr/share/polkit-1/rules.d/io.example.DeviceBroker.rules"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/device-broker-integration-1.4.0.tar.xz",
            hash = "9abcdef0123456789abcdef0123456789abcdef0123456789abcdef012345678",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}