//! Compile-time proof for the production declaration adapter boundary.

use std::{error::Error, fmt};

use declarative_config::{
    DeclarationCodec, DeclarationEvaluationError, DeclarationEvaluator,
    DeclarationInputEvaluator, EngineId, Evaluation, LanguageId, LanguageSpec,
    Limits, Source, SourceRoot,
};

const FIXTURE_GENERATED_MARKER: &str =
    "// @generated by fixture declaration adapter. DO NOT EDIT.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
struct EvaluationIdentity {
    language: LanguageId,
    engine: EngineId,
    logical_source: String,
    source_hash: [u8; 32],
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct TriggerDeclaration {
    name: String,
    command: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ProfileFragment {
    name: String,
    packages: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct InputSensitiveDeclaration {
    source: String,
    explicit_inputs: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct InputSensitiveIdentity {
    source: EvaluationIdentity,
    explicit_inputs: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureError(&'static str);

impl fmt::Display for FixtureError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.0)
    }
}

impl Error for FixtureError {}

struct TriggerEvaluator {
    language: LanguageSpec,
}

impl TriggerEvaluator {
    fn new() -> Self {
        Self {
            language: gluon_language(),
        }
    }
}

impl DeclarationEvaluator<TriggerDeclaration> for TriggerEvaluator {
    type Identity = EvaluationIdentity;
    type Error = FixtureError;

    fn language_spec(&self) -> &LanguageSpec {
        &self.language
    }

    fn limits(&self) -> Limits {
        Limits::default()
    }

    fn with_source_root(&self, _source_root: SourceRoot) -> Self {
        Self::new()
    }

    fn evaluate(
        &self,
        source: &Source,
    ) -> Result<
        Evaluation<TriggerDeclaration, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        let (name, command) = source
            .text()
            .split_once(':')
            .ok_or_else(|| {
                DeclarationEvaluationError::conversion(FixtureError("trigger shape"))
            })?;
        Ok(Evaluation {
            value: TriggerDeclaration {
                name: name.to_owned(),
                command: command.to_owned(),
            },
            identity: fixture_identity(self.language_spec(), source),
        })
    }
}

struct ProfileCodec {
    language: LanguageSpec,
}

impl ProfileCodec {
    fn new() -> Self {
        Self {
            language: gluon_language(),
        }
    }
}

impl DeclarationEvaluator<ProfileFragment> for ProfileCodec {
    type Identity = EvaluationIdentity;
    type Error = FixtureError;

    fn language_spec(&self) -> &LanguageSpec {
        &self.language
    }

    fn limits(&self) -> Limits {
        Limits::default()
    }

    fn with_source_root(&self, _source_root: SourceRoot) -> Self {
        Self::new()
    }

    fn evaluate(
        &self,
        source: &Source,
    ) -> Result<
        Evaluation<ProfileFragment, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        let (name, packages) = source
            .text()
            .split_once('=')
            .ok_or_else(|| {
                DeclarationEvaluationError::conversion(FixtureError("fragment shape"))
            })?;
        Ok(Evaluation {
            value: ProfileFragment {
                name: name.to_owned(),
                packages: packages.split(',').map(str::to_owned).collect(),
            },
            identity: fixture_identity(self.language_spec(), source),
        })
    }
}

impl DeclarationCodec<ProfileFragment> for ProfileCodec {
    fn encode(&self, value: &ProfileFragment) -> Result<String, Self::Error> {
        Ok(format!("{}={}", value.name, value.packages.join(",")))
    }
}

struct InputSensitiveEvaluator {
    language: LanguageSpec,
}

impl InputSensitiveEvaluator {
    fn new() -> Self {
        Self {
            language: gluon_language(),
        }
    }
}

impl DeclarationEvaluator<InputSensitiveDeclaration> for InputSensitiveEvaluator {
    type Identity = InputSensitiveIdentity;
    type Error = FixtureError;

    fn language_spec(&self) -> &LanguageSpec {
        &self.language
    }

    fn limits(&self) -> Limits {
        Limits::default()
    }

    fn with_source_root(&self, _source_root: SourceRoot) -> Self {
        Self::new()
    }

    fn evaluate(
        &self,
        source: &Source,
    ) -> Result<
        Evaluation<InputSensitiveDeclaration, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        <Self as DeclarationInputEvaluator<InputSensitiveDeclaration>>::evaluate_with_inputs(
            self,
            source,
            &[],
        )
    }
}

impl DeclarationInputEvaluator<InputSensitiveDeclaration>
    for InputSensitiveEvaluator
{
    fn evaluate_with_inputs(
        &self,
        source: &Source,
        explicit_inputs: &[u8],
    ) -> Result<
        Evaluation<InputSensitiveDeclaration, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        Ok(Evaluation {
            value: InputSensitiveDeclaration {
                source: source.text().to_owned(),
                explicit_inputs: explicit_inputs.to_vec(),
            },
            identity: InputSensitiveIdentity {
                source: fixture_identity(self.language_spec(), source),
                explicit_inputs: explicit_inputs.to_vec(),
            },
        })
    }
}

fn gluon_language() -> LanguageSpec {
    LanguageSpec::new(
        LanguageId::new("gluon").expect("fixture language is canonical"),
        EngineId::new("gluon-vm", "0.18.3").expect("fixture engine is canonical"),
        "glu",
        "declaration-v1",
        FIXTURE_GENERATED_MARKER,
    )
    .expect("fixture descriptors are canonical")
}

fn fixture_identity(spec: &LanguageSpec, source: &Source) -> EvaluationIdentity {
    let mut source_hash = [0; 32];
    for (index, byte) in source.text().bytes().enumerate() {
        source_hash[index % source_hash.len()] ^= byte;
    }
    EvaluationIdentity {
        language: spec.language().clone(),
        engine: spec.engine().clone(),
        logical_source: source.logical_name().to_owned(),
        source_hash,
    }
}

fn evaluate_read_only<T, E>(
    evaluator: &E,
    source: &Source,
) -> Result<
    Evaluation<T, E::Identity>,
    DeclarationEvaluationError<E::Error>,
>
where
    E: DeclarationEvaluator<T>,
{
    evaluator.evaluate(source)
}

fn evaluate_with_identity_inputs<T, E>(
    evaluator: &E,
    source: &Source,
    explicit_inputs: &[u8],
) -> Result<
    Evaluation<T, E::Identity>,
    DeclarationEvaluationError<E::Error>,
>
where
    E: DeclarationInputEvaluator<T>,
{
    evaluator.evaluate_with_inputs(source, explicit_inputs)
}

fn round_trip_writable<T, C>(
    codec: &C,
    source: &Source,
) -> Result<
    Evaluation<T, C::Identity>,
    DeclarationEvaluationError<C::Error>,
>
where
    C: DeclarationCodec<T>,
{
    let evaluation = codec.evaluate(source)?;
    let _canonical_source = codec
        .encode(&evaluation.value)
        .map_err(DeclarationEvaluationError::conversion)?;
    Ok(evaluation)
}

#[test]
fn language_and_engine_descriptors_reject_noncanonical_values() {
    let language = gluon_language();
    assert_eq!(language.language().as_str(), "gluon");
    assert_eq!(language.engine().implementation(), "gluon-vm");
    assert_eq!(language.engine().version(), "0.18.3");
    assert_eq!(language.extension(), "glu");
    assert_eq!(language.source_profile(), "declaration-v1");
    assert_eq!(language.generated_marker(), FIXTURE_GENERATED_MARKER);

    assert!(LanguageId::new("").is_err());
    assert!(LanguageId::new("Gluon").is_err());
    assert!(EngineId::new("gluon vm", "0.18.3").is_err());
    assert!(EngineId::new("gluon-vm", "").is_err());
    let valid_language = LanguageId::new("gluon").unwrap();
    let valid_engine = EngineId::new("gluon-vm", "0.18.3").unwrap();
    assert!(
        LanguageSpec::new(
            valid_language.clone(),
            valid_engine.clone(),
            ".glu",
            "v1",
            "generated\n",
        )
        .is_err()
    );
    assert!(
        LanguageSpec::new(
            valid_language.clone(),
            valid_engine.clone(),
            "glu",
            "v1",
            "missing newline",
        )
        .is_err()
    );
    assert!(
        LanguageSpec::new(
            valid_language,
            valid_engine,
            "glu",
            "v1",
            "line\nbreak\n",
        )
        .is_err()
    );
}

#[test]
fn read_only_trigger_needs_only_a_typed_evaluator() {
    let evaluation = evaluate_read_only(
        &TriggerEvaluator::new(),
        &Source::new("tx.d/rebuild.glu", "rebuild:/usr/bin/rebuild-cache"),
    )
    .expect("read-only trigger evaluates");

    assert_eq!(evaluation.value.name, "rebuild");
    assert_eq!(evaluation.value.command, "/usr/bin/rebuild-cache");
    assert_eq!(evaluation.identity.logical_source, "tx.d/rebuild.glu");
}

#[test]
fn writable_fragment_adds_a_codec_without_changing_evaluation() {
    let codec = ProfileCodec::new();
    let source = Source::new("profiles.d/workstation.glu", "workstation=base,desktop");
    let evaluation = round_trip_writable(&codec, &source).expect("writable fragment round trips");

    assert_eq!(evaluation.value.name, "workstation");
    assert_eq!(evaluation.value.packages, ["base", "desktop"]);
    assert_eq!(codec.encode(&evaluation.value).unwrap(), source.text());
}

#[test]
fn explicit_identity_inputs_are_an_opt_in_typed_role() {
    let evaluator = InputSensitiveEvaluator::new();
    let source = Source::new("lock.d/source.glu", "source-lock");
    let plain = evaluate_read_only(&evaluator, &source).unwrap();
    let supplied = evaluate_with_identity_inputs(
        &evaluator,
        &source,
        b"resolved-source:v1",
    )
    .unwrap();

    assert!(plain.value.explicit_inputs.is_empty());
    assert!(plain.identity.explicit_inputs.is_empty());
    assert_eq!(supplied.value.source, "source-lock");
    assert_eq!(supplied.value.explicit_inputs, b"resolved-source:v1");
    assert_eq!(supplied.identity.explicit_inputs, b"resolved-source:v1");
    assert_ne!(plain.identity, supplied.identity);
}

#[test]
fn evaluation_owns_the_domain_value_and_identity() {
    let evaluation = {
        let evaluator = TriggerEvaluator::new();
        evaluate_read_only(
            &evaluator,
            &Source::new("sys.d/reindex.glu", "reindex:/usr/bin/reindex"),
        )
        .unwrap()
    };

    assert_eq!(evaluation.value.name, "reindex");
    assert_eq!(evaluation.identity.language.as_str(), "gluon");
}
