use std::{
    error::Error,
    fmt,
    path::PathBuf,
};

use config::declaration::{
    FixedRootRevalidationPhase, LoadFixedRootDeclarationError,
    RootDeclarationDiscoveryError, RootDeclarationSlot,
    TypedDeclarationEvaluatorSet, load_fixed_root_declaration,
    load_required_fixed_root_declaration_from_source_root,
};
use declarative_config::{
    DeclarationEvaluationError, DeclarationEvaluator, Diagnostic, EvaluationDeadline, EngineId,
    Evaluation, LanguageId, LanguageSpec, LimitKind, Limits, Source,
    SourceRoot,
};
use fs_err as fs;
use tempfile::tempdir;

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureValue {
    adapter: &'static str,
    value: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureIdentity {
    adapter: &'static str,
    logical_name: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureError(&'static str);

impl fmt::Display for FixtureError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.0)
    }
}

impl Error for FixtureError {}

#[derive(Clone)]
struct AdapterState {
    language: LanguageSpec,
    prefix: &'static str,
    value_name: &'static str,
    max_source_bytes: usize,
    source_root: Option<SourceRoot>,
    replacement: Option<(PathBuf, PathBuf)>,
}

#[derive(Clone)]
enum FixtureAdapter {
    First(AdapterState),
    Second(AdapterState),
}

impl FixtureAdapter {
    fn first(replacement: Option<(PathBuf, PathBuf)>) -> Self {
        Self::First(AdapterState {
            language: language("fixture-first", "alpha"),
            prefix: "a:",
            value_name: "first",
            max_source_bytes: 64,
            source_root: None,
            replacement,
        })
    }

    fn second() -> Self {
        Self::Second(AdapterState {
            language: language("fixture-second", "beta"),
            prefix: "b:",
            value_name: "second",
            max_source_bytes: 12,
            source_root: None,
            replacement: None,
        })
    }

    fn state(&self) -> &AdapterState {
        match self {
            Self::First(state) | Self::Second(state) => state,
        }
    }

    fn state_mut(&mut self) -> &mut AdapterState {
        match self {
            Self::First(state) | Self::Second(state) => state,
        }
    }
}

impl DeclarationEvaluator<FixtureValue> for FixtureAdapter {
    type Identity = FixtureIdentity;
    type Error = FixtureError;

    fn language_spec(&self) -> &LanguageSpec {
        &self.state().language
    }

    fn limits(&self) -> Limits {
        Limits {
            max_source_bytes: self.state().max_source_bytes,
            ..Limits::default()
        }
    }

    fn with_source_root(&self, source_root: SourceRoot) -> Self {
        let mut rooted = self.clone();
        rooted.state_mut().source_root = Some(source_root);
        rooted
    }

    fn evaluate_within(
        &self,
        source: &Source,
        _deadline: EvaluationDeadline,
    ) -> Result<
        Evaluation<FixtureValue, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        if self.state().source_root.is_none() {
            return Err(Diagnostic::internal("fixture adapter was not rooted").into());
        }
        if let Some((directory, held)) = &self.state().replacement {
            fs::rename(directory, held).unwrap();
            fs::create_dir(directory).unwrap();
            return Err(Diagnostic::internal("fixture evaluation failed after replacement").into());
        }
        if source.text() == "diagnostic" {
            return Err(Diagnostic::internal("fixture evaluation failure").into());
        }
        let value = source
            .text()
            .strip_prefix(self.state().prefix)
            .ok_or_else(|| DeclarationEvaluationError::conversion(FixtureError("fixture conversion")))?;
        Ok(Evaluation {
            value: FixtureValue {
                adapter: self.state().value_name,
                value: value.to_owned(),
            },
            identity: FixtureIdentity {
                adapter: self.state().value_name,
                logical_name: source.logical_name().to_owned(),
            },
        })
    }
}

fn language(name: &str, extension: &str) -> LanguageSpec {
    LanguageSpec::new(
        LanguageId::new(name).unwrap(),
        EngineId::new(format!("{name}-engine"), "1").unwrap(),
        extension,
        "declaration-v1",
        format!("# generated by {name}\n"),
    )
    .unwrap()
}

fn evaluators(
    replacement: Option<(PathBuf, PathBuf)>,
) -> TypedDeclarationEvaluatorSet<FixtureValue, FixtureAdapter> {
    TypedDeclarationEvaluatorSet::new([
        FixtureAdapter::first(replacement),
        FixtureAdapter::second(),
    ])
    .unwrap()
}

fn slot() -> RootDeclarationSlot {
    RootDeclarationSlot::new("fixed", "portable/fixed").unwrap()
}

#[test]
fn exact_descriptor_dispatches_both_non_config_adapter_variants() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    fs::create_dir(&directory).unwrap();
    fs::write(directory.join("fixed.alpha"), "a:first-value").unwrap();
    let evaluators = evaluators(None);

    let first = load_fixed_root_declaration(&directory, &slot(), &evaluators)
        .unwrap()
        .unwrap();
    assert_eq!(first.logical_name, "portable/fixed");
    assert_eq!(first.path, directory.join("fixed.alpha"));
    assert_eq!(first.language.extension(), "alpha");
    assert_eq!(first.value.adapter, "first");
    assert_eq!(first.value.value, "first-value");
    assert_eq!(first.identity.logical_name, "portable/fixed");

    fs::remove_file(directory.join("fixed.alpha")).unwrap();
    fs::write(directory.join("fixed.beta"), "b:second").unwrap();
    let second = load_fixed_root_declaration(&directory, &slot(), &evaluators)
        .unwrap()
        .unwrap();
    assert_eq!(second.language.extension(), "beta");
    assert_eq!(second.value.adapter, "second");
    assert_eq!(second.value.value, "second");
}

#[test]
fn collisions_and_registered_nonregular_candidates_remain_structured() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    fs::create_dir(&directory).unwrap();
    fs::write(directory.join("fixed.alpha"), "a:first").unwrap();
    fs::write(directory.join("fixed.beta"), "b:second").unwrap();

    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators(None)).unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Discovery {
            source: RootDeclarationDiscoveryError::Collision { .. },
            ..
        }
    ));

    fs::remove_file(directory.join("fixed.alpha")).unwrap();
    fs::remove_file(directory.join("fixed.beta")).unwrap();
    fs::create_dir(directory.join("fixed.alpha")).unwrap();
    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators(None)).unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Discovery {
            source: RootDeclarationDiscoveryError::NotRegular { .. },
            ..
        }
    ));
}

#[test]
fn missing_directory_and_unknown_extensions_are_none() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    let evaluators = evaluators(None);

    assert!(
        load_fixed_root_declaration(&directory, &slot(), &evaluators)
            .unwrap()
            .is_none()
    );

    fs::create_dir(&directory).unwrap();
    fs::write(directory.join("fixed.unknown"), "ignored").unwrap();
    assert!(
        load_fixed_root_declaration(&directory, &slot(), &evaluators)
            .unwrap()
            .is_none()
    );

    let real_parent = temporary.path().join("real-parent");
    let linked_parent = temporary.path().join("linked-parent");
    fs::create_dir(&real_parent).unwrap();
    fs::create_dir(real_parent.join("nested")).unwrap();
    std::os::unix::fs::symlink(&real_parent, &linked_parent).unwrap();
    let error = load_fixed_root_declaration(
        linked_parent.join("nested"),
        &slot(),
        &evaluators,
    )
    .unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::OpenDirectory { .. }
    ));
}

#[test]
fn per_adapter_bounds_and_error_classes_remain_distinct() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    fs::create_dir(&directory).unwrap();
    let path = directory.join("fixed.beta");
    let evaluators = evaluators(None);

    fs::write(&path, "b:012345678901").unwrap();
    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators).unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Read { source, .. }
            if source.limit == Some(LimitKind::SourceSize)
    ));

    fs::write(&path, "wrong").unwrap();
    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators).unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Conversion {
            source: FixtureError("fixture conversion"),
            ..
        }
    ));

    fs::write(&path, "diagnostic").unwrap();
    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators).unwrap_err();
    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Evaluation { .. }
    ));
}

#[test]
fn evaluator_error_cannot_hide_directory_substitution() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    let held = temporary.path().join("held");
    fs::create_dir(&directory).unwrap();
    fs::write(directory.join("fixed.alpha"), "a:value").unwrap();
    let evaluators = evaluators(Some((directory.clone(), held.clone())));

    let error = load_fixed_root_declaration(&directory, &slot(), &evaluators).unwrap_err();

    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Revalidation {
            phase: FixedRootRevalidationPhase::AfterEvaluation,
            ..
        }
    ));
    assert!(held.join("fixed.alpha").exists());
    assert!(!directory.join("fixed.alpha").exists());
}

#[test]
fn source_root_backed_loader_accepts_and_pins_a_symlinked_root() {
    let temporary = tempdir().unwrap();
    let real = temporary.path().join("real");
    let held = temporary.path().join("held");
    let linked = temporary.path().join("linked");
    fs::create_dir(&real).unwrap();
    fs::write(real.join("fixed.alpha"), "a:pinned-value").unwrap();
    std::os::unix::fs::symlink(&real, &linked).unwrap();
    let source_root = SourceRoot::new(&linked).unwrap();

    fs::rename(&real, &held).unwrap();
    fs::create_dir(&real).unwrap();
    fs::write(real.join("fixed.alpha"), "a:replacement-value").unwrap();

    let evaluators = evaluators(None);
    let required_language = evaluators.languages().get("alpha").unwrap().clone();
    let loaded = load_required_fixed_root_declaration_from_source_root(
        &linked,
        &source_root,
        &slot(),
        &required_language,
        &evaluators,
    )
    .unwrap();

    assert_eq!(loaded.path, linked.join("fixed.alpha"));
    assert_eq!(loaded.value.value, "pinned-value");
    assert_eq!(
        fs::read_to_string(real.join("fixed.alpha")).unwrap(),
        "a:replacement-value"
    );
}

#[test]
fn source_root_backed_loader_preserves_nonregular_load_diagnostics() {
    let temporary = tempdir().unwrap();
    let directory = temporary.path().join("declarations");
    fs::create_dir(&directory).unwrap();
    fs::write(directory.join("target.alpha"), "a:value").unwrap();
    std::os::unix::fs::symlink(
        "target.alpha",
        directory.join("fixed.alpha"),
    )
    .unwrap();
    let source_root = SourceRoot::new(&directory).unwrap();
    let evaluators = evaluators(None);
    let required_language = evaluators.languages().get("alpha").unwrap().clone();
    let expected = source_root.load("fixed.alpha", 64).unwrap_err();

    let error = load_required_fixed_root_declaration_from_source_root(
        &directory,
        &source_root,
        &slot(),
        &required_language,
        &evaluators,
    )
    .unwrap_err();

    assert!(matches!(
        error,
        LoadFixedRootDeclarationError::Read { path, source }
            if path == directory.join("fixed.alpha")
                && source.category == expected.category
                && source.limit == expected.limit
                && source.source_name == expected.source_name
                && source.span == expected.span
                && source.message == expected.message
    ));
}
