use std::{
    error::Error,
    fmt,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
};

use config::{
    Config,
    declaration::{
        ConfigDeclarationEvaluator, DeclarationEvaluatorSet,
        LoadRootedDeclarationsError, RootedDeclarationRevalidationPhase,
        load_rooted_declarations,
    },
};
use declarative_config::{
    DeclarationEvaluationError, DeclarationEvaluator, Diagnostic,
    DiagnosticCategory, EngineId, Evaluation, LanguageId, LanguageSpec,
    LimitKind, Limits, Source, SourceRoot,
};
use fs_err as fs;
use tempfile::tempdir;

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureConfig {
    value: String,
}

impl Config for FixtureConfig {
    fn domain() -> String {
        "bundle".to_owned()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureIdentity {
    language: String,
    source: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct FixtureError(&'static str);

impl fmt::Display for FixtureError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.0)
    }
}

impl Error for FixtureError {}

#[derive(Clone)]
struct FixtureAdapter {
    language: LanguageSpec,
    prefix: &'static str,
    source_limit: usize,
    root: Option<SourceRoot>,
    evaluations: Arc<Mutex<Vec<String>>>,
    replace_collection: Option<(PathBuf, PathBuf)>,
}

impl FixtureAdapter {
    fn first(evaluations: Arc<Mutex<Vec<String>>>) -> Self {
        Self::new("first", "one", "one:", 64, evaluations)
    }

    fn second(evaluations: Arc<Mutex<Vec<String>>>, source_limit: usize) -> Self {
        Self::new("second", "two", "two:", source_limit, evaluations)
    }

    fn new(
        language: &str,
        extension: &str,
        prefix: &'static str,
        source_limit: usize,
        evaluations: Arc<Mutex<Vec<String>>>,
    ) -> Self {
        Self {
            language: LanguageSpec::new(
                LanguageId::new(language).unwrap(),
                EngineId::new(format!("{language}-engine"), "1").unwrap(),
                extension,
                "declaration-v1",
                format!("# generated by {language}\n"),
            )
            .unwrap(),
            prefix,
            source_limit,
            root: None,
            evaluations,
            replace_collection: None,
        }
    }

    fn replacing_collection(mut self, collection: PathBuf, held: PathBuf) -> Self {
        self.replace_collection = Some((collection, held));
        self
    }
}

impl DeclarationEvaluator<FixtureConfig> for FixtureAdapter {
    type Identity = FixtureIdentity;
    type Error = FixtureError;

    fn language_spec(&self) -> &LanguageSpec {
        &self.language
    }

    fn limits(&self) -> Limits {
        Limits {
            max_source_bytes: self.source_limit,
            ..Limits::default()
        }
    }

    fn with_source_root(&self, source_root: SourceRoot) -> Self {
        let mut rooted = self.clone();
        rooted.root = Some(source_root);
        rooted
    }

    fn evaluate(
        &self,
        source: &Source,
    ) -> Result<
        Evaluation<FixtureConfig, Self::Identity>,
        DeclarationEvaluationError<Self::Error>,
    > {
        if self.root.is_none() {
            return Err(Diagnostic::internal("fixture adapter was not rooted").into());
        }
        self.evaluations.lock().unwrap().push(format!(
            "{}:{}:{}",
            self.language.language().as_str(),
            source.logical_name(),
            source.text()
        ));
        if let Some((collection, held)) = &self.replace_collection {
            fs::rename(collection, held).unwrap();
            fs::create_dir(collection).unwrap();
        }
        if source.text() == "diagnostic" {
            return Err(Diagnostic::internal("fixture diagnostic").into());
        }
        if source.text() == "conversion" {
            return Err(DeclarationEvaluationError::conversion(FixtureError(
                "fixture conversion",
            )));
        }
        let value = source.text().strip_prefix(self.prefix).ok_or_else(|| {
            DeclarationEvaluationError::conversion(FixtureError(
                "wrong adapter dispatch",
            ))
        })?;
        Ok(Evaluation {
            value: FixtureConfig {
                value: value.to_owned(),
            },
            identity: FixtureIdentity {
                language: self.language.language().as_str().to_owned(),
                source: source.logical_name().to_owned(),
            },
        })
    }
}

impl ConfigDeclarationEvaluator for FixtureAdapter {
    type Config = FixtureConfig;
}

fn evaluators(
    evaluations: Arc<Mutex<Vec<String>>>,
    second_limit: usize,
) -> DeclarationEvaluatorSet<FixtureAdapter> {
    DeclarationEvaluatorSet::new([
        FixtureAdapter::first(Arc::clone(&evaluations)),
        FixtureAdapter::second(evaluations, second_limit),
    ])
    .unwrap()
}

fn write(path: impl AsRef<Path>, contents: &str) {
    let path = path.as_ref();
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, contents).unwrap();
}

#[test]
fn retained_root_dispatches_two_adapters_and_returns_logical_order() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    let detached = temporary.path().join("detached");
    write(root_path.join("bundle.one"), "one:root");
    write(root_path.join("bundle.d/zeta.one"), "one:zeta");
    write(root_path.join("bundle.d/alpha.two"), "two:alpha");
    write(root_path.join("bundle.d/ignored.unknown"), "ignored");
    let retained = fs::File::open(&root_path).unwrap();

    fs::rename(&root_path, &detached).unwrap();
    write(root_path.join("bundle.one"), "one:injected");
    write(root_path.join("bundle.d/alpha.two"), "two:injected");

    let evaluations = Arc::new(Mutex::new(Vec::new()));
    let loaded = load_rooted_declarations(
        &root_path,
        &retained,
        &evaluators(Arc::clone(&evaluations), 64),
    )
    .unwrap();

    assert_eq!(
        loaded
            .iter()
            .map(|declaration| (
                declaration.logical_name.as_str(),
                declaration.value.value.as_str(),
                declaration.language.extension(),
                declaration.identity.source.as_str(),
            ))
            .collect::<Vec<_>>(),
        [
            ("alpha", "alpha", "two", "bundle.d/alpha.two"),
            ("bundle", "root", "one", "bundle.one"),
            ("zeta", "zeta", "one", "bundle.d/zeta.one"),
        ]
    );
    assert_eq!(
        *evaluations.lock().unwrap(),
        [
            "first:bundle.one:one:root",
            "second:bundle.d/alpha.two:two:alpha",
            "first:bundle.d/zeta.one:one:zeta",
        ]
    );
}

#[test]
fn adapter_source_limit_is_applied_before_rooted_evaluation() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    write(root_path.join("bundle.one"), "one:accepted");
    write(root_path.join("bundle.d/oversized.two"), "two:too-long");
    let retained = fs::File::open(&root_path).unwrap();
    let evaluations = Arc::new(Mutex::new(Vec::new()));

    let error = load_rooted_declarations(
        &root_path,
        &retained,
        &evaluators(Arc::clone(&evaluations), 8),
    )
    .unwrap_err();

    assert!(matches!(
        error,
        LoadRootedDeclarationsError::Read { source, .. }
            if source.limit == Some(LimitKind::SourceSize)
    ));
    assert_eq!(
        *evaluations.lock().unwrap(),
        ["first:bundle.one:one:accepted"]
    );
}

#[test]
fn evaluation_error_cannot_bypass_post_evaluation_revalidation() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    let collection = root_path.join("bundle.d");
    let held = root_path.join("held");
    write(collection.join("failure.one"), "diagnostic");
    let retained = fs::File::open(&root_path).unwrap();
    let evaluations = Arc::new(Mutex::new(Vec::new()));
    let replacing = FixtureAdapter::first(evaluations)
        .replacing_collection(collection, held);
    let evaluators = DeclarationEvaluatorSet::new([replacing]).unwrap();

    let error = load_rooted_declarations(&root_path, &retained, &evaluators)
        .unwrap_err();

    assert!(matches!(
        error,
        LoadRootedDeclarationsError::Revalidation {
            phase: RootedDeclarationRevalidationPhase::AfterEvaluation,
            ..
        }
    ));
}

#[test]
fn evaluation_and_conversion_failures_remain_distinct() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    write(root_path.join("bundle.one"), "diagnostic");
    let retained = fs::File::open(&root_path).unwrap();
    let evaluations = Arc::new(Mutex::new(Vec::new()));
    let set = evaluators(evaluations, 64);

    let error = load_rooted_declarations(&root_path, &retained, &set)
        .unwrap_err();
    assert!(matches!(
        error,
        LoadRootedDeclarationsError::Evaluation { source, .. }
            if source.category == DiagnosticCategory::Internal
    ));

    write(root_path.join("bundle.one"), "conversion");
    let retained = fs::File::open(&root_path).unwrap();
    let error = load_rooted_declarations(&root_path, &retained, &set)
        .unwrap_err();
    assert!(matches!(
        error,
        LoadRootedDeclarationsError::Conversion {
            source: FixtureError("fixture conversion"),
            ..
        }
    ));
}
