-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-cargo-features-fixture-1.0.0.tar",
            sha256 = "325eb5329547c77250f5d642bfcb3a3ff3b61eecdf20b0791a411a10db38bab6"
        },
    },
}