// SPDX-FileCopyrightText: 2026 AerynOS Developers
// SPDX-License-Identifier: MPL-2.0

//! Canonical generated lock data for resolved recipe sources.
//!
//! This module deliberately emits a standalone Gluon value instead of
//! rewriting authored recipe source. Loading and upstream integration are kept
//! separate so the lock format can be reviewed and versioned first.

use std::{
    cmp::Ordering,
    fmt::Write as _,
    io::{self, Write as _},
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering as AtomicOrdering},
};

use fs_err as fs;

/// Canonical file name for generated source resolution data.
pub const SOURCE_LOCK_FILE_NAME: &str = "sources.lock.glu";

/// Current schema written into [`SourceLock::schema_version`].
pub const SOURCE_LOCK_SCHEMA_VERSION: u32 = 1;

/// Marker which makes it explicit that the lock must not be hand edited.
pub const GENERATED_GLUON_MARKER: &str = "// @generated by boulder. DO NOT EDIT.\n";

const STANDALONE_GLUON_TYPES: &str = r#"type SourceResolution =
    | Archive {
        order : Int,
        url : String,
        sha256 : String,
    }
    | Git {
        order : Int,
        url : String,
        requested_ref : String,
        commit : String,
    }

type SourceLock = {
    schema_version : Int,
    sources : Array SourceResolution,
}

"#;

/// Versioned generated source resolution data.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceLock {
    pub schema_version: u32,
    pub sources: Vec<SourceResolution>,
}

impl SourceLock {
    /// Construct a lock using the current schema version.
    pub fn new(sources: Vec<SourceResolution>) -> Self {
        Self {
            schema_version: SOURCE_LOCK_SCHEMA_VERSION,
            sources,
        }
    }
}

impl Default for SourceLock {
    fn default() -> Self {
        Self::new(Vec::new())
    }
}

/// One resolved source, retaining its position in the authored upstream list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SourceResolution {
    Archive(ArchiveResolution),
    Git(GitResolution),
}

impl SourceResolution {
    fn order(&self) -> u32 {
        match self {
            Self::Archive(source) => source.order,
            Self::Git(source) => source.order,
        }
    }

    fn kind_order(&self) -> u8 {
        match self {
            Self::Archive(_) => 0,
            Self::Git(_) => 1,
        }
    }

    fn canonical_cmp(&self, other: &Self) -> Ordering {
        self.order()
            .cmp(&other.order())
            .then_with(|| self.kind_order().cmp(&other.kind_order()))
            .then_with(|| match (self, other) {
                (Self::Archive(left), Self::Archive(right)) => {
                    left.url.cmp(&right.url).then_with(|| left.sha256.cmp(&right.sha256))
                }
                (Self::Git(left), Self::Git(right)) => left
                    .url
                    .cmp(&right.url)
                    .then_with(|| left.requested_ref.cmp(&right.requested_ref))
                    .then_with(|| left.commit.cmp(&right.commit)),
                _ => Ordering::Equal,
            })
    }
}

/// Resolution data for an archive source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveResolution {
    pub order: u32,
    pub url: String,
    pub sha256: String,
}

/// Resolution data for a Git source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GitResolution {
    pub order: u32,
    pub url: String,
    pub requested_ref: String,
    /// The complete resolved commit identifier, never an abbreviated display
    /// hash.
    pub commit: String,
}

/// Result of saving a generated source lock.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteOutcome {
    /// The existing file was byte-for-byte canonical already.
    Unchanged,
    /// A missing or different lock was atomically replaced.
    Written,
}

/// Encode a canonical, standalone, import-free Gluon lock value.
///
/// Source entries are ordered by authored position and then by all remaining
/// fields, so construction order never affects the generated file.
pub fn encode_source_lock(lock: &SourceLock) -> String {
    let mut sources = lock.sources.iter().collect::<Vec<_>>();
    sources.sort_by(|left, right| left.canonical_cmp(right));

    let mut output = String::from(GENERATED_GLUON_MARKER);
    output.push_str("// Canonical standalone source lock. Schema version is explicit below.\n");
    output.push_str(STANDALONE_GLUON_TYPES);
    output.push_str("{\n");
    writeln!(output, "    schema_version = {},", lock.schema_version).unwrap();
    output.push_str("    sources = [\n");
    for source in sources {
        match source {
            SourceResolution::Archive(source) => encode_archive(&mut output, source),
            SourceResolution::Git(source) => encode_git(&mut output, source),
        }
    }
    output.push_str("    ],\n");
    output.push_str("}\n");
    output
}

fn encode_archive(output: &mut String, source: &ArchiveResolution) {
    output.push_str("        Archive {\n");
    writeln!(output, "            order = {},", source.order).unwrap();
    writeln!(output, "            url = {},", gluon_string(&source.url)).unwrap();
    writeln!(output, "            sha256 = {},", gluon_string(&source.sha256)).unwrap();
    output.push_str("        },\n");
}

fn encode_git(output: &mut String, source: &GitResolution) {
    output.push_str("        Git {\n");
    writeln!(output, "            order = {},", source.order).unwrap();
    writeln!(output, "            url = {},", gluon_string(&source.url)).unwrap();
    writeln!(
        output,
        "            requested_ref = {},",
        gluon_string(&source.requested_ref)
    )
    .unwrap();
    writeln!(output, "            commit = {},", gluon_string(&source.commit)).unwrap();
    output.push_str("        },\n");
}

fn gluon_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

/// Atomically write a canonical lock, avoiding any replacement when its bytes
/// are unchanged.
pub fn write_source_lock(path: &Path, lock: &SourceLock) -> io::Result<WriteOutcome> {
    let encoded = encode_source_lock(lock);
    match fs::read(path) {
        Ok(existing) if existing == encoded.as_bytes() => return Ok(WriteOutcome::Unchanged),
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }

    atomic_write_with(path, encoded.as_bytes(), |_| Ok(()))?;
    Ok(WriteOutcome::Written)
}

static TEMPORARY_COUNTER: AtomicU64 = AtomicU64::new(0);

fn atomic_write_with(
    path: &Path,
    bytes: &[u8],
    before_replace: impl FnOnce(&Path) -> io::Result<()>,
) -> io::Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let file_name = path
        .file_name()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "source lock path has no file name"))?
        .to_string_lossy();

    let (temporary_path, mut file) = create_temporary(parent, &file_name)?;
    let mut guard = TemporaryGuard(Some(temporary_path.clone()));
    file.write_all(bytes)?;
    file.sync_all()?;
    drop(file);

    before_replace(&temporary_path)?;
    fs::rename(&temporary_path, path)?;
    guard.0 = None;
    fs::File::open(parent)?.sync_all()?;
    Ok(())
}

fn create_temporary(parent: &Path, file_name: &str) -> io::Result<(PathBuf, fs::File)> {
    for _ in 0..100 {
        let counter = TEMPORARY_COUNTER.fetch_add(1, AtomicOrdering::Relaxed);
        let path = parent.join(format!(".{file_name}.tmp-{}-{counter}", std::process::id()));
        match fs::OpenOptions::new().write(true).create_new(true).open(&path) {
            Ok(file) => return Ok((path, file)),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
            Err(error) => return Err(error),
        }
    }
    Err(io::Error::new(
        io::ErrorKind::AlreadyExists,
        "unable to allocate a temporary source lock",
    ))
}

struct TemporaryGuard(Option<PathBuf>);

impl Drop for TemporaryGuard {
    fn drop(&mut self) {
        if let Some(path) = self.0.take() {
            let _ = fs::remove_file(path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FULL_COMMIT: &str = "0123456789abcdef0123456789abcdef01234567";

    #[test]
    fn encodes_archive_and_git_with_the_full_commit() {
        let encoded = encode_source_lock(&sample_lock());

        assert!(encoded.starts_with(GENERATED_GLUON_MARKER));
        assert!(encoded.contains("type SourceResolution ="));
        assert!(encoded.contains("type SourceLock ="));
        assert!(encoded.contains("Archive {"));
        assert!(encoded.contains("sha256 = \"archive-sha256\","));
        assert!(encoded.contains("Git {"));
        assert!(encoded.contains("requested_ref = \"refs/tags/v1.2.3\","));
        assert!(encoded.contains(&format!("commit = \"{FULL_COMMIT}\",")));
        assert!(!encoded.contains("import!"));
    }

    #[test]
    fn encoding_order_is_canonical() {
        let lock = sample_lock();
        let mut reversed = lock.clone();
        reversed.sources.reverse();

        let encoded = encode_source_lock(&lock);

        assert_eq!(encoded, encode_source_lock(&reversed));
        assert!(encoded.find("Archive {").unwrap() < encoded.find("Git {").unwrap());
    }

    #[test]
    fn strings_are_escaped_deterministically() {
        let lock = SourceLock::new(vec![SourceResolution::Git(GitResolution {
            order: 0,
            url: "https://example.invalid/quoted\"/path\\leaf".to_owned(),
            requested_ref: "line\none\ttwo\rthree".to_owned(),
            commit: FULL_COMMIT.to_owned(),
        })]);

        let encoded = encode_source_lock(&lock);

        assert!(encoded.contains("url = \"https://example.invalid/quoted\\\"/path\\\\leaf\","));
        assert!(encoded.contains("requested_ref = \"line\\none\\ttwo\\rthree\","));
    }

    #[test]
    fn unchanged_lock_is_not_replaced() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(SOURCE_LOCK_FILE_NAME);
        let lock = sample_lock();

        assert_eq!(write_source_lock(&path, &lock).unwrap(), WriteOutcome::Written);
        let before = fs::metadata(&path).unwrap();
        assert_eq!(write_source_lock(&path, &lock).unwrap(), WriteOutcome::Unchanged);
        let after = fs::metadata(&path).unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            assert_eq!(before.ino(), after.ino());
        }
        assert_eq!(fs::read_to_string(path).unwrap(), encode_source_lock(&lock));
    }

    #[test]
    fn interrupted_atomic_replace_leaves_a_complete_old_or_new_lock() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(SOURCE_LOCK_FILE_NAME);
        let old_lock = sample_lock();
        let mut new_lock = sample_lock();
        new_lock.sources.push(SourceResolution::Archive(ArchiveResolution {
            order: 2,
            url: "https://example.invalid/second.tar.zst".to_owned(),
            sha256: "second-sha256".to_owned(),
        }));
        let old = encode_source_lock(&old_lock);
        let new = encode_source_lock(&new_lock);
        fs::write(&path, &old).unwrap();

        let error = atomic_write_with(&path, new.as_bytes(), |_| {
            Err(io::Error::new(io::ErrorKind::Interrupted, "simulated interruption"))
        })
        .unwrap_err();

        assert_eq!(error.kind(), io::ErrorKind::Interrupted);
        let after_interruption = fs::read_to_string(&path).unwrap();
        assert!(after_interruption == old || after_interruption == new);
        assert_eq!(after_interruption, old);

        assert_eq!(write_source_lock(&path, &new_lock).unwrap(), WriteOutcome::Written);
        assert_eq!(fs::read_to_string(path).unwrap(), new);
    }

    fn sample_lock() -> SourceLock {
        SourceLock::new(vec![
            SourceResolution::Git(GitResolution {
                order: 1,
                url: "https://example.invalid/project.git".to_owned(),
                requested_ref: "refs/tags/v1.2.3".to_owned(),
                commit: FULL_COMMIT.to_owned(),
            }),
            SourceResolution::Archive(ArchiveResolution {
                order: 0,
                url: "https://example.invalid/archive.tar.zst".to_owned(),
                sha256: "archive-sha256".to_owned(),
            }),
        ])
    }
}
