//! The Lua declaration engine — a second adapter over `declarative_config`.
//!
//! This crate owns only Lua-specific behavior: parsing and profile validation,
//! literal-import extraction, restricted VM construction, capability policy,
//! limit/deadline mapping, and bounded value-tree decoding. Source discovery,
//! graph limits, evaluation identity, persistence, and domain meaning all stay
//! in the shared core. The shared core gains no `if language == Lua` branch;
//! `LuaEngine` supplies opaque descriptors instead.

use declarative_config::{
    AbiCatalog, AbiId, EngineId, EvaluatorPolicyId, LanguageId, LanguageSpec,
    Limits, SourceRoot,
};

mod decode;
mod emit;
mod engine;
mod imports;
mod profile;
mod value;

pub use decode::{LuaOption, LuaPatch};
pub use emit::{
    lua_option, lua_optional_bool, lua_optional_integer, lua_optional_string, lua_string,
    pretty_lua,
};
pub use engine::{
    LuaPrepared, LuaRuntime, LuaSerdeDecoder, LuaValueDecoder, PreparedLuaModule,
};
pub use imports::discover_imports;
pub use profile::{ProfileViolation, validate_profile};
pub use value::{ValueLimits, validate_value_tree};

/// The exact vendored Lua release whose behavior this engine commits to.
pub const LUA_VERSION: &str = "5.4.7";

/// Version of the Rust/declaration-language configuration boundary.
///
/// Re-exported from `declarative_config`, which owns it: the boundary belongs to
/// the declaration contract rather than to any one adapter.
pub use declarative_config::CONFIGURATION_ABI_VERSION;

/// Version of the evaluator's security and determinism policy. Owned by
/// `declarative_config` for the same reason.
pub use declarative_config::EVALUATOR_POLICY_VERSION;

/// Generated-file ownership marker, written using Lua comment syntax.
pub const GENERATED_LUA_MARKER: &str = "-- @generated by cast. DO NOT EDIT.\n";

/// The neutral configuration-ABI descriptor.
///
/// Engine and language identity live in the evaluation identity, not in the ABI
/// name, so every adapter commits to the one descriptor `declarative_config`
/// defines.
pub fn lua_configuration_abi() -> AbiId {
    declarative_config::configuration_abi()
}

/// The neutral evaluator-policy descriptor.
pub fn lua_evaluator_policy() -> EvaluatorPolicyId {
    declarative_config::evaluator_policy()
}

/// The immutable public identity and file profile of the Lua adapter.
///
/// The `lua` language and `lua`/`{LUA_VERSION}` engine descriptors are what make
/// a Lua evaluation identity differ from that of any other configuration
/// language over otherwise-identical material.
pub fn lua_language_spec() -> LanguageSpec {
    LanguageSpec::new(
        LanguageId::new("lua").expect("Lua language identifier is canonical"),
        EngineId::new("lua", LUA_VERSION).expect("Lua engine identifier is canonical"),
        "lua",
        "declaration-v1",
        GENERATED_LUA_MARKER,
    )
    .expect("Lua language profile is canonical")
}

/// The Lua implementation of the shared declaration-engine contract.
///
/// Construction fixes the resource policy, capability profile, and embedded ABI
/// catalog. A source root is bound later (per evaluation) so relative imports
/// resolve beneath one retained descriptor.
#[derive(Debug, Clone)]
pub struct LuaEngine {
    limits: Limits,
    source_root: Option<SourceRoot>,
    abi_catalog: AbiCatalog,
    language_spec: LanguageSpec,
}

impl Default for LuaEngine {
    fn default() -> Self {
        Self::new(Limits::default())
    }
}

impl LuaEngine {
    pub fn new(limits: Limits) -> Self {
        Self {
            limits,
            source_root: None,
            abi_catalog: AbiCatalog::new(),
            language_spec: lua_language_spec(),
        }
    }

    /// Return the same engine rooted at one retained source authority.
    pub fn with_source_root(mut self, source_root: SourceRoot) -> Self {
        self.source_root = Some(source_root);
        self
    }

    /// Replace the embedded ABI catalog (the immutable module sources this
    /// engine will admit). The catalog is supplied by each domain, not the core.
    pub fn with_abi_catalog(mut self, abi_catalog: AbiCatalog) -> Self {
        self.abi_catalog = abi_catalog;
        self
    }

    pub fn limits(&self) -> Limits {
        self.limits
    }

    pub fn language_spec(&self) -> &LanguageSpec {
        &self.language_spec
    }

    pub fn source_root(&self) -> Option<&SourceRoot> {
        self.source_root.as_ref()
    }

    pub fn abi_catalog(&self) -> &AbiCatalog {
        &self.abi_catalog
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lua_descriptors_are_canonical_and_engine_specific() {
        let spec = lua_language_spec();
        assert_eq!(spec.language().as_str(), "lua");
        assert_eq!(spec.engine().implementation(), "lua");
        assert_eq!(spec.engine().version(), "5.4.7");
        assert_eq!(spec.extension(), "lua");
        assert_eq!(spec.generated_marker(), "-- @generated by cast. DO NOT EDIT.\n");

        // The configuration ABI and evaluator policy are engine-neutral; only
        // the engine/language descriptors differ, which is what separates one
        // engine's evaluation identity from another's.
        assert_eq!(lua_configuration_abi().name(), "cast.configuration");
        assert_eq!(lua_configuration_abi().version(), "1");
        assert_eq!(lua_evaluator_policy().as_str(), "1");
    }

    #[test]
    fn a_fresh_engine_has_default_limits_and_no_root() {
        let engine = LuaEngine::default();
        assert_eq!(engine.limits(), Limits::default());
        assert!(engine.source_root().is_none());
    }
}
