-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-plugin-output-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-plugin-output-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "mkdir"
            },
            {
                kind = "binary",
                value = "cc"
            },
            {
                kind = "binary",
                value = "dash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/mkdir",
                            requirement = {
                                kind = "binary",
                                value = "mkdir"
                            }
                        },
                        args = {
                            "-p",
                            "build"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-std=c11",
                            "-O2",
                            "-g",
                            "-Wall",
                            "-Wextra",
                            "-Werror",
                            "-fstack-protector-strong",
                            "-D_FORTIFY_SOURCE=3",
                            "-fPIC",
                            "-shared",
                            "plugin.c",
                            "-Wl,-soname,cast-plugin-output.so",
                            "-Wl,--build-id=sha1",
                            "-Wl,-z,relro,-z,now",
                            "-Wl,-z,noexecstack",
                            "-Wl,-z,separate-code",
                            "-Wl,--no-undefined",
                            "-o",
                            "build/cast-plugin-output.so"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-std=c11",
                            "-O2",
                            "-g",
                            "-Wall",
                            "-Wextra",
                            "-Werror",
                            "-fstack-protector-strong",
                            "-D_FORTIFY_SOURCE=3",
                            "-fPIE",
                            "host.c",
                            "-Wl,-pie",
                            "-Wl,--build-id=sha1",
                            "-Wl,-z,relro,-z,now",
                            "-Wl,-z,noexecstack",
                            "-Wl,-z,separate-code",
                            "-Wl,--as-needed",
                            "-ldl",
                            "-o",
                            "build/cast-plugin-host"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\ninstall -Dm755 build/cast-plugin-host \\\n    \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/cast-plugin-host\"\ninstall -Dm644 build/cast-plugin-output.so \\\n    \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/cast/plugins/cast-plugin-output.so\"\n"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run_built",
                        program = {
                            path = "build/cast-plugin-host"
                        },
                        args = {
                            "--plugin",
                            "build/cast-plugin-output.so"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Explicit runtime-loaded plugin host"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-plugin-output-fixture"
                        },
                        output = "plugins"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/cast-plugin-host"
                }
            },
            conflicts = {}
        },
        {
            name = "plugins",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Explicit runtime-loaded plugin"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/cast/plugins/cast-plugin-output.so"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Plugin host and module debugging symbols"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-plugin-output-fixture-1.0.0.tar",
            hash = "467879af548882eb7c2a2197d475b54ec8cc5106c82631b7bd8204b13d8c5319",
            rename = {
                kind = "some",
                value = "cast-plugin-output-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-plugin-output-fixture"
            }
        }
    },
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}