use crate::linux_fs::descriptor_boot_namespace::{
    BootNamespaceAssessmentLimits, RetainedBootNamespaceAssessmentLimits,
};

pub(super) const HARD_MAX_PUBLICATION_BYTES: u64 = 16 * 1024 * 1024 * 1024;
pub(super) const HARD_MAX_PUBLICATION_WRITE_CALLS: usize = 8 * 1024 * 1024;

/// Exact immutable content request for one already-existing retained parent.
///
/// The leaf is a single destination component, not a path. The SHA-256 value
/// authenticates exact bytes independently from the XXH3 checksum retained by
/// the existing namespace and path protocol.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct RetainedBootFilePublicationRequest<'a> {
    canonical_leaf: &'a str,
    expected_length: u64,
    expected_xxh3: u128,
    expected_sha256: [u8; 32],
}
impl<'a> RetainedBootFilePublicationRequest<'a> {
    pub(crate) const fn new(
        canonical_leaf: &'a str,
        expected_length: u64,
        expected_xxh3: u128,
        expected_sha256: [u8; 32],
    ) -> Self {
        Self {
            canonical_leaf,
            expected_length,
            expected_xxh3,
            expected_sha256,
        }
    }

    pub(crate) const fn canonical_leaf(self) -> &'a str {
        self.canonical_leaf
    }

    pub(crate) const fn expected_length(self) -> u64 {
        self.expected_length
    }

    pub(crate) const fn expected_xxh3(self) -> u128 {
        self.expected_xxh3
    }

    pub(crate) const fn expected_sha256(self) -> [u8; 32] {
        self.expected_sha256
    }
}

/// Independent ceilings for one leaf-publication attempt.
///
/// Namespace and source limits are reused unchanged from the retained
/// destination observer. Write admission is separate because generated bytes
/// require no physical expected-source reads.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct RetainedBootFilePublicationLimits {
    pub(crate) namespace: BootNamespaceAssessmentLimits,
    pub(crate) retained_namespace: RetainedBootNamespaceAssessmentLimits,
    pub(crate) max_write_bytes: u64,
    pub(crate) max_write_calls: usize,
}

impl Default for RetainedBootFilePublicationLimits {
    fn default() -> Self {
        Self {
            namespace: BootNamespaceAssessmentLimits::default(),
            retained_namespace: RetainedBootNamespaceAssessmentLimits::default(),
            max_write_bytes: HARD_MAX_PUBLICATION_BYTES,
            max_write_calls: HARD_MAX_PUBLICATION_WRITE_CALLS,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum RetainedBootFilePublicationOutcome {
    Published,
    AlreadyExact,
}

/// Closed terminal evidence for one durable leaf outcome.
///
/// This value retains scalars only. In particular it contains no descriptor,
/// path resolver, callback, or future mutation authority.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ValidatedRetainedBootFilePublication {
    outcome: RetainedBootFilePublicationOutcome,
    destination_device: u64,
    destination_inode: u64,
    destination_mount_id: u64,
    file_device: u64,
    file_inode: u64,
    length: u64,
    xxh3: u128,
    sha256: [u8; 32],
}

impl ValidatedRetainedBootFilePublication {
    #[allow(clippy::too_many_arguments)]
    pub(super) const fn new(
        outcome: RetainedBootFilePublicationOutcome,
        destination_device: u64,
        destination_inode: u64,
        destination_mount_id: u64,
        file_device: u64,
        file_inode: u64,
        length: u64,
        xxh3: u128,
        sha256: [u8; 32],
    ) -> Self {
        Self {
            outcome,
            destination_device,
            destination_inode,
            destination_mount_id,
            file_device,
            file_inode,
            length,
            xxh3,
            sha256,
        }
    }

    pub(crate) const fn outcome(self) -> RetainedBootFilePublicationOutcome {
        self.outcome
    }

    pub(crate) const fn destination_device(self) -> u64 {
        self.destination_device
    }

    pub(crate) const fn destination_inode(self) -> u64 {
        self.destination_inode
    }

    pub(crate) const fn destination_mount_id(self) -> u64 {
        self.destination_mount_id
    }

    pub(crate) const fn file_device(self) -> u64 {
        self.file_device
    }

    pub(crate) const fn file_inode(self) -> u64 {
        self.file_inode
    }

    pub(crate) const fn length(self) -> u64 {
        self.length
    }

    pub(crate) const fn xxh3(self) -> u128 {
        self.xxh3
    }

    pub(crate) const fn sha256(self) -> [u8; 32] {
        self.sha256
    }
}
