use std::{
    cell::Cell,
    fs::{File, OpenOptions},
    io::Write as _,
    os::{
        fd::{AsFd as _, AsRawFd as _, FromRawFd as _, OwnedFd},
        unix::fs::OpenOptionsExt as _,
    },
    path::Path,
    time::{Duration, Instant},
};

use xxhash_rust::xxh3::xxh3_128;

use super::*;
use crate::linux_fs::descriptor_boot_namespace::RetainedBootNamespaceExpectedSource;

const FULL_SEALS: i32 =
    nix::libc::F_SEAL_WRITE | nix::libc::F_SEAL_GROW | nix::libc::F_SEAL_SHRINK | nix::libc::F_SEAL_SEAL;

fn target_temporary(prefix: &str) -> tempfile::TempDir {
    let target = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target");
    std::fs::create_dir_all(&target).unwrap();
    tempfile::Builder::new().prefix(prefix).tempdir_in(target).unwrap()
}

fn retained_root(path: &Path) -> File {
    OpenOptions::new()
        .read(true)
        .custom_flags(nix::libc::O_PATH | nix::libc::O_DIRECTORY | nix::libc::O_CLOEXEC | nix::libc::O_NOFOLLOW)
        .open(path)
        .unwrap()
}

fn request<'path>(path: &'path str, bytes: &[u8]) -> BootNamespaceRequest<'path> {
    BootNamespaceRequest::new(path, bytes.len() as u64, xxh3_128(bytes))
}

fn sealed_memfd(bytes: &[u8], mode: u32, seals: i32, cloexec: bool) -> File {
    // SAFETY: the static C string remains live for the one memfd_create call.
    let raw = unsafe {
        nix::libc::syscall(
            nix::libc::SYS_memfd_create,
            c"forge-expected-source".as_ptr(),
            nix::libc::MFD_CLOEXEC | nix::libc::MFD_ALLOW_SEALING,
        )
    };
    assert!(raw >= 0, "memfd_create failed: {}", std::io::Error::last_os_error());
    let raw = i32::try_from(raw).unwrap();
    // SAFETY: successful memfd_create returned this fresh owned descriptor.
    let owned = unsafe { OwnedFd::from_raw_fd(raw) };
    let mut file = File::from(owned);
    file.write_all(bytes).unwrap();
    // SAFETY: fchmod observes the live descriptor and retains no argument.
    assert_eq!(unsafe { nix::libc::fchmod(file.as_raw_fd(), mode) }, 0);
    if seals != 0 {
        // SAFETY: F_ADD_SEALS consumes only the integer mask for this live memfd.
        assert_eq!(
            unsafe { nix::libc::fcntl(file.as_raw_fd(), nix::libc::F_ADD_SEALS, seals) },
            0
        );
    }
    set_cloexec(&file, cloexec);
    file
}

fn set_cloexec(file: &File, enabled: bool) {
    let flags = if enabled { nix::libc::FD_CLOEXEC } else { 0 };
    // SAFETY: F_SETFD changes descriptor-local flags and retains no argument.
    assert_eq!(
        unsafe { nix::libc::fcntl(file.as_raw_fd(), nix::libc::F_SETFD, flags) },
        0
    );
}

fn assess_sealed(
    root: &File,
    path: &str,
    request_bytes: &[u8],
    source: &File,
    limits: RetainedBootNamespaceAssessmentLimits,
) -> Result<ValidatedRetainedBootNamespaceAssessment, RetainedBootNamespaceAssessmentError> {
    let requests = [request(path, request_bytes)];
    let expected = [RetainedBootNamespaceExpectedSource::sealed_descriptor(source.as_fd())];
    assess_retained_boot_namespace_until(
        root,
        &requests,
        &expected,
        BootNamespaceAssessmentLimits::default(),
        limits,
        Instant::now() + Duration::from_secs(30),
    )
}

#[test]
fn sealed_source_larger_than_one_chunk_streams_exactly_with_physical_usage() {
    let temporary = target_temporary("forge-retained-expected-stream-");
    let bytes = (0..(3 * 4096 + 37))
        .map(|index| ((index * 17 + 11) % 251) as u8)
        .collect::<Vec<_>>();
    std::fs::write(temporary.path().join("loader"), &bytes).unwrap();
    let root = retained_root(temporary.path());
    let source = sealed_memfd(&bytes, 0o400, FULL_SEALS, true);

    let assessment = assess_sealed(
        &root,
        "loader",
        &bytes,
        &source,
        RetainedBootNamespaceAssessmentLimits::default(),
    )
    .unwrap();

    assert_eq!(assessment.states(), &[BootNamespaceDestinationState::Exact]);
    let chunks = bytes.len().div_ceil(4096);
    let usage = assessment.fixture_usage();
    assert_eq!(usage.expected_hash_bytes, bytes.len() as u64);
    assert_eq!(usage.expected_hash_chunks, chunks);
    assert_eq!(usage.expected_source_read_bytes, 2 * bytes.len() as u64 + 2);
    assert_eq!(usage.expected_source_read_calls, 2 * chunks + 2);
}

#[test]
fn generated_source_uses_no_physical_expected_source_io() {
    let temporary = target_temporary("forge-retained-generated-source-");
    let bytes = b"generated bytes".as_slice();
    std::fs::write(temporary.path().join("loader"), bytes).unwrap();
    let root = retained_root(temporary.path());
    let requests = [request("loader", bytes)];
    let expected = [RetainedBootNamespaceExpectedSource::generated(bytes)];

    let assessment = assess_retained_boot_namespace_until(
        &root,
        &requests,
        &expected,
        BootNamespaceAssessmentLimits::default(),
        RetainedBootNamespaceAssessmentLimits::default(),
        Instant::now() + Duration::from_secs(30),
    )
    .unwrap();

    assert_eq!(assessment.states(), &[BootNamespaceDestinationState::Exact]);
    assert_eq!(assessment.fixture_usage().expected_source_read_bytes, 0);
    assert_eq!(assessment.fixture_usage().expected_source_read_calls, 0);

    let sealed = sealed_memfd(bytes, 0o400, FULL_SEALS, true);
    let sealed_assessment = assess_sealed(
        &root,
        "loader",
        bytes,
        &sealed,
        RetainedBootNamespaceAssessmentLimits::default(),
    )
    .unwrap();
    let expected_source_calls = 9 + 2 * (bytes.len().div_ceil(4096) + 1);
    assert_eq!(
        sealed_assessment.fixture_usage().observation_io_attempts,
        assessment.fixture_usage().observation_io_attempts + expected_source_calls,
    );
}

#[test]
fn sealed_source_capability_failures_precede_root_observation() {
    let temporary = target_temporary("forge-retained-source-capability-");
    let root = retained_root(temporary.path());
    let bytes = b"sealed".as_slice();
    let fixtures = [
        sealed_memfd(bytes, 0o400, FULL_SEALS & !nix::libc::F_SEAL_WRITE, true),
        sealed_memfd(bytes, 0o400, FULL_SEALS & !nix::libc::F_SEAL_GROW, true),
        sealed_memfd(bytes, 0o400, FULL_SEALS & !nix::libc::F_SEAL_SHRINK, true),
        sealed_memfd(bytes, 0o400, FULL_SEALS & !nix::libc::F_SEAL_SEAL, true),
        sealed_memfd(bytes, 0o600, FULL_SEALS, true),
        sealed_memfd(bytes, 0o400, FULL_SEALS, false),
    ];

    for source in &fixtures {
        let requests = [request("missing", bytes)];
        let expected = [RetainedBootNamespaceExpectedSource::sealed_descriptor(source.as_fd())];
        let events = Cell::new(0usize);
        let mut hook = |_| {
            events.set(events.get() + 1);
            Ok(())
        };
        let error = assess_retained_boot_namespace_with_hook_until(
            &root,
            &requests,
            &expected,
            BootNamespaceAssessmentLimits::default(),
            RetainedBootNamespaceAssessmentLimits::default(),
            Instant::now() + Duration::from_secs(30),
            &mut hook,
        )
        .unwrap_err();
        assert!(matches!(error, RetainedBootNamespaceAssessmentError::Filesystem { .. }));
        assert_eq!(events.get(), 0);
    }
}

#[test]
fn sealed_source_length_and_digest_mismatch_precede_root_observation() {
    let temporary = target_temporary("forge-retained-source-identity-");
    let root = retained_root(temporary.path());
    let bytes = b"sealed".as_slice();
    let source = sealed_memfd(bytes, 0o400, FULL_SEALS, true);
    let fixtures = [
        (
            BootNamespaceRequest::new("missing", bytes.len() as u64 + 1, xxh3_128(bytes)),
            false,
        ),
        (
            BootNamespaceRequest::new("missing", bytes.len() as u64, xxh3_128(b"forged")),
            true,
        ),
    ];

    for (request, digest_mismatch) in fixtures {
        let requests = [request];
        let expected = [RetainedBootNamespaceExpectedSource::sealed_descriptor(source.as_fd())];
        let events = Cell::new(0usize);
        let mut hook = |_| {
            events.set(events.get() + 1);
            Ok(())
        };
        let error = assess_retained_boot_namespace_with_hook_until(
            &root,
            &requests,
            &expected,
            BootNamespaceAssessmentLimits::default(),
            RetainedBootNamespaceAssessmentLimits::default(),
            Instant::now() + Duration::from_secs(30),
            &mut hook,
        )
        .unwrap_err();
        if digest_mismatch {
            assert!(matches!(
                error,
                RetainedBootNamespaceAssessmentError::ExpectedDigestMismatch { request_index: 0 }
            ));
        } else {
            assert!(matches!(
                error,
                RetainedBootNamespaceAssessmentError::Filesystem { .. }
            ));
        }
        assert_eq!(events.get(), 0);
    }
}

#[test]
fn sealed_source_read_budgets_accept_exact_usage_and_reject_n_minus_one() {
    let temporary = target_temporary("forge-retained-source-budget-");
    let bytes = vec![0x5a; 4096 + 19];
    std::fs::write(temporary.path().join("loader"), &bytes).unwrap();
    let root = retained_root(temporary.path());
    let source = sealed_memfd(&bytes, 0o400, FULL_SEALS, true);

    let baseline = assess_sealed(
        &root,
        "loader",
        &bytes,
        &source,
        RetainedBootNamespaceAssessmentLimits::default(),
    )
    .unwrap()
    .fixture_usage();
    assert!(baseline.expected_source_read_bytes > 1);
    assert!(baseline.expected_source_read_calls > 1);

    let exact = RetainedBootNamespaceAssessmentLimits {
        max_observation_io_attempts: baseline.observation_io_attempts,
        max_expected_source_read_bytes: baseline.expected_source_read_bytes,
        max_expected_source_read_calls: baseline.expected_source_read_calls,
        ..RetainedBootNamespaceAssessmentLimits::default()
    };
    assert!(assess_sealed(&root, "loader", &bytes, &source, exact).is_ok());

    let short_bytes = RetainedBootNamespaceAssessmentLimits {
        max_expected_source_read_bytes: baseline.expected_source_read_bytes - 1,
        ..exact
    };
    assert!(matches!(
        assess_sealed(&root, "loader", &bytes, &source, short_bytes),
        Err(RetainedBootNamespaceAssessmentError::LiveBudgetExceeded {
            field: "expected source read bytes",
            ..
        })
    ));

    let short_calls = RetainedBootNamespaceAssessmentLimits {
        max_expected_source_read_calls: baseline.expected_source_read_calls - 1,
        ..exact
    };
    assert!(matches!(
        assess_sealed(&root, "loader", &bytes, &source, short_calls),
        Err(RetainedBootNamespaceAssessmentError::LiveBudgetExceeded {
            field: "expected source read calls",
            ..
        })
    ));

    let short_io = RetainedBootNamespaceAssessmentLimits {
        max_observation_io_attempts: baseline.observation_io_attempts - 1,
        ..exact
    };
    assert!(matches!(
        assess_sealed(&root, "loader", &bytes, &source, short_io),
        Err(RetainedBootNamespaceAssessmentError::LiveBudgetExceeded {
            field: "observation I/O attempts",
            ..
        })
    ));
}

#[test]
fn terminal_source_revalidation_rejects_descriptor_flag_drift() {
    let temporary = target_temporary("forge-retained-source-terminal-");
    let bytes = b"terminal evidence".as_slice();
    std::fs::write(temporary.path().join("loader"), bytes).unwrap();
    let root = retained_root(temporary.path());
    let source = sealed_memfd(bytes, 0o400, FULL_SEALS, true);
    let requests = [request("loader", bytes)];
    let expected = [RetainedBootNamespaceExpectedSource::sealed_descriptor(source.as_fd())];
    let changed = Cell::new(false);
    let completed = Cell::new(false);
    let mut hook = |event| {
        if matches!(event, FixtureRetainedBootNamespaceProtocolEvent::ActualRead { .. }) && !changed.replace(true) {
            set_cloexec(&source, false);
        }
        if matches!(event, FixtureRetainedBootNamespaceProtocolEvent::Complete) {
            completed.set(true);
        }
        Ok(())
    };

    let error = assess_retained_boot_namespace_with_hook_until(
        &root,
        &requests,
        &expected,
        BootNamespaceAssessmentLimits::default(),
        RetainedBootNamespaceAssessmentLimits::default(),
        Instant::now() + Duration::from_secs(30),
        &mut hook,
    )
    .unwrap_err();

    assert!(changed.get());
    assert!(!completed.get());
    assert!(matches!(error, RetainedBootNamespaceAssessmentError::Filesystem { .. }));
}
