-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "vector-header",
        version = "1.8.0",
        release = 1,
        homepage = "https://example.invalid/vector-header",
        license = {
            "MIT"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "cc"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\ninstall -d \"${CAST_INSTALL_ROOT}${CAST_PREFIX}/include/vector-header\"\ninstall -m644 include/*.h \"${CAST_INSTALL_ROOT}${CAST_PREFIX}/include/vector-header/\"\ninstall -Dm644 vector-header.pc \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/pkgconfig/vector-header.pc\"\ninstall -Dm644 LICENSE \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/licenses/vector-header/LICENSE\"\n"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-I./include",
                            "-fsyntax-only",
                            "tests/smoke.c"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Vector header license metadata"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/licenses/vector-header"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Header-only vector interfaces"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include/vector-header"
                },
                {
                    kind = "any",
                    path = "/usr/lib/pkgconfig/vector-header.pc"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/vector-header-1.8.0.tar.xz",
            hash = "6789abcdef0123456789abcdef0123456789abcdef0123456789abcdef012345",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}