use std::{
    os::unix::{ffi::OsStringExt as _, fs::symlink},
    path::{Path, PathBuf},
};

use declarative_config::{EngineId, LanguageId, LanguageSpec};
use fs_err as fs;
use tempfile::tempdir;

use super::*;

fn language(name: &str, extension: &str) -> LanguageSpec {
    LanguageSpec::new(
        LanguageId::new(name).unwrap(),
        EngineId::new(format!("{name}-engine"), "1").unwrap(),
        extension,
        "declaration-v1",
        format!("# generated by {name}\n"),
    )
    .unwrap()
}

fn languages() -> RegisteredLanguages {
    RegisteredLanguages::new([
        language("fixture", "abc"),
        language("alternate", "xyz"),
    ])
    .unwrap()
}

fn limits(max_fragments: usize, max_directory_entries: usize) -> FragmentDeclarationLimits {
    FragmentDeclarationLimits::new(max_fragments, max_directory_entries)
}

fn write(path: impl AsRef<Path>, contents: &str) {
    let path = path.as_ref();
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, contents).unwrap();
}

fn discover(
    root_path: &Path,
    root: &fs::File,
    max_fragments: usize,
    max_directory_entries: usize,
) -> Result<RootedFragmentDeclarationSet, RootedFragmentDeclarationSetError> {
    RootedFragmentDeclarationSet::discover(
        root_path,
        root,
        "bundle",
        &languages(),
        limits(max_fragments, max_directory_entries),
    )
}

#[test]
fn retained_tree_is_authoritative_after_public_path_substitution() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    let detached = temporary.path().join("detached");
    write(root_path.join("bundle.abc"), "retained root");
    write(root_path.join("bundle.d/value.xyz"), "retained fragment");
    let retained = fs::File::open(&root_path).unwrap();

    fs::rename(&root_path, &detached).unwrap();
    write(root_path.join("bundle.abc"), "injected root");
    write(root_path.join("bundle.d/injected.abc"), "injected fragment");

    let set = discover(&root_path, &retained, 2, 1).unwrap();
    assert_eq!(set.root_path(), root_path);
    assert_eq!(set.domain(), "bundle");
    assert_eq!(set.source_root().path(), root_path);
    assert_eq!(set.len(), 2);
    assert_eq!(
        set.iter()
            .map(|declaration| (
                declaration.logical_name(),
                declaration.relative_path(),
                declaration.language().extension(),
            ))
            .collect::<Vec<_>>(),
        [
            ("bundle", Path::new("bundle.abc"), "abc"),
            ("value", Path::new("bundle.d/value.xyz"), "xyz"),
        ]
    );
    assert_eq!(set.declarations()[0].root_path(), root_path);
    assert_eq!(
        set.declarations()[0].physical_path(),
        root_path.join("bundle.abc")
    );
    assert_eq!(
        set.declarations()[0].read_source(64).unwrap().text(),
        "retained root"
    );
    assert_eq!(
        set.declarations()[1].read_source(64).unwrap().text(),
        "retained fragment"
    );
    set.revalidate().unwrap();
}

#[test]
fn exact_registered_extensions_are_sorted_and_unknown_entries_are_ignored() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    write(root_path.join("bundle.abc"), "root");
    write(root_path.join("bundle.unknown"), "ignored root");
    write(root_path.join("bundle.d/zeta.abc"), "zeta");
    write(root_path.join("bundle.d/alpha.xyz"), "alpha");
    fs::create_dir_all(root_path.join("bundle.d/directory.unknown")).unwrap();
    write(root_path.join("bundle.d/plain"), "ignored plain entry");
    let retained = fs::File::open(&root_path).unwrap();

    let first = discover(&root_path, &retained, 3, 4).unwrap();
    let repeated = discover(&root_path, &retained, 3, 4).unwrap();
    let identities = |set: &RootedFragmentDeclarationSet| {
        set.iter()
            .map(|declaration| (
                declaration.logical_name().to_owned(),
                declaration.relative_path().to_owned(),
                declaration.language().extension().to_owned(),
            ))
            .collect::<Vec<_>>()
    };

    assert_eq!(identities(&first), identities(&repeated));
    assert_eq!(
        identities(&first),
        [
            (
                "bundle".to_owned(),
                PathBuf::from("bundle.abc"),
                "abc".to_owned(),
            ),
            (
                "alpha".to_owned(),
                PathBuf::from("bundle.d/alpha.xyz"),
                "xyz".to_owned(),
            ),
            (
                "zeta".to_owned(),
                PathBuf::from("bundle.d/zeta.abc"),
                "abc".to_owned(),
            ),
        ]
    );
}

#[test]
fn every_same_root_logical_collision_is_rejected_with_sorted_paths() {
    let root_extensions = tempdir().unwrap();
    let root_path = root_extensions.path().join("root");
    write(root_path.join("bundle.xyz"), "one");
    write(root_path.join("bundle.abc"), "two");
    let retained = fs::File::open(&root_path).unwrap();
    let error = discover(&root_path, &retained, 8, 8).unwrap_err();
    assert!(matches!(
        error,
        RootedFragmentDeclarationSetError::Collision {
            ref logical_name,
            ref paths,
        } if logical_name == "bundle"
            && paths == &[
                root_path.join("bundle.abc"),
                root_path.join("bundle.xyz"),
            ]
    ));

    let fragment_extensions = tempdir().unwrap();
    let root_path = fragment_extensions.path().join("root");
    write(root_path.join("bundle.d/shared.xyz"), "one");
    write(root_path.join("bundle.d/shared.abc"), "two");
    let retained = fs::File::open(&root_path).unwrap();
    let error = discover(&root_path, &retained, 8, 8).unwrap_err();
    assert!(matches!(
        error,
        RootedFragmentDeclarationSetError::Collision {
            ref logical_name,
            ref paths,
        } if logical_name == "shared"
            && paths == &[
                root_path.join("bundle.d/shared.abc"),
                root_path.join("bundle.d/shared.xyz"),
            ]
    ));

    let root_and_fragment = tempdir().unwrap();
    let root_path = root_and_fragment.path().join("root");
    write(root_path.join("bundle.xyz"), "root");
    write(root_path.join("bundle.d/bundle.abc"), "fragment");
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 8, 8),
        Err(RootedFragmentDeclarationSetError::Collision {
            ref logical_name,
            ref paths,
        }) if logical_name == "bundle" && paths.len() == 2
    ));
}

#[test]
fn matching_nonregular_links_and_invalid_names_fail_closed() {
    let root_directory = tempdir().unwrap();
    let root_path = root_directory.path().join("root");
    fs::create_dir_all(root_path.join("bundle.abc")).unwrap();
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 4, 4),
        Err(RootedFragmentDeclarationSetError::NotRegular { .. })
    ));

    let fragment_directory = tempdir().unwrap();
    let root_path = fragment_directory.path().join("root");
    fs::create_dir_all(root_path.join("bundle.d/value.xyz")).unwrap();
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 4, 4),
        Err(RootedFragmentDeclarationSetError::NotRegular { .. })
    ));

    let collection_file = tempdir().unwrap();
    let root_path = collection_file.path().join("root");
    write(root_path.join("bundle.d"), "not a directory");
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 4, 4),
        Err(RootedFragmentDeclarationSetError::CollectionNotDirectory { .. })
    ));

    let linked = tempdir().unwrap();
    let root_path = linked.path().join("root");
    write(linked.path().join("outside"), "outside");
    fs::create_dir(&root_path).unwrap();
    symlink(linked.path().join("outside"), root_path.join("bundle.abc")).unwrap();
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 4, 4),
        Err(RootedFragmentDeclarationSetError::InspectDeclaration { .. })
            | Err(RootedFragmentDeclarationSetError::NotRegular { .. })
    ));

    let non_utf8 = tempdir().unwrap();
    let root_path = non_utf8.path().join("root");
    let invalid = std::ffi::OsString::from_vec(b"\xff.abc".to_vec());
    write(root_path.join("bundle.d").join(invalid), "invalid");
    let retained = fs::File::open(&root_path).unwrap();
    assert!(matches!(
        discover(&root_path, &retained, 4, 4),
        Err(RootedFragmentDeclarationSetError::InvalidLogicalName { .. })
    ));

    let unsafe_name = tempdir().unwrap();
    let root_path = unsafe_name.path().join("root");
    write(root_path.join("bundle.d/a\\name.abc"), "invalid");
    write(root_path.join("bundle.d/z\nname.abc"), "also invalid");
    let retained = fs::File::open(&root_path).unwrap();
    let error = discover(&root_path, &retained, 4, 4).unwrap_err();
    assert!(matches!(
        error,
        RootedFragmentDeclarationSetError::InvalidLogicalName { ref path }
            if path == &root_path.join("bundle.d/a\\name.abc")
    ));
}

#[test]
fn limits_count_all_directory_entries_and_every_registered_fragment() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    write(root_path.join("bundle.abc"), "root");
    write(root_path.join("bundle.d/value.xyz"), "fragment");
    write(root_path.join("bundle.d/ignored.unknown"), "ignored");
    let retained = fs::File::open(&root_path).unwrap();

    assert_eq!(discover(&root_path, &retained, 2, 2).unwrap().len(), 2);
    assert!(matches!(
        discover(&root_path, &retained, 1, 2),
        Err(RootedFragmentDeclarationSetError::FragmentLimit {
            limit: 1,
            discovered: 2,
        })
    ));
    assert!(matches!(
        discover(&root_path, &retained, 2, 1),
        Err(RootedFragmentDeclarationSetError::DirectoryEntryLimit {
            limit: 1,
            ..
        })
    ));
}

#[test]
fn file_collection_and_import_directory_substitution_are_detected() {
    let file_case = tempdir().unwrap();
    let root_path = file_case.path().join("root");
    let detached = file_case.path().join("detached-file");
    write(root_path.join("bundle.abc"), "retained");
    let retained = fs::File::open(&root_path).unwrap();
    let set = discover(&root_path, &retained, 1, 0).unwrap();
    fs::rename(root_path.join("bundle.abc"), &detached).unwrap();
    write(root_path.join("bundle.abc"), "injected");
    assert!(matches!(
        set.declarations()[0].revalidate_before_evaluation(),
        Err(RootedFragmentDeclarationSetError::DeclarationChanged { .. })
    ));

    let collection_case = tempdir().unwrap();
    let root_path = collection_case.path().join("root");
    let collection = root_path.join("bundle.d");
    let detached = root_path.join("detached-collection");
    write(collection.join("value.abc"), "retained");
    let retained = fs::File::open(&root_path).unwrap();
    let set = discover(&root_path, &retained, 1, 1).unwrap();
    let declaration = &set.declarations()[0];
    declaration.read_source(64).unwrap();
    fs::rename(&collection, &detached).unwrap();
    write(collection.join("value.abc"), "injected");
    assert!(matches!(
        declaration.revalidate_after_evaluation(),
        Err(RootedFragmentDeclarationSetError::CollectionChanged { .. })
            | Err(RootedFragmentDeclarationSetError::VerifyRetainedDirectories { .. })
    ));

    let import_case = tempdir().unwrap();
    let root_path = import_case.path().join("root");
    let modules = root_path.join("bundle.d/modules");
    let detached = import_case.path().join("detached-modules");
    write(root_path.join("bundle.d/main.abc"), "main");
    write(modules.join("anchor.abc"), "anchor");
    write(modules.join("value.abc"), "retained import");
    let retained = fs::File::open(&root_path).unwrap();
    let set = discover(&root_path, &retained, 1, 3).unwrap();
    let declaration = &set.declarations()[0];
    declaration
        .source_root()
        .load("bundle.d/modules/anchor.abc", 64)
        .unwrap();
    fs::rename(&modules, &detached).unwrap();
    fs::create_dir(&modules).unwrap();
    write(modules.join("value.abc"), "injected import");
    let error = declaration
        .source_root()
        .load("bundle.d/modules/value.abc", 64)
        .unwrap_err();
    assert!(error.message.contains("source directory changed"));
}

#[test]
fn source_reads_are_bounded_and_domains_are_safe() {
    let temporary = tempdir().unwrap();
    let root_path = temporary.path().join("root");
    write(root_path.join("bundle.abc"), "12345");
    let retained = fs::File::open(&root_path).unwrap();
    let set = discover(&root_path, &retained, 1, 0).unwrap();
    assert!(matches!(
        set.declarations()[0].read_source(4),
        Err(RootedFragmentDeclarationSetError::ReadSource { .. })
    ));

    for domain in ["", ".", "..", "nested/name", "nested\\name", "line\nbreak"] {
        assert!(matches!(
            RootedFragmentDeclarationSet::discover(
                &root_path,
                &retained,
                domain,
                &languages(),
                limits(1, 1),
            ),
            Err(RootedFragmentDeclarationSetError::InvalidDomain { .. })
        ));
    }
}
