# SPDX-FileCopyrightText: 2025 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0

[default]

[default.extend-identifiers]
"3e1ba34" = "3e1ba34"
"0f041afe" = "0f041afe"

[default.extend-words]
restat = "restat"
# OpenType's mandatory glyph-location table tag.
loca = "loca"

# thanks to base yamls
idae = "idae"

[files]
extend-exclude = ["serpent-style/**/*"]
