-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "zig-vector",
        version = "0.8.0",
        release = 1,
        homepage = "https://example.invalid/zig-vector",
        license = {
            "MIT"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "zig"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {},
                        script = "test -f build.zig\ntest -f build.zig.zon\ntest -d vendor"
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/zig",
                                requirement = {
                                    kind = "binary",
                                    value = "zig"
                                }
                            }
                        },
                        script = "ZIG_GLOBAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-global-cache\" \\\nZIG_LOCAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-local-cache\" \\\nzig build -Doptimize=ReleaseSafe"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/zig",
                                requirement = {
                                    kind = "binary",
                                    value = "zig"
                                }
                            }
                        },
                        script = "ZIG_GLOBAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-global-cache\" \\\nZIG_LOCAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-local-cache\" \\\nzig build install -Doptimize=ReleaseSafe --prefix \"${CAST_INSTALL_ROOT}${CAST_PREFIX}\""
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/zig",
                                requirement = {
                                    kind = "binary",
                                    value = "zig"
                                }
                            }
                        },
                        script = "ZIG_GLOBAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-global-cache\" \\\nZIG_LOCAL_CACHE_DIR=\"${CAST_BUILD_ROOT}/zig-local-cache\" \\\nzig build test -Doptimize=ReleaseSafe"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Vector conversion command-line tool"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "zig-vector"
                        },
                        output = "libs"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/zig-vector"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Zig vector conversion runtime library"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/libzig-vector.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Headers and link-time library for zig-vector"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "zig-vector"
                        },
                        output = "libs"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include/zig-vector"
                },
                {
                    kind = "symlink",
                    path = "/usr/lib/libzig-vector.so"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/zig-vector-0.8.0-vendored.tar.xz",
            hash = "23456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef01",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}