//! Real startup-entry contracts for the ActiveReblit rollback suffix.

mod candidate_wrapper_exchange_kill_boundaries;
mod candidate_wrapper_exchange_process_harness;
mod candidate_wrapper_exchange_process_kill;
mod complete_authority_binding;
mod complete_evidence_races;
mod complete_exclusions;
mod complete_matrix;
mod complete_restart;
mod complete_storage_faults;
mod durability_failures;
mod effect_failures;
mod evidence_races;
mod exclusions;
mod finalization_authority_binding;
mod finalization_boundaries;
mod finalization_evidence_races;
mod finalization_lock_handoff;
mod finalization_matrix;
mod finalization_process_kill;
mod finalization_public_binding_races;
mod finalization_restart;
mod finalization_storage_faults;
mod matrix;
mod new_state_regression;
mod restart;
mod storage_faults;
mod support;
