.PHONY: help

help:
	@echo
	@echo "Usage: make [target]"
	@echo
	@echo "Available targets:"
	@echo "  build         Build the complete workspace"
	@echo "  cast          Build Cast with MODE=$(MODE) (default)"
	@echo "  get-started   Build and install Cast and its data"
	@echo "  test          Run lints and all workspace tests"
	@timeout 10s echo "  userspace-profile-declaration-test  Check deterministic source-less userspace composition"
	@echo "  forge-read-only-installation-test  Run retained read-only snapshot and mutable-client rejection tests"
	@echo "  forge-installation-test  Run all direct installation policy and filesystem tests"
	@echo "  forge-mutable-startup-namespace-test  Run retained mutable startup namespace substitution tests"
	@timeout 10s echo "  forge-mutable-system-capabilities-test  Run coherent mutable startup capability and drop-order contracts"
	@timeout 10s echo "  forge-system-trigger-view-test  Run anchored least-privilege system-trigger view contracts"
	@timeout 10s echo "  forge-active-reblit-boot-schema-input-test  Run sealed state-schema binding contracts"
	@timeout 10s echo "  forge-active-reblit-local-boot-policy-test  Run descriptor-retained local cmdline policy contracts"
	@timeout 10s echo "  forge-active-reblit-package-cmdline-input-test  Run sealed package cmdline semantic-input contracts"
	@timeout 10s echo "  forge-active-reblit-boot-topology-intent-test  Run machine-local Gluon partition-intent contracts"
	@timeout 10s echo "  forge-active-reblit-root-filesystem-intent-test  Run machine-local Gluon root-locator contracts"
	@timeout 10s echo "  forge-active-reblit-boot-render-input-test  Run pure exact-owner boot semantic-input contracts"
	@timeout 10s echo "  forge-active-reblit-bls-renderer-test  Run pure lifetime-bound BLS rendering contracts"
	@timeout 10s echo "  forge-active-reblit-desired-publication-test  Run bounded canonical desired boot-publication contracts"
	@echo "  forge-active-reblit-boot-publication-receipt-test  Run complete authority-free boot receipt contracts"
	@echo "  forge-active-reblit-boot-publication-preflight-test  Run retained read-only BOOT publication preflight contracts"
	@echo "  forge-active-reblit-boot-immutable-publication-attempt-test  Run staged immutable BOOT publication attempt contracts"
	@echo "  forge-active-reblit-boot-terminal-promotion-test  Run terminal BOOT evidence-to-receipt promotion contracts"
	@echo "  forge-active-reblit-boot-sync-completion-test  Run exact promoted receipt-to-BootSyncComplete contracts"
	@timeout 10s echo "  forge-candidate-pre-journal-durability-test  Run candidate durability, marker-link, and namespace tests"
	@timeout 10s echo "  forge-transition-journal-coordinator-test  Run the unwired durable journal coordinator through /usr exchange completion"
	@timeout 10s echo "  forge-transition-recovery-classifier-test  Run persisted-phase startup recovery direction tests"
	@timeout 10s echo "  forge-startup-reconciliation-test  Run read-only startup recovery assessment tests"
	@timeout 10s echo "  forge-startup-activation-namespace-test  Run authenticated startup activation-namespace inventory tests"
	@timeout 10s echo "  forge-startup-usr-rollback-decision-test  Run exact journal-only startup rollback-decision contracts"
	@timeout 10s echo "  forge-startup-usr-exchanged-root-abi-normalization-test  Run retained UsrExchanged root ABI convergence contracts"
	@timeout 10s echo "  forge-startup-usr-exchange-parent-durability-test  Run exact descriptor-bound parent-durability contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-resume-route-test  Run exact journal-only rollback-resume routing contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-candidate-preserve-admission-test  Run sealed read-only candidate-preservation admission contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-candidate-preserve-target-test  Run all candidate target preparation, creation, and normalization contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-candidate-preserve-effect-test  Run sealed NewState candidate-preservation move contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-active-reblit-preserve-effect-test  Run production ActiveReblit wrapper-exchange contracts"
	@timeout 10s echo "  forge-startup-active-reblit-candidate-preserve-post-exchange-durability-test  Run shared ActiveReblit POST durability contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-active-reblit-candidate-preserve-persistence-test  Run production ActiveReblit CandidatePreserved persistence contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-candidate-preserve-post-move-durability-test  Run shared NewState post-move durability contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-candidate-preserve-persistence-test  Run durable CandidatePreserved journal persistence contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-archived-candidate-preserve-foundation-test  Run test-sealed archived child-move foundation contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-activate-archived-candidate-dispatch-test  Run production ActivateArchived candidate-preservation contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-fresh-db-invalidation-route-test  Run journal-only fresh-database invalidation routing contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-fresh-db-invalidation-effect-test  Run sealed exact fresh-database invalidation effect contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-fresh-db-invalidation-persistence-test  Run durable FreshDbInvalidated journal persistence contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-complete-route-test  Run journal-only FreshDbInvalidated-to-RollbackComplete route contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-finalization-test  Run sealed terminal rollback journal-finalization contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-active-reblit-candidate-dispatch-test  Run one-entry real-startup ActiveReblit candidate-preservation contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-active-reblit-complete-route-test  Run real-startup ActiveReblit rollback-completion routing contracts"
	@timeout 10s echo "  forge-startup-active-reblit-boot-repair-required-test  Run exact ActiveReblit boot-rollback routing contracts"
	@timeout 10s echo "  forge-startup-active-reblit-boot-repair-unverified-test  Run zero-boot Started-to-Unverified retention contracts"
	@timeout 10s echo "  forge-startup-active-reblit-boot-repair-complete-test  Run journal-only Complete-to-RollbackComplete contracts"
	@timeout 10s echo "  forge-clean-boot-synchronization-test  Run standalone boot synchronization authority contracts"
	@timeout 10s echo "  forge-legacy-boot-repair-test  Run clean-authority legacy boot-repair contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-activate-archived-complete-route-test  Run production one-entry ActivateArchived rollback-completion contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-activate-archived-finalization-test  Run terminal ActivateArchived rollback-finalization contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-active-reblit-finalization-test  Run terminal ActiveReblit rollback-finalization contracts"
	@echo "  forge-startup-root-links-terminal-process-test  Run RootLinks terminal process-death contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-new-state-dispatch-test  Run the real-startup NewState rollback-suffix contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-admission-test  Run sealed read-only reverse-admission contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-projection-test  Run normalized reverse-exchange projection contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-effect-adapter-test  Run the one-shot reverse-exchange syscall adapter contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-reconciliation-test  Run fresh namespace reverse-exchange reconciliation contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-effect-test  Run sealed Apply/Finish reverse-effect contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-namespace-durability-test  Run retained reverse parent-durability contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-durability-test  Run sealed reverse durability-authority contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-persistence-test  Run exact UsrRestored persistence and reopen contracts"
	@timeout 10s echo "  forge-startup-usr-rollback-reverse-dispatch-test  Run one-phase real-startup reverse dispatch contracts"
	@echo "  forge-linux-fs-test  Run the exact retained Linux filesystem capability tests"
	@timeout 10s echo "  host-storage-safety-test  Audit local tests and harnesses for host-storage access"
	@echo "  disposable-vm-uefi-boot-storage-harness-test  Statically check the VM-only storage harness"
	@echo "  disposable-vm-uefi-boot-storage-challenge  Arm a fresh exact-guest challenge without disk mutation"
	@echo "  disposable-vm-uefi-boot-storage-admission  Recheck an armed challenge without disk mutation"
	@echo "  disposable-vm-uefi-boot-storage-campaign  DESTROY only the exact admitted disposable-VM disk"
	@echo "  disposable-vm-uefi-boot-gpt-topology-harness-test  Statically check the VM-only GPT boot harness"
	@echo "  disposable-vm-uefi-boot-gpt-topology-challenge  Arm the GPT topology VM challenge without disk mutation"
	@echo "  disposable-vm-uefi-boot-gpt-topology-admission  Recheck the GPT topology VM admission without mutation"
	@echo "  disposable-vm-uefi-boot-gpt-topology-campaign  REPARTITION only the exact admitted disposable-VM disk"
	@echo "  disposable-vm-uefi-boot-gpt-aggregate-harness-test  Statically check the receipt-bound aggregate GPT harness"
	@echo "  disposable-vm-uefi-boot-gpt-aggregate-challenge  Arm the aggregate GPT VM challenge without disk mutation"
	@echo "  disposable-vm-uefi-boot-gpt-aggregate-admission  Recheck the aggregate GPT VM admission without mutation"
	@echo "  disposable-vm-uefi-boot-gpt-aggregate-campaign  REPARTITION the exact admitted VM disk and test aggregate BOOT publication"
	@timeout 10s echo "  forge-linux-descriptor-boot-filesystem-test  Run pure descriptor-bound boot-filesystem authentication contracts"
	@echo "  forge-linux-descriptor-boot-publication-parent-test  Run retained nested boot publication-parent contracts"
	@timeout 10s echo "  forge-linux-descriptor-boot-namespace-test  Run pure bounded boot-destination namespace assessment contracts"
	@timeout 10s echo "  forge-linux-gpt-partition-role-test  Run pure bounded GPT partition-role parser contracts"
	@timeout 10s echo "  forge-linux-mount-attachment-test  Run exact synthetic mountinfo attachment-selection contracts"
	@timeout 10s echo "  forge-linux-mount-boot-policy-test  Run exact synthetic vfat boot mount-policy contracts"
	@timeout 10s echo "  forge-linux-mount-devtmpfs-policy-test  Run exact synthetic devtmpfs mount-policy contracts"
	@timeout 10s echo "  forge-linux-mountinfo-parser-test  Run the bounded byte-preserving Linux mountinfo parser contracts"
	@timeout 10s echo "  forge-linux-mount-namespace-test  Run retained synthetic namespace and task-root anchor contracts"
	@timeout 10s echo "  forge-linux-authenticated-mountinfo-snapshot-test  Run authenticated current-thread mountinfo snapshot contracts"
	@timeout 10s echo "  forge-linux-sysfs-block-parser-test  Run bounded kernel block-identity parser contracts"
	@timeout 10s echo "  forge-linux-sysfs-identity-test  Run descriptor-retained synthetic sysfs identity contracts"
	@echo "  forge-cache-test  Run the exact descriptor-rooted download and asset cache tests"
	@echo "  forge-client-direct-test  Run all direct frozen and state-transition client tests"
	@echo "  forge-cli-state-request-test  Run bounded canonical state-ID and removal-range contracts"
	@echo "  forge-database-adapter-test  Run extracted layout and metadata database adapter tests"
	@echo "  forge-boot-publication-receipt-head-test  Run strict receipt identity and database-head contracts"
	@echo "  forge-boot-publication-receipt-state-test  Run strict receipt-body database state contracts"
	@echo "  forge-boot-publication-receipt-promotion-test  Run exact atomic pending-to-committed receipt contracts"
	@echo "  forge-read-only-substrate-test  Run immutable database-image and clean-journal substrate tests"
	@timeout 10s echo "  forge-exact-fresh-transition-removal-test  Run exact fresh-state database removal contracts"
	@echo "  forge-read-only-client-test  Run public retained read-only query-client tests"
	@echo "  forge-transition-journal-contract-test  Run durable journal model, codec, and phase tests"
	@echo "  forge-transition-runtime-evidence-test  Run authenticated boot, namespace, and tree witness tests"
	@echo "  forge-transition-journal-successor-test  Run production journal successor-construction tests"
	@echo "  forge-transition-journal-bound-delete-test  Run exact consuming journal-inode deletion tests"
	@echo "  forge-transition-journal-delete-residue-recovery-test  Run exact interrupted bound-delete recovery tests"
	@echo "  forge-transition-journal-test  Run every direct transition-journal contract and storage test"
	@echo "  stone-read-test  Run the exact bounded Stone reader and content-stream tests"
	@echo "  stone-recipe-derivation-provenance-test  Run exact derivation provenance identity and validation tests"
	@echo "  stone-recipe-derivation-validation-test  Run all extracted derivation validation tests"
	@echo "  stone-recipe-build-lock-test  Run all extracted build-lock codec and validation tests"
	@echo "  stone-recipe-package-validation-test  Run package validation, limits, and package-v3 conversion tests"
	@echo "  stone-recipe-build-policy-validation-test  Run extracted policy validation and budget tests"
	@echo "  stone-recipe-build-policy-contract-test  Run repository policy ABI and validation tests"
	@echo "  stone-recipe-build-policy-patch-test  Run total policy-patch composition tests"
	@echo "  tools-buildinfo-semantic-fingerprint-test  Run semantic source-fingerprint tests"
	@echo "  container-cgroup-test  Run all extracted cgroup lifecycle and parser tests"
	@echo "  container-process-runtime-test  Run host-safe process-runtime, pidfd, and signal tests"
	@echo "  container-mount-boundary-test  Run anchored root and pseudo-filesystem mount tests"
	@echo "  container-private-device-test Run private minimal-device provider contract tests"
	@echo "  private-device-service-test  Check the hidden Cast broker entrypoint and systemd units"
	@echo "  container-root-host-safe-test  Run every direct container test except five sandbox-denied socket diagnostics"
	@echo "  mason-package-collect-test  Run bounded collection filesystem and inventory tests"
	@echo "  mason-package-collect-transaction-test  Run transactional mutation and publication tests"
	@echo "  mason-analysis-handler-test  Run all bounded analyzer input, sandbox, and process tests"
	@echo "  mason-emit-test  Run the exact transactional Stone emission verification tests"
	@echo "  mason-archive-test  Run all bounded authenticated archive extraction tests"
	@echo "  mason-draft-hardening-test  Run deterministic bounded recipe-drafting and cache tests"
	@echo "  mason-package-publication-test  Run all frozen package and bundle publication tests"
	@echo "  mason-git-materialization-test  Run all descriptor-rooted Git materialization tests"
	@echo "  mason-paths-test  Run all retained workspace path and execution-lock tests"
	@echo "  mason-executor-test  Run all frozen executor supervision and output-bound tests"
	@echo "  mason-build-context-test  Run all frozen build-context resolution tests"
	@echo "  mason-build-tuning-test  Run ordered compiler-tuning composition tests"
	@echo "  mason-recipe-explanation-test  Run recipe explanation determinism tests"
	@echo "  mason-upstream-git-cache-test  Run authenticated Git cache lifecycle tests"
	@echo "  mason-build-root-test  Run exact frozen-root input and binding tests"
	@echo "  mason-profile-test  Run typed Gluon profile loading and persistence tests"
	@echo "  mason-planner-bootstrap-test  Run pinned execution-closure planner tests"
	@echo "  mason-policy-test  Run rooted policy composition and provenance tests"
	@echo "  config-declaration-manager-test  Run language-neutral typed manager tests"
	@echo "  config-rooted-declaration-loader-test  Run descriptor-rooted typed declaration tests"
	@echo "  config-fixed-root-declaration-loader-test  Run fixed-slot typed declaration tests"
	@echo "  config-declaration-storage-test  Run language-neutral declaration slot and persistence tests"
	@echo "  config-declaration-store-test  Run all language-neutral declaration store tests"
	@echo "  gitwrap-repository-fs-test  Run repository filesystem identity, quota, and mirror tests"
	@timeout 10s echo "  gitwrap-fixture-bundle-test  Run the exact bounded offline Git bundle tests"
	@echo "  gitwrap-all-test  Run every direct Gitwrap runtime and repository test"
	@timeout 10s echo "  mason-upstream-git-fixture-import-test  Run fail-closed offline Git cache import tests"
	@timeout 10s echo "  mason-upstream-git-share-test  Run retained-root Git source publication tests"
	@echo "  forge-repository-manager-test  Run repository snapshot, publication, and validation tests"
	@echo "  forge-security-fixture-test  Run hardened intent, state-marker, and inode-kind fixtures"
	@echo "  forge-client-startup-gate-test  Run focused system-client startup recovery-evidence tests"
	@echo "  forge-active-state-snapshot-test  Run descriptor-rooted live active-state and stale-client tests"
	@echo "  forge-transition-identity-test  Run focused durable /usr identity and recovery tests"
	@echo "  forge-state-prune-test  Run exact retained archived-state prune and restart-residue tests"
	@timeout 10s echo "  forge-active-reblit-boot-state-root-test  Run authenticated live/archive boot-state root contracts"
	@echo "  forge-archived-repair-test  Run retained whole-wrapper inactive-state repair tests"
	@echo "  forge-ephemeral-candidate-metadata-test  Run retained external candidate and trigger tests"
	@echo "  forge-fixed-staging-test  Run retained fixed-staging and external-target security tests"
	@echo "  forge-previous-tree-move-test  Run retained previous-tree archive and restore tests"
	@echo "  forge-archived-candidate-move-test  Run retained archived-candidate move and recovery tests"
	@echo "  examples      Check, evaluate, freeze, and fail-close the Gluon examples"
	@echo "  cast-example-process-supervision-test  Prove bounded Cast example child cleanup"
	@echo "  examples-gate-test  Test example discovery and failure propagation"
	@echo "  execution-fixtures  Verify real offline source archives and Gluon locks"
	@echo "  execution-capability-preflight-test  Test optional/required preflight policy and classification"
	@echo "  fixture-proof-test  Test fixture proof production and exact validation"
	@echo "  fixture-proof-validator-test  Test exact fixture CI proof v2 validation"
	@echo "  mason-fixture-proof-evidence-test  Test Mason fixture proof production"
	@echo "  mason-fixture-proof-cross-boundary-test  Validate Rust proof bytes through the exact shell contract"
	@echo "  delegated-execution-preflight  Check production execution capability before bootstrap download"
	@echo "  delegated-execution-fixtures  Run selected contentful fixtures in a harness-free delegated unit"
	@echo "  delegated-fixture-runner-test  Test delegated-unit cleanup and bounded CI evidence"
	@echo "  bootstrap-fixtures  Prepare the pinned closure, then run the offline fixture lane"
	@echo "  bootstrap-fixtures-prepare  Fetch and verify the pinned 179-package Stone closure"
	@echo "  bootstrap-fixtures-offline  Build selected fixtures twice without downloading"
	@echo "                    Set FIXTURE=all (default) or one of the twenty-eight fixture names"
	@echo "                    Set REQUIRE_EXECUTION=1 to reject namespace-capability skips"
	@echo "  fixtures-ci    Required-capability twenty-eight-fixture execution and reproduction gate"
	@echo "  fixture-sources  Rebuild deterministic offline execution-source archives"
	@echo "  multiple-sources-contract-test  Test the exact mixed-source declaration, lock, and tamper boundary"
	@echo "  multiple-sources-supplemental-compiler-test  Compile the mixed-source golden with GCC and Clang (supplemental only)"
	@echo "  external-test-vectors-contract-test  Test the exact independently locked source/corpus contract"
	@echo "  external-test-vectors-supplemental-host-test  Run disposable CMake/CTest corpus checks (supplemental only)"
	@echo "  gettext-localization-contract-test  Test exact catalog sources, build-only consumer, output routing, and tamper rejection"
	@echo "  gettext-localization-supplemental-host-test  Compile and execute both catalog translations with host tools (supplemental only)"
	@echo "  go-module-contract-test  Test the exact offline Go declaration, vendor tree, lock, and tamper boundary"
	@echo "  go-module-supplemental-host-test  Rebuild the vendored Go module twice under a hostile offline host environment"
	@echo "  python-module-contract-test  Test the exact offline PEP 517 declaration, source tree, lock, and tamper boundary"
	@echo "  python-module-supplemental-host-test  Rebuild the Python wheel twice under a hostile offline host environment"
	@echo "  desktop-integration-contract-test  Test exact desktop assets, relations, staged validation topology, and tamper rejection"
	@echo "  desktop-integration-supplemental-host-test  Recheck staged desktop assets with host validators (supplemental only)"
	@echo "  font-family-contract-test  Test exact authored fonts, provenance, recipe, lock, and tamper boundaries"
	@echo "  font-family-supplemental-host-test  Recheck TTF metadata and cache isolation with host fontconfig (supplemental only)"
	@echo "  system-integration-assets-contract-test  Test exact system assets, relations, syntax topology, and tamper rejection"
	@echo "  system-integration-assets-supplemental-host-test  Recheck staged assets with host validators (supplemental only)"
	@echo "  check         Check all workspace targets"
	@echo "  fix           Apply clippy, formatting, and typo fixes"
	@echo "  fmt           Format the workspace"
	@echo "  binary-layout  Require Cast to be the sole executable target"
	@echo "  product-names  Reject active references to retired product names"
	@echo "  config-formats  Reject YAML/KDL outside external-service interfaces"
	@echo "  config-formats-test  Test the configuration-format gate"
	@echo "  source-loc    Enforce the 1000-line limit on tracked repo-owned text"
	@echo "  source-loc-test  Test tracked-path classification and LOC boundaries"
	@echo "  migrate       Apply all Forge database migrations"
	@echo "  migrate-redo  Reapply all Forge database migrations"
	@echo "  libstone      Build and run the C libstone example"
	@echo "  clean         Remove Cargo build artifacts"
	@echo
