.PHONY: config-rooted-gluon-test forge-client-startup-gate-test forge-active-state-snapshot-test forge-transition-identity-test forge-state-prune-test forge-active-reblit-wrapper-test forge-archived-repair-test forge-stateful-candidate-metadata-test forge-ephemeral-candidate-metadata-test forge-fixed-staging-test forge-previous-tree-move-test forge-archived-candidate-move-test forge-frozen-normalization-test forge-frozen-publication-test forge-frozen-discard-test cache-clean-test cast-example-process-supervision-test examples examples-gate-test execution-fixtures execution-capability-preflight-test delegated-execution-preflight delegated-execution-fixtures delegated-fixture-runner-test bootstrap-fixtures bootstrap-fixtures-prepare bootstrap-fixtures-offline bootstrap-fixtures-tmp bootstrap-fixture-selection bootstrap-execution-requirement fixtures-ci fixture-sources fixture-sources-check

include misc/make/hardening-tests.mk
include misc/make/boot-publication-receipt-head-tests.mk
include misc/make/boot-publication-receipt-state-tests.mk misc/make/boot-publication-receipt-promotion-tests.mk misc/make/boot-publication-installed-receipt-tests.mk misc/make/boot-publication-promoted-receipt-chain-tests.mk
include misc/make/transition-journal-bound-delete-tests.mk
include misc/make/transition-journal-delete-residue-recovery-tests.mk
include misc/make/private-device-tests.mk
include misc/make/private-device-service-tests.mk
include misc/make/host-storage-safety-tests.mk
include misc/make/disposable-vm-uefi-boot-storage-campaign.mk
include misc/make/linux-descriptor-boot-filesystem-tests.mk
include misc/make/linux-descriptor-boot-file-publication-tests.mk misc/make/linux-descriptor-boot-file-replacement-tests.mk misc/make/linux-descriptor-boot-leaf-assessment-tests.mk
include misc/make/linux-descriptor-boot-publication-parent-tests.mk
include misc/make/disposable-vm-uefi-boot-gpt-topology-campaign.mk misc/make/disposable-vm-uefi-boot-gpt-aggregate-campaign.mk
include misc/make/linux-descriptor-boot-namespace-tests.mk
include misc/make/linux-descriptor-boot-namespace-production-tests.mk
include misc/make/linux-descriptor-devtmpfs-filesystem-tests.mk
include misc/make/linux-gpt-partition-role-tests.mk
include misc/make/linux-gpt-partition-device-tests.mk
include misc/make/linux-mount-attachment-tests.mk
include misc/make/linux-mount-boot-policy-tests.mk
include misc/make/linux-mount-devtmpfs-policy-tests.mk
include misc/make/linux-mountinfo-parser-tests.mk
include misc/make/linux-mount-namespace-tests.mk
include misc/make/linux-authenticated-mountinfo-snapshot-tests.mk
include misc/make/linux-sysfs-block-parser-tests.mk
include misc/make/linux-sysfs-identity-tests.mk
include misc/make/draft-hardening-tests.mk
include misc/make/state-request-tests.mk
include misc/make/exact-fresh-transition-removal-tests.mk
include misc/make/transition-coordinator-tests.mk
include misc/make/transition-root-abi-publication-tests.mk
include misc/make/activation-namespace-tests.mk
include misc/make/startup-gate-tests.mk
include misc/make/mutable-system-capabilities-tests.mk
include misc/make/system-trigger-view-tests.mk
include misc/make/boot-synchronization-authority-tests.mk
include misc/make/active-reblit-boot-state-root-tests.mk
include misc/make/active-reblit-boot-schema-input-tests.mk
include misc/make/active-reblit-local-boot-policy-tests.mk
include misc/make/active-reblit-package-cmdline-input-tests.mk
include misc/make/active-reblit-boot-topology-intent-tests.mk
include misc/make/active-reblit-root-filesystem-intent-tests.mk
include misc/make/active-reblit-boot-render-input-tests.mk
include misc/make/active-reblit-bls-renderer-tests.mk
include misc/make/active-reblit-desired-publication-tests.mk
include misc/make/active-reblit-boot-publication-receipt-tests.mk
include misc/make/active-reblit-boot-namespace-input-tests.mk misc/make/active-reblit-boot-publication-preflight-tests.mk misc/make/active-reblit-boot-immutable-publication-attempt-tests.mk misc/make/active-reblit-boot-terminal-promotion-tests.mk misc/make/active-reblit-boot-sync-completion-tests.mk misc/make/active-reblit-boot-complete-finalization-tests.mk misc/make/active-reblit-installed-boot-publication-delta-tests.mk misc/make/active-reblit-boot-owned-replacement-bridge-tests.mk
include misc/make/startup-recovery-tests.mk
include misc/make/startup-root-abi-normalization-tests.mk
include misc/make/startup-exchange-durability-tests.mk
include misc/make/startup-rollback-resume-route-tests.mk
include misc/make/startup-candidate-preserve-admission-tests.mk
include misc/make/startup-candidate-preserve-target-tests.mk
include misc/make/startup-candidate-preserve-effect-tests.mk
include misc/make/startup-active-reblit-candidate-preserve-effect-tests.mk
include misc/make/startup-active-reblit-candidate-preserve-post-exchange-durability-tests.mk
include misc/make/startup-active-reblit-candidate-preserve-persistence-tests.mk
include misc/make/startup-candidate-preserve-post-move-durability-tests.mk
include misc/make/startup-candidate-preserve-persistence-tests.mk
include misc/make/startup-rollback-archived-candidate-preserve-foundation-tests.mk
include misc/make/startup-rollback-activate-archived-candidate-dispatch-tests.mk
include misc/make/startup-fresh-db-invalidation-route-tests.mk
include misc/make/startup-fresh-db-invalidation-effect-tests.mk
include misc/make/startup-fresh-db-invalidation-persistence-tests.mk
include misc/make/startup-rollback-complete-route-tests.mk
include misc/make/startup-rollback-finalization-tests.mk
include misc/make/startup-rollback-active-reblit-candidate-dispatch-tests.mk
include misc/make/startup-rollback-active-reblit-complete-route-tests.mk
include misc/make/startup-active-reblit-boot-repair-required-tests.mk
include misc/make/startup-active-reblit-boot-repair-unverified-tests.mk
include misc/make/startup-active-reblit-boot-repair-complete-tests.mk misc/make/startup-active-reblit-boot-sync-complete-tests.mk misc/make/startup-active-reblit-commit-cleanup-authority-tests.mk misc/make/startup-active-reblit-commit-cleanup-effect-tests.mk misc/make/startup-active-reblit-commit-cleanup-dispatch-tests.mk misc/make/startup-active-reblit-commit-cleanup-complete-tests.mk misc/make/startup-active-reblit-complete-finalization-tests.mk
include misc/make/startup-rollback-activate-archived-complete-route-tests.mk
include misc/make/startup-rollback-activate-archived-finalization-tests.mk
include misc/make/startup-rollback-active-reblit-finalization-tests.mk
include misc/make/startup-root-links-terminal-process-tests.mk
include misc/make/startup-rollback-new-state-dispatch-tests.mk
include misc/make/startup-rollback-reverse-admission-tests.mk
include misc/make/startup-rollback-reverse-projection-tests.mk
include misc/make/startup-rollback-reverse-effect-adapter-tests.mk
include misc/make/startup-rollback-reverse-reconciliation-tests.mk
include misc/make/startup-rollback-reverse-effect-tests.mk
include misc/make/startup-rollback-reverse-namespace-durability-tests.mk
include misc/make/startup-rollback-reverse-durability-tests.mk
include misc/make/startup-rollback-reverse-persistence-tests.mk
include misc/make/startup-rollback-reverse-dispatch-tests.mk
include misc/make/userspace-profile-fixture.mk
include misc/make/fixture-proof-tests.mk
include misc/make/git-source-hardening-tests.mk
include misc/make/mason-generated-routing-tests.mk
include misc/make/mason-elf-debug-route-tests.mk
include misc/make/multiple-sources-fixture-tests.mk
include misc/make/gettext-localization-fixture-tests.mk
include misc/make/go-module-fixture-tests.mk
include misc/make/python-module-fixture-tests.mk
include misc/make/pgo-workload-fixture-tests.mk
include misc/make/relation-policy-fixture-tests.mk
include misc/make/desktop-integration-fixture-tests.mk
include misc/make/font-family-fixture-tests.mk
include misc/make/system-integration-assets-fixture-tests.mk
include misc/make/external-test-vectors-fixture-tests.mk
