use std::collections::TryReserveError;

use thiserror::Error;

use super::super::active_reblit_bls_renderer::ActiveReblitBlsRendererError;

#[derive(Debug, Error)]
pub(in crate::client) enum ActiveReblitBootNamespaceInputError {
    #[error("boot namespace input binding exceeded the retained deadline at {checkpoint}")]
    DeadlineExceeded { checkpoint: &'static str },
    #[error("boot publication collision domains no longer match the retained topology view")]
    CollisionDomainDrift,
    #[error("boot namespace input plan is empty")]
    EmptyPublicationPlan,
    #[error("boot namespace input destination domain {domain} is empty")]
    EmptyDestinationDomain { domain: &'static str },
    #[error("boot namespace input publication count {actual} exceeds limit {limit}")]
    PublicationCountLimit { limit: usize, actual: usize },
    #[error("boot namespace input path bytes {actual} exceed limit {limit}")]
    PathByteLimit { limit: usize, actual: usize },
    #[error("boot namespace input logical bytes {actual} exceed limit {limit}")]
    LogicalByteLimit { limit: u64, actual: u64 },
    #[error("generated boot publication {plan_index} has {actual} bytes, exceeding limit {limit}")]
    GeneratedFileByteLimit {
        plan_index: usize,
        limit: usize,
        actual: usize,
    },
    #[error("generated boot publication bytes {actual} exceed limit {limit}")]
    GeneratedTotalByteLimit { limit: usize, actual: usize },
    #[error("boot namespace input binding work {actual} exceeds limit {limit}")]
    WorkLimit { limit: usize, actual: usize },
    #[error("planned boot publication {plan_index} has a non-UTF-8 path")]
    NonUtf8PlanPath { plan_index: usize },
    #[error("generated boot publication {plan_index} has inconsistent scalar length")]
    GeneratedSourceLengthMismatch { plan_index: usize },
    #[error("sealed boot publication {plan_index} is absent from the retained renderer catalog")]
    MissingSealedSource { plan_index: usize },
    #[error("sealed boot publication {plan_index} does not match its retained asset identity")]
    SealedSourceIdentityMismatch { plan_index: usize },
    #[error("resolve retained sealed source for boot publication {plan_index}")]
    RetainedSourceCatalog {
        plan_index: usize,
        #[source]
        source: ActiveReblitBlsRendererError,
    },
    #[error("boot namespace input preflight and binding observations differed")]
    ImmutablePlanDrift,
    #[error("boot namespace input logical bytes differ from the prepared publication plan")]
    PreparedLogicalByteMismatch,
    #[error("boot namespace input publication count differs from the prepared publication plan")]
    PreparedPublicationCountMismatch,
    #[error("boot namespace input path bytes differ from the prepared publication plan")]
    PreparedPathByteMismatch,
    #[error("boot namespace input generated bytes differ from the prepared publication plan")]
    PreparedGeneratedByteMismatch,
    #[error("boot namespace input domain {domain} retained {actual} publications, expected {expected}")]
    DomainLengthMismatch {
        domain: &'static str,
        expected: usize,
        actual: usize,
    },
    #[error("allocate {resource} for boot namespace input domain {domain}")]
    Allocation {
        domain: &'static str,
        resource: &'static str,
        #[source]
        source: TryReserveError,
    },
}
