-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "generated-packet-library",
        version = "1.0.0",
        release = 1,
        homepage = "https://example.invalid/generated-packet-library",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "mkdir"
            },
            {
                kind = "binary",
                value = "cc"
            },
            {
                kind = "binary",
                value = "bash"
            },
            {
                kind = "binary",
                value = "install"
            },
            {
                kind = "binary",
                value = "ln"
            },
            {
                kind = "binary",
                value = "test"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/mkdir",
                            requirement = {
                                kind = "binary",
                                value = "mkdir"
                            }
                        },
                        args = {
                            "-p",
                            "build"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/libexec/packet-schema/packet-codegen",
                            requirement = {
                                kind = "output",
                                value = {
                                    package = {
                                        name = "packet-schema-tools"
                                    },
                                    output = "compiler"
                                }
                            }
                        },
                        args = {
                            "--input",
                            "source/schema/packet.idl",
                            "--header",
                            "build/packet-generated.h",
                            "--source",
                            "build/packet-generated.c"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-fPIC",
                            "-O2",
                            "-c",
                            "build/packet-generated.c",
                            "-o",
                            "build/packet-generated.o"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-shared",
                            "-Wl,-soname,libpacket-generated.so.1",
                            "build/packet-generated.o",
                            "-lpacket-runtime",
                            "-o",
                            "build/libpacket-generated.so.1.0.0"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            },
                            {
                                path = "/usr/bin/ln",
                                requirement = {
                                    kind = "binary",
                                    value = "ln"
                                }
                            }
                        },
                        script = "\ninstall -Dm755 build/libpacket-generated.so.1.0.0 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libpacket-generated.so.1.0.0\"\nln -s libpacket-generated.so.1.0.0 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libpacket-generated.so.1\"\nln -s libpacket-generated.so.1 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libpacket-generated.so\"\ninstall -Dm644 build/packet-generated.h \"${CAST_INSTALL_ROOT}${CAST_PREFIX}/include/packet-generated.h\"\n"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/test",
                            requirement = {
                                kind = "binary",
                                value = "test"
                            }
                        },
                        args = {
                            "-s",
                            "build/packet-generated.h"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "output",
            value = {
                package = {
                    name = "packet-schema-tools"
                },
                output = "compiler"
            }
        }
    },
    build_inputs = {
        {
            kind = "pkg_config",
            value = "packet-runtime"
        }
    },
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Generated packet target library"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "soname",
                    value = "libpacket-runtime.so.1"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/libpacket-generated.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Generated packet development interface"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "generated-packet-library"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include/packet-generated.h"
                },
                {
                    kind = "symlink",
                    path = "/usr/lib/libpacket-generated.so"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/generated-packet-library-1.0.0.tar.xz",
            hash = "7777777777777777777777777777777777777777777777777777777777777777",
            rename = {
                kind = "some",
                value = "generated-packet-library.tar.xz"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "source"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}