-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "net-audit",
        version = "3.1.0",
        release = 1,
        homepage = "https://example.invalid/net-audit",
        license = {
            "ISC"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "bash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "install -Dm755 \"${CAST_SOURCE_DIR}/net-audit\" \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/net-audit\""
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/sh",
                            requirement = {
                                kind = "binary",
                                value = "sh"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/bash",
                                requirement = {
                                    kind = "binary",
                                    value = "bash"
                                }
                            }
                        },
                        script = "bash -n \"${CAST_SOURCE_DIR}/net-audit\""
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Small network-audit command"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "binary",
                    value = "bash"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/net-audit"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/releases/net-audit-3.1.0",
            hash = "789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456",
            rename = {
                kind = "some",
                value = "net-audit"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = false,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}