-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-autotools-fixture-1.0.0.tar",
            sha256 = "cc72bc585ef513808277602603a6d883d0d9b8722a84e43fe65090035accf394"
        },
    },
}