    use declarative_config::{DeclarationCodec, EngineId, LanguageId};
    use stone_recipe::package::{BuilderSpec, HooksSpec, ProfileSpec, encode_lua_recipe};

    use super::*;

    const SOURCE_SPEC: &str = r#"{
    pname = "example",
    version = "1.2.3",
    release = 1,
    homepage = "https://example.com",
    license = ["MPL-2.0"],
}"#;

    const ARCHIVE_URL: &str = "https://example.com/source.tar.xz";
    const ARCHIVE_HASH: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const GIT_URL: &str = "https://example.com/source.git";
    const GIT_REF: &str = "main";
    const FULL_COMMIT: &str = "0123456789abcdef0123456789abcdef01234567";
    const MATERIALIZATION_SHA256: &str = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

    fn canonical_source_lock(lock: &SourceLock) -> String {
        GluonSourceLockCodec::default().encode(lock).unwrap()
    }

    fn gluon_recipe(source: &str) -> String {
        format!(
            "let a = import! cast.authored.v1\n{{\n    \
             meta = {source},\n    \
             builder = a.builder.custom a.empty.builder,\n    \
             sources = [],\n    \
             native_build_inputs = [],\n    \
             build_inputs = [],\n    \
             check_inputs = [],\n    \
             outputs = a.outputs.default,\n    \
             options = a.unset,\n    \
             profiles = [],\n    \
             architectures = [],\n    \
             tuning = [],\n    \
             emul32 = a.false,\n    \
             mold = a.false,\n    \
             hooks = a.unset,\n}}"
        )
    }

    fn synthetic_language(name: &str, extension: &str) -> LanguageSpec {
        LanguageSpec::new(
            LanguageId::new(name).unwrap(),
            EngineId::new(format!("{name}-engine"), "1").unwrap(),
            extension,
            "declaration-v1",
            format!("# generated by {name}\n"),
        )
        .unwrap()
    }

    fn minimal_recipe() -> Recipe {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe(SOURCE_SPEC)).unwrap();
        Recipe::load(root.path()).unwrap()
    }

    fn find_stone_glu(dir: &Path, found: &mut Vec<PathBuf>) {
        for entry in fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                find_stone_glu(&path, found);
            } else if path.file_name().and_then(|name| name.to_str()) == Some("stone.glu") {
                found.push(path);
            }
        }
    }

    #[test]
    fn every_gluon_recipe_example_round_trips_through_lua() {
        // Pair the authored `stone.glu` documentation corpus with generated Lua
        // by emitting each loaded recipe and re-loading it through the `.lua`
        // path; every example must normalize to the same package value.
        let examples =
            Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/examples/gluon"));
        let mut recipes = Vec::new();
        find_stone_glu(examples, &mut recipes);
        assert!(!recipes.is_empty(), "the Gluon recipe corpus is non-empty");

        for recipe_path in recipes {
            let directory = recipe_path.parent().unwrap();
            let gluon = Recipe::load_authored(directory)
                .unwrap_or_else(|error| panic!("load {recipe_path:?}: {error}"));
            let emitted = encode_lua_recipe(&gluon.declaration);

            let temporary = tempfile::tempdir().unwrap();
            fs::write(temporary.path().join("stone.lua"), &emitted).unwrap();
            let lua = Recipe::load_authored(temporary.path())
                .unwrap_or_else(|error| panic!("reload emitted {recipe_path:?}: {error}"));

            assert_eq!(lua.declaration, gluon.declaration, "recipe {recipe_path:?}");
        }
    }

    fn recipe_from(source: &str) -> Recipe {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe(source)).unwrap();
        Recipe::load(root.path()).unwrap()
    }

    /// One-shot corpus converter: generate the Lua mirror of every `packages/`
    /// recipe example, verifying each round-trips before writing. Run explicitly
    /// with `cargo test -p mason generate_lua_recipe_example_mirror -- --ignored`.
    #[test]
    #[ignore = "one-shot corpus conversion tool"]
    fn generate_lua_recipe_example_mirror() {
        let gluon_root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/examples/gluon/packages");
        let lua_root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/examples/lua/packages");

        let mut recipes = Vec::new();
        find_stone_glu(&gluon_root, &mut recipes);
        assert!(!recipes.is_empty(), "recipe corpus is non-empty");

        for stone_glu in &recipes {
            let dir = stone_glu.parent().unwrap();
            let gluon = Recipe::load_authored(dir)
                .unwrap_or_else(|error| panic!("load {stone_glu:?}: {error}"));
            let lua = encode_lua_recipe(&gluon.declaration);

            // Verify the emitted Lua re-decodes to the same package value.
            let scratch = tempfile::tempdir().unwrap();
            fs::write(scratch.path().join("stone.lua"), &lua).unwrap();
            let reloaded = Recipe::load_authored(scratch.path())
                .unwrap_or_else(|error| panic!("reload emitted {stone_glu:?}: {error}"));
            assert_eq!(reloaded.declaration, gluon.declaration, "round-trip {stone_glu:?}");

            let relative = dir.strip_prefix(&gluon_root).unwrap();
            let destination = lua_root.join(relative);
            fs::create_dir_all(&destination).unwrap();
            fs::write(destination.join("stone.lua"), &lua).unwrap();
        }
        eprintln!("converted {} recipe examples to Lua", recipes.len());
    }

    /// One-shot: convert the complete top-level recipe examples (the canonical
    /// `stone` and the layered `composed-stone`) to verified Lua. The remaining
    /// top-level files are other domain ABIs (repository, trigger, system,
    /// boot topology), not package recipes, and are handled as doc prose
    /// rather than mechanically converted.
    #[test]
    #[ignore = "one-shot corpus conversion tool"]
    fn generate_top_level_lua_recipe_examples() {
        let gluon_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/examples/gluon");
        let lua_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/examples/lua");

        for name in ["stone", "composed-stone"] {
            let source = gluon_dir.join(format!("{name}.glu"));
            let gluon = Recipe::load_authored(&source)
                .unwrap_or_else(|error| panic!("load {source:?}: {error}"));
            let lua = encode_lua_recipe(&gluon.declaration);

            let scratch = tempfile::tempdir().unwrap();
            fs::write(scratch.path().join("stone.lua"), &lua).unwrap();
            let reloaded = Recipe::load_authored(scratch.path())
                .unwrap_or_else(|error| panic!("reload emitted {name}: {error}"));
            assert_eq!(reloaded.declaration, gluon.declaration, "round-trip {name}");

            fs::write(lua_dir.join(format!("{name}.lua")), &lua).unwrap();
        }
    }

    #[test]
    fn a_recipe_authorizes_only_an_equivalent_replacement() {
        let authored = recipe_from(SOURCE_SPEC);
        let equivalent = recipe_from(SOURCE_SPEC);
        assert_eq!(
            authored.authorize_lua_replacement(&equivalent),
            RecipeMigrationDecision::Authorized
        );

        let divergent = recipe_from(&SOURCE_SPEC.replace("example", "renamed"));
        assert_eq!(
            authored.authorize_lua_replacement(&divergent),
            RecipeMigrationDecision::Rejected
        );
    }

    /// Author an equivalent-or-divergent Lua replacement in a separate
    /// directory (it cannot co-locate with the Gluon original) and return its
    /// `stone.lua` path.
    fn lua_replacement(declaration: &PackageSpec) -> (tempfile::TempDir, PathBuf) {
        let candidate = tempfile::tempdir().unwrap();
        let path = candidate.path().join("stone.lua");
        fs::write(&path, encode_lua_recipe(declaration)).unwrap();
        (candidate, path)
    }

    #[test]
    fn an_authorized_recipe_migration_switches_the_source_authority() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("stone.glu"), gluon_recipe(SOURCE_SPEC)).unwrap();
        let authored = Recipe::load_authored(dir.path().join("stone.glu")).unwrap();

        // The operator authors an equivalent Lua replacement elsewhere.
        let (_candidate, replacement) = lua_replacement(&authored.declaration);

        let outcome = migrate_recipe_to_lua(dir.path(), &replacement).unwrap();
        assert_eq!(outcome, RecipeMigration::Migrated);

        // The authored Gluon authority is gone; the Lua one is now sole and
        // discovery resolves it unambiguously.
        assert!(!dir.path().join("stone.glu").exists());
        assert!(dir.path().join("stone.lua").exists());
        assert!(resolve_path(dir.path()).unwrap().ends_with("stone.lua"));

        let migrated = Recipe::load_authored(dir.path()).unwrap();
        assert_eq!(migrated.declaration, authored.declaration);
    }

    #[test]
    fn a_rejected_recipe_migration_leaves_the_recipe_untouched() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("stone.glu"), gluon_recipe(SOURCE_SPEC)).unwrap();

        // A valid but non-equivalent Lua recipe (a different package name).
        let divergent = recipe_from(&SOURCE_SPEC.replace("example", "renamed"));
        let (_candidate, replacement) = lua_replacement(&divergent.declaration);

        let outcome = migrate_recipe_to_lua(dir.path(), &replacement).unwrap();
        assert_eq!(outcome, RecipeMigration::Rejected);

        // Fail-closed: the Gluon authority stays and no Lua file was installed.
        assert!(dir.path().join("stone.glu").exists());
        assert!(!dir.path().join("stone.lua").exists());
    }

    #[test]
    fn a_stone_lua_recipe_is_discovered_by_extension() {
        // The recipe loader now registers both languages; a directory holding a
        // `stone.lua` resolves to it (the `.lua` recipe dispatch), while an
        // unregistered extension is not discovered.
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.lua"), "return {}\n").unwrap();
        let resolved = resolve_path(root.path()).unwrap();
        assert!(resolved.ends_with("stone.lua"));

        let unknown = tempfile::tempdir().unwrap();
        fs::write(unknown.path().join("stone.toml"), "").unwrap();
        assert!(matches!(resolve_path(unknown.path()), Err(Error::MissingRecipe(_))));
    }

    fn target(name: &str) -> TargetPolicySpec {
        crate::BuildPolicy::repository_for_tests().target(name).unwrap().clone()
    }

    fn profile(name: &str) -> ProfileSpec {
        ProfileSpec {
            name: name.to_owned(),
            builder: BuilderSpec::default(),
            hooks: HooksSpec::default(),
            native_build_inputs: Vec::new(),
            build_inputs: Vec::new(),
            check_inputs: Vec::new(),
        }
    }

    fn gluon_recipe_with_upstreams() -> String {
        format!(
            r#"let a = import! cast.authored.v1
{{
    meta = {SOURCE_SPEC},
    builder = a.builder.custom a.empty.builder,
    sources = [
        a.source.archive "{ARCHIVE_URL}" "{ARCHIVE_HASH}",
        a.source.git "{GIT_URL}" "{GIT_REF}",
    ],
    native_build_inputs = [],
    build_inputs = [],
    check_inputs = [],
    outputs = a.outputs.default,
    options = a.unset,
    profiles = [],
    architectures = [],
    tuning = [],
    emul32 = a.false,
    mold = a.false,
    hooks = a.unset,
}}"#
        )
    }

    #[test]
    fn documented_recipe_examples_remain_loadable() {
        let examples = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/examples/gluon");

        let minimal = Recipe::load(examples.join("stone.glu")).unwrap();
        assert_eq!(minimal.declaration.meta.pname, "hello");

        let composed = Recipe::load(examples.join("composed-stone.glu")).unwrap();
        assert_eq!(composed.declaration.meta.pname, "composed-hello");
        assert_eq!(
            composed.declaration.outputs[0].summary.as_deref(),
            Some("Recipe composed with an imported policy")
        );
    }

    #[test]
    fn empty_architecture_list_supports_all_native_policy_targets_and_gates_emul32() {
        let mut recipe = minimal_recipe();
        let x86_64 = target("x86_64");
        let x86_64_v3x = target("x86_64-v3x");
        let emul32 = target("emul32/x86_64");

        assert!(recipe.supports_target(&x86_64));
        assert!(recipe.supports_target(&x86_64_v3x));
        assert!(!recipe.supports_target(&emul32));

        recipe.declaration.emul32 = true;
        assert!(recipe.supports_target(&emul32));
    }

    #[test]
    fn declared_architectures_match_exact_policy_names_or_typed_classes_only() {
        let mut recipe = minimal_recipe();
        let x86_64 = target("x86_64");
        let x86_64_v3x = target("x86_64-v3x");
        let emul32 = target("emul32/x86_64");

        recipe.declaration.architectures = vec!["x86_64".to_owned()];
        assert!(recipe.supports_target(&x86_64));
        assert!(!recipe.supports_target(&x86_64_v3x));
        assert!(!recipe.supports_target(&emul32));

        recipe.declaration.architectures = vec!["native".to_owned()];
        assert!(recipe.supports_target(&x86_64));
        assert!(recipe.supports_target(&x86_64_v3x));
        assert!(!recipe.supports_target(&emul32));

        recipe.declaration.architectures = vec!["emul32".to_owned()];
        assert!(!recipe.supports_target(&x86_64));
        assert!(recipe.supports_target(&emul32));

        recipe.declaration.architectures = vec!["emul32/x86_64".to_owned()];
        assert!(recipe.supports_target(&emul32));
    }

    #[test]
    fn target_profiles_prefer_exact_policy_name_then_typed_emul32_fallback() {
        let mut recipe = minimal_recipe();
        let target = target("emul32/x86_64");
        recipe.declaration.profiles = vec![profile("emul32"), profile("emul32/x86_64")];

        assert_eq!(recipe.build_target_profile_key(&target), Some("emul32/x86_64"));
        assert_eq!(recipe.build_target_profile(&target).unwrap().name, "emul32/x86_64");

        recipe.declaration.profiles.pop();
        assert_eq!(recipe.build_target_profile_key(&target), Some("emul32"));
        assert_eq!(recipe.build_target_profile(&target).unwrap().name, "emul32");
    }

    fn matching_source_lock() -> SourceLock {
        SourceLock::new(vec![
            source_lock::SourceResolution::Archive(source_lock::ArchiveResolution {
                order: 0,
                url: ARCHIVE_URL.to_owned(),
                sha256: ARCHIVE_HASH.to_owned(),
            }),
            source_lock::SourceResolution::Git(source_lock::GitResolution {
                order: 1,
                url: GIT_URL.to_owned(),
                requested_ref: GIT_REF.to_owned(),
                commit: FULL_COMMIT.to_owned(),
                materialization_sha256: MATERIALIZATION_SHA256.to_owned(),
            }),
        ])
    }

    #[test]
    fn recipe_directory_resolves_registered_gluon_root() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.yaml"), "ignored").unwrap();

        let missing = resolve_path(root.path()).unwrap_err();
        assert!(matches!(missing, Error::MissingRecipe(path) if path.ends_with("stone.glu")));

        let gluon = root.path().join("stone.glu");
        fs::write(&gluon, "{}").unwrap();
        assert_eq!(resolve_path(root.path()).unwrap(), gluon.canonicalize().unwrap());
    }

    #[test]
    fn recipe_root_discovery_dispatches_registered_extensions_and_rejects_collisions() {
        let root = tempfile::tempdir().unwrap();
        let slot = RootDeclarationSlot::new(
            RECIPE_ROOT_BASENAME,
            RECIPE_ROOT_LOGICAL_NAME_V1,
        )
        .unwrap();
        let languages = RegisteredLanguages::new([
            synthetic_language("alpha", "alpha"),
            synthetic_language("beta", "beta"),
        ])
        .unwrap();
        let alpha = root.path().join("stone.alpha");
        fs::write(&alpha, "alpha").unwrap();

        assert_eq!(
            discover_recipe_root(root.path(), &slot, &languages).unwrap(),
            Some(alpha.clone())
        );

        let beta = root.path().join("stone.beta");
        fs::write(&beta, "beta").unwrap();
        let error = discover_recipe_root(root.path(), &slot, &languages).unwrap_err();
        let Error::DiscoverRecipeSlot { directory, source } = error else {
            panic!("unexpected error: {error}");
        };
        assert_eq!(directory, root.path());
        assert_eq!(source.collision_paths(), Some([alpha, beta].as_slice()));
    }

    #[cfg(unix)]
    #[test]
    fn recipe_root_discovery_rejects_a_symlinked_registered_candidate() {
        use std::os::unix::fs::symlink;

        let root = tempfile::tempdir().unwrap();
        let target = root.path().join("target.glu");
        let recipe = root.path().join(RECIPE_ROOT_LOGICAL_NAME_V1);
        fs::write(&target, gluon_recipe(SOURCE_SPEC)).unwrap();
        symlink(&target, &recipe).unwrap();

        let error = resolve_path(root.path()).unwrap_err();
        let Error::DiscoverRecipeSlot { directory, source } = error else {
            panic!("unexpected error: {error}");
        };
        assert_eq!(directory, root.path());
        assert!(matches!(
            source,
            RootDeclarationDiscoveryError::NotRegular { path } if path == recipe
        ));
    }

    #[test]
    fn explicit_gluon_file_loads_and_records_provenance() {
        let root = tempfile::tempdir().unwrap();
        let path = root.path().join("custom.glu");
        fs::write(&path, gluon_recipe(SOURCE_SPEC)).unwrap();

        let recipe = Recipe::load(&path).unwrap();

        assert_eq!(recipe.path, path.canonicalize().unwrap());
        assert_eq!(recipe.declaration.meta.pname, "example");
        assert!(recipe.source_lock.is_none());
        let fingerprint = recipe.fingerprint;
        assert_eq!(fingerprint.root_source_sha256.len(), 64);
        assert!(
            fingerprint
                .modules
                .iter()
                .any(|module| module.logical_name == "cast.authored.v1")
        );
    }

    #[test]
    fn explicit_unknown_extension_never_selects_a_sibling_gluon_recipe() {
        let root = tempfile::tempdir().unwrap();
        let gluon = root.path().join("custom.glu");
        let unknown = root.path().join("custom.yaml");
        fs::write(&gluon, gluon_recipe(SOURCE_SPEC)).unwrap();
        fs::write(&unknown, gluon_recipe(SOURCE_SPEC)).unwrap();

        let error = Recipe::load(&unknown).unwrap_err();

        assert!(matches!(error, Error::MissingRecipe(path) if path == unknown.canonicalize().unwrap()));
    }

    #[test]
    fn directory_gluon_loads_contained_relative_imports() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("source.glu"), SOURCE_SPEC).unwrap();
        fs::write(
            root.path().join("stone.glu"),
            r#"
let a = import! cast.authored.v1
let source = import! "source.glu"
{
    meta = source,
    builder = a.builder.custom a.empty.builder,
    sources = [],
    native_build_inputs = [],
    build_inputs = [],
    check_inputs = [],
    outputs = a.outputs.default,
    options = a.unset,
    profiles = [],
    architectures = [],
    tuning = [],
    emul32 = a.false,
    mold = a.false,
    hooks = a.unset,
}
"#,
        )
        .unwrap();

        let recipe = Recipe::load(root.path()).unwrap();
        let fingerprint = recipe.fingerprint;

        assert_eq!(recipe.path, root.path().join("stone.glu").canonicalize().unwrap());
        assert_eq!(recipe.declaration.meta.version, "1.2.3");
        assert_eq!(fingerprint.root_logical_name, RECIPE_ROOT_LOGICAL_NAME_V1);
        let mut modules = fingerprint
            .modules
            .iter()
            .map(|module| module.logical_name.as_str())
            .collect::<Vec<_>>();
        // v2 identity orders modules by canonical graph identity; assert
        // membership independent of that ordering.
        modules.sort_unstable();
        assert_eq!(
            modules,
            [
                "cast.authored.v1",
                "source.glu",
                "std.string.prim",
                "std.types",
            ]
        );
    }

    #[test]
    fn invalid_gluon_preserves_source_diagnostics() {
        let root = tempfile::tempdir().unwrap();
        fs::write(
            root.path().join("stone.glu"),
            r#"
let a = import! cast.authored.v1
{
    meta = {
        pname = "example",
        version = "1.2.3",
        release = 1,
        homepage = 42,
        license = ["MPL-2.0"],
    },
    builder = a.builder.custom a.empty.builder,
    sources = [],
    native_build_inputs = [],
    build_inputs = [],
    check_inputs = [],
    outputs = a.outputs.default,
    options = a.unset,
    profiles = [],
    architectures = [],
    tuning = [],
    emul32 = a.false,
    mold = a.false,
    hooks = a.unset,
}
"#,
        )
        .unwrap();

        let error = Recipe::load(root.path()).unwrap_err();
        let Error::EvaluateRecipe(DeclarationEvaluationError::Evaluation(diagnostic)) = error else {
            panic!("unexpected error: {error}");
        };

        assert_eq!(diagnostic.category, gluon_config::DiagnosticCategory::Type);
        assert_eq!(diagnostic.source_name.as_deref(), Some("stone.glu"));
        assert!(diagnostic.span.is_some());
    }

    #[test]
    fn legacy_recipe_shape_is_not_an_implicit_fallback() {
        let root = tempfile::tempdir().unwrap();
        fs::write(
            root.path().join("stone.glu"),
            format!("let source = {SOURCE_SPEC}\n{{ source }}"),
        )
        .unwrap();

        let error = Recipe::load(root.path()).unwrap_err();
        assert!(matches!(
            error,
            Error::EvaluateRecipe(DeclarationEvaluationError::Evaluation(_))
        ));
    }

    #[test]
    fn valid_source_lock_is_decoded_and_retained() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe_with_upstreams()).unwrap();
        fs::write(
            root.path().join(SOURCE_LOCK_FILE_NAME),
            canonical_source_lock(&matching_source_lock()),
        )
        .unwrap();

        let recipe = Recipe::load(root.path()).unwrap();

        assert_eq!(recipe.source_lock, Some(matching_source_lock()));
    }

    #[test]
    fn oversized_and_symlinked_source_locks_are_rejected_structurally() {
        use std::os::unix::fs::symlink;

        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe_with_upstreams()).unwrap();
        let lock_path = root.path().join(SOURCE_LOCK_FILE_NAME);
        let limit = Limits::default().max_source_bytes;
        fs::File::create(&lock_path)
            .unwrap()
            .set_len(u64::try_from(limit).unwrap() + 1)
            .unwrap();

        let error = Recipe::load(root.path()).unwrap_err();
        let Error::LoadSourceLock { source, .. } = error else {
            panic!("unexpected error: {error}");
        };
        assert!(matches!(
            *source,
            generated_lock::ReadError::TooLarge { limit: found, .. } if found == limit
        ));

        fs::remove_file(&lock_path).unwrap();
        let target = root.path().join("lock-target");
        fs::write(&target, canonical_source_lock(&matching_source_lock())).unwrap();
        symlink(&target, &lock_path).unwrap();

        let error = Recipe::load(root.path()).unwrap_err();
        let Error::LoadSourceLock { source, .. } = error else {
            panic!("unexpected error: {error}");
        };
        assert!(matches!(
            *source,
            generated_lock::ReadError::NotRegular {
                kind: generated_lock::FileKind::Symlink,
                ..
            }
        ));
    }

    #[test]
    fn malformed_schema_and_commit_lock_errors_include_the_lock_path() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe_with_upstreams()).unwrap();
        let lock_path = root.path().join(SOURCE_LOCK_FILE_NAME);

        let mut wrong_schema = matching_source_lock();
        wrong_schema.schema_version = 3;
        let mut short_commit = matching_source_lock();
        let source_lock::SourceResolution::Git(git) = &mut short_commit.sources[1] else {
            unreachable!();
        };
        git.commit = "abc123d".to_owned();

        let cases = [
            ("{".to_owned(), "Unexpected end of file"),
            (canonical_source_lock(&wrong_schema), "unsupported schema"),
            (
                canonical_source_lock(&short_commit),
                "exactly 40 lowercase hexadecimal",
            ),
        ];

        for (contents, expected) in cases {
            fs::write(&lock_path, contents).unwrap();
            let error = Recipe::load(root.path()).unwrap_err();
            let Error::EvaluateSourceLock { path, source } = error else {
                panic!("unexpected error: {error}");
            };
            assert_eq!(path, lock_path);
            assert!(source.to_string().contains(expected), "{source}");
        }
    }

    #[test]
    fn authored_load_ignores_generated_lock_bytes_without_mutating_them() {
        let root = tempfile::tempdir().unwrap();
        let recipe_path = root.path().join("stone.glu");
        let lock_path = root.path().join(SOURCE_LOCK_FILE_NAME);
        fs::write(&recipe_path, gluon_recipe(SOURCE_SPEC)).unwrap();
        fs::write(&lock_path, "not valid Gluon").unwrap();

        let recipe = Recipe::load_authored(root.path()).unwrap();

        assert_eq!(recipe.declaration.meta.pname, "example");
        assert!(recipe.source_lock.is_none());
        assert_eq!(fs::read_to_string(lock_path).unwrap(), "not valid Gluon");
    }

    #[test]
    fn stale_source_lock_rejects_count_kind_url_hash_and_requested_ref() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe_with_upstreams()).unwrap();
        let lock_path = root.path().join(SOURCE_LOCK_FILE_NAME);

        let mut count = matching_source_lock();
        count.sources.pop();

        let mut kind = matching_source_lock();
        kind.sources[0] = source_lock::SourceResolution::Git(source_lock::GitResolution {
            order: 0,
            url: ARCHIVE_URL.to_owned(),
            requested_ref: "archive".to_owned(),
            commit: FULL_COMMIT.to_owned(),
            materialization_sha256: MATERIALIZATION_SHA256.to_owned(),
        });

        let mut url = matching_source_lock();
        let source_lock::SourceResolution::Archive(archive) = &mut url.sources[0] else {
            unreachable!();
        };
        archive.url = "https://example.com/changed.tar.xz".to_owned();

        let mut hash = matching_source_lock();
        let source_lock::SourceResolution::Archive(archive) = &mut hash.sources[0] else {
            unreachable!();
        };
        archive.sha256 = "b".repeat(64);

        let mut requested_ref = matching_source_lock();
        let source_lock::SourceResolution::Git(git) = &mut requested_ref.sources[1] else {
            unreachable!();
        };
        git.requested_ref = "v2".to_owned();

        for (lock, expected) in [
            (count, "stale source count"),
            (kind, "stale source kind"),
            (url, "sources[0].url"),
            (hash, "sources[0].sha256"),
            (requested_ref, "sources[1].requested_ref"),
        ] {
            fs::write(&lock_path, canonical_source_lock(&lock)).unwrap();
            let error = Recipe::load(root.path()).unwrap_err();
            let Error::StaleSourceLock { path, source } = error else {
                panic!("unexpected error: {error}");
            };
            assert_eq!(path, lock_path);
            assert!(source.to_string().contains(expected), "{source}");
        }
    }

    #[test]
    fn recipe_and_lock_fingerprints_are_deterministic() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe(SOURCE_SPEC)).unwrap();
        let lock = canonical_source_lock(&SourceLock::default());
        fs::write(root.path().join(SOURCE_LOCK_FILE_NAME), &lock).unwrap();

        let first = Recipe::load(root.path()).unwrap();
        let repeated = Recipe::load(root.path()).unwrap();

        assert_eq!(first.declaration, repeated.declaration);
        assert_eq!(first.source, repeated.source);
        assert_eq!(first.fingerprint, repeated.fingerprint);

        fs::write(
            root.path().join(SOURCE_LOCK_FILE_NAME),
            format!("{lock}// semantically inert fingerprint change\n"),
        )
        .unwrap();
        let changed = Recipe::load(root.path()).unwrap();
        let first_fingerprint = &first.fingerprint;
        let changed_fingerprint = &changed.fingerprint;

        assert_ne!(first_fingerprint.sha256, changed_fingerprint.sha256);
        assert_ne!(
            first_fingerprint.explicit_inputs_sha256,
            changed_fingerprint.explicit_inputs_sha256
        );
    }

    #[test]
    fn explicit_build_timestamp_is_deterministic_and_ambient_free() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("stone.glu"), gluon_recipe(SOURCE_SPEC)).unwrap();
        let timestamp = DateTime::from_timestamp(1_700_000_000, 0).unwrap();

        let first = Recipe::load_at(root.path(), timestamp).unwrap();
        let repeated = Recipe::load_at(root.path(), timestamp).unwrap();
        let defaulted = Recipe::load(root.path()).unwrap();

        assert_eq!(first.build_time, repeated.build_time);
        assert_eq!(first.build_time.timestamp(), 1_700_000_000);
        assert_eq!(defaulted.build_time.timestamp(), 0);
    }
