-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "userspace-server",
        version = "1",
        release = 1,
        homepage = "https://example.invalid/userspace-roles",
        license = {
            "CC0-1.0"
        }
    },
    builder = {
        required_tools = {},
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {}
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Declarative service host role"
            },
            description = {
                kind = "some",
                value = "One explicit, typed userspace role with no imperative activation phase."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "package",
                    value = {
                        name = "openssh"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "podman"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd"
                    }
                }
            },
            runtime_exclude = {},
            paths = {},
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}