use std::path::{Path, PathBuf};

use declarative_config::{EngineId, LanguageId, LanguageSpec, SourceRoot};
use fs_err as fs;
use tempfile::tempdir;

use super::*;
use crate::declaration::RegisteredLanguages;

fn language(name: &str, extension: &str) -> LanguageSpec {
    LanguageSpec::new(
        LanguageId::new(name).unwrap(),
        EngineId::new(format!("{name}-engine"), "1").unwrap(),
        extension,
        "declaration-v1",
        format!("# generated by {name}\n"),
    )
    .unwrap()
}

fn languages() -> RegisteredLanguages {
    RegisteredLanguages::new([
        language("fixture", "decl"),
        language("alternate", "alt"),
    ])
    .unwrap()
}

fn limits(max_fragments: usize, max_directory_entries: usize) -> FragmentDeclarationLimits {
    FragmentDeclarationLimits::new(max_fragments, max_directory_entries)
}

fn write(path: impl AsRef<Path>, contents: &str) {
    let path = path.as_ref();
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, contents).unwrap();
}

fn discover(
    layers: impl IntoIterator<Item = PathBuf>,
    max_fragments: usize,
    max_directory_entries: usize,
) -> Result<FragmentDeclarationSet, FragmentDeclarationSetError> {
    FragmentDeclarationSet::discover(
        layers.into_iter().collect(),
        "bundle",
        &languages(),
        limits(max_fragments, max_directory_entries),
    )
}

#[test]
fn exact_registered_dispatch_retains_every_identity_in_deterministic_order() {
    let temporary = tempdir().unwrap();
    let layer = temporary.path().join("layer");
    write(layer.join("bundle.d/zeta.decl"), "zeta");
    write(layer.join("bundle.d/alpha.alt"), "alpha");
    write(layer.join("bundle.decl"), "root");
    write(layer.join("bundle.unknown"), "ignored root");
    fs::create_dir(layer.join("bundle.d/ignored.unknown")).unwrap();

    let first = discover([layer.clone()], 3, 3).unwrap();
    let repeated = discover([layer.clone()], 3, 3).unwrap();
    let identity = |set: &FragmentDeclarationSet| {
        set.iter()
            .map(|declaration| {
                (
                    declaration.layer_index(),
                    declaration.logical_name().to_owned(),
                    declaration.relative_path().to_owned(),
                    declaration.language().extension().to_owned(),
                )
            })
            .collect::<Vec<_>>()
    };

    assert_eq!(first.domain(), "bundle");
    assert_eq!(first.layer_directories(), [layer.clone()]);
    assert_eq!(identity(&first), identity(&repeated));
    assert_eq!(
        identity(&first),
        [
            (0, "bundle".to_owned(), PathBuf::from("bundle.decl"), "decl".to_owned()),
            (0, "alpha".to_owned(), PathBuf::from("bundle.d/alpha.alt"), "alt".to_owned()),
            (0, "zeta".to_owned(), PathBuf::from("bundle.d/zeta.decl"), "decl".to_owned()),
        ]
    );

    let expected_root = SourceRoot::new(&layer).unwrap();
    for declaration in first.iter() {
        assert_eq!(declaration.layer_directory(), layer);
        assert_eq!(
            declaration.physical_path(),
            layer.join(declaration.relative_path())
        );
        assert_eq!(declaration.source_root(), &expected_root);
        declaration.revalidate_before_read().unwrap();
        declaration.revalidate_after_read().unwrap();
    }
}

#[test]
fn every_same_layer_logical_collision_is_rejected() {
    let root_extensions = tempdir().unwrap();
    write(root_extensions.path().join("layer/bundle.decl"), "one");
    write(root_extensions.path().join("layer/bundle.alt"), "two");
    let error = discover([root_extensions.path().join("layer")], 8, 8).unwrap_err();
    assert!(matches!(
        error,
        FragmentDeclarationSetError::Collision {
            layer_index: 0,
            ref logical_name,
            ref paths,
        } if logical_name == "bundle" && paths.len() == 2
    ));

    let fragment_extensions = tempdir().unwrap();
    write(fragment_extensions.path().join("layer/bundle.d/shared.decl"), "one");
    write(fragment_extensions.path().join("layer/bundle.d/shared.alt"), "two");
    let error = discover([fragment_extensions.path().join("layer")], 8, 8).unwrap_err();
    assert!(matches!(
        error,
        FragmentDeclarationSetError::Collision {
            layer_index: 0,
            ref logical_name,
            ref paths,
        } if logical_name == "shared" && paths.len() == 2
    ));

    let root_and_fragment = tempdir().unwrap();
    write(root_and_fragment.path().join("layer/bundle.decl"), "root");
    write(root_and_fragment.path().join("layer/bundle.d/bundle.alt"), "fragment");
    let error = discover([root_and_fragment.path().join("layer")], 8, 8).unwrap_err();
    assert!(matches!(
        error,
        FragmentDeclarationSetError::Collision {
            layer_index: 0,
            ref logical_name,
            ref paths,
        } if logical_name == "bundle" && paths.len() == 2
    ));
}

#[test]
fn equal_logical_names_across_layers_are_preserved_in_layer_order() {
    let temporary = tempdir().unwrap();
    let lower = temporary.path().join("lower");
    let upper = temporary.path().join("upper");
    write(lower.join("bundle.d/shared.decl"), "lower");
    write(upper.join("bundle.d/shared.alt"), "upper");

    let set = discover([lower.clone(), upper.clone()], 2, 1).unwrap();

    assert_eq!(set.len(), 2);
    assert_eq!(
        set.iter()
            .map(|declaration| (
                declaration.layer_index(),
                declaration.logical_name(),
                declaration.language().extension(),
            ))
            .collect::<Vec<_>>(),
        [(0, "shared", "decl"), (1, "shared", "alt")]
    );
    assert_eq!(set.declarations()[0].layer_directory(), lower);
    assert_eq!(set.declarations()[1].layer_directory(), upper);
}

#[test]
fn unknown_extensions_are_ignored_even_when_their_entries_are_nonregular() {
    let temporary = tempdir().unwrap();
    let layer = temporary.path().join("layer");
    write(layer.join("bundle.unknown"), "ignored");
    fs::create_dir_all(layer.join("bundle.d/directory.unknown")).unwrap();
    write(layer.join("bundle.d/plain"), "ignored");

    let set = discover([layer], 0, 2).unwrap();

    assert!(set.is_empty());
}

#[test]
fn matching_nonregular_roots_and_fragments_fail_closed() {
    let root = tempdir().unwrap();
    fs::create_dir_all(root.path().join("layer/bundle.decl")).unwrap();
    assert!(matches!(
        discover([root.path().join("layer")], 4, 4),
        Err(FragmentDeclarationSetError::NotRegular { layer_index: 0, .. })
    ));

    let fragment = tempdir().unwrap();
    fs::create_dir_all(fragment.path().join("layer/bundle.d/value.alt")).unwrap();
    assert!(matches!(
        discover([fragment.path().join("layer")], 4, 4),
        Err(FragmentDeclarationSetError::NotRegular { layer_index: 0, .. })
    ));
}

#[test]
fn fragment_and_directory_entry_limits_accept_n_and_reject_n_plus_one() {
    let temporary = tempdir().unwrap();
    let layer = temporary.path().join("layer");
    write(layer.join("bundle.decl"), "root");
    write(layer.join("bundle.d/value.alt"), "fragment");
    write(layer.join("bundle.d/ignored.unknown"), "ignored");

    assert_eq!(discover([layer.clone()], 2, 2).unwrap().len(), 2);
    assert!(matches!(
        discover([layer.clone()], 1, 2),
        Err(FragmentDeclarationSetError::FragmentLimit { limit: 1 })
    ));
    assert!(matches!(
        discover([layer], 2, 1),
        Err(FragmentDeclarationSetError::DirectoryEntryLimit {
            layer_index: 0,
            limit: 1,
            ..
        })
    ));
}

#[test]
fn retained_layer_and_collection_identities_are_revalidated() {
    let layer_replacement = tempdir().unwrap();
    let layer = layer_replacement.path().join("layer");
    let held = layer_replacement.path().join("held");
    write(layer.join("bundle.decl"), "root");
    let set = discover([layer.clone()], 1, 0).unwrap();
    fs::rename(&layer, &held).unwrap();
    fs::create_dir(&layer).unwrap();
    assert!(matches!(
        set.declarations()[0].revalidate_before_read(),
        Err(FragmentDeclarationSetError::SourceRootChanged {
            layer_index: 0,
            ..
        })
    ));

    let collection_replacement = tempdir().unwrap();
    let layer = collection_replacement.path().join("layer");
    let collection = layer.join("bundle.d");
    let held = layer.join("held");
    write(collection.join("value.decl"), "value");
    let set = discover([layer], 1, 1).unwrap();
    fs::rename(&collection, &held).unwrap();
    fs::create_dir(&collection).unwrap();
    assert!(matches!(
        set.declarations()[0].revalidate_after_read(),
        Err(FragmentDeclarationSetError::CollectionChanged {
            layer_index: 0,
            ..
        })
    ));
}

#[test]
fn domain_basename_is_safe_and_missing_layers_remain_explicit() {
    let temporary = tempdir().unwrap();
    let missing = temporary.path().join("missing");
    let set = FragmentDeclarationSet::discover(
        vec![missing.clone()],
        "safe-domain",
        &languages(),
        limits(0, 0),
    )
    .unwrap();
    assert_eq!(set.layer_directories(), [missing]);
    assert!(set.is_empty());

    for domain in ["", ".", "..", "nested/name", "nested\\name", "line\nbreak"] {
        assert!(matches!(
            FragmentDeclarationSet::discover(Vec::new(), domain, &languages(), limits(0, 0)),
            Err(FragmentDeclarationSetError::InvalidDomain { .. })
        ));
    }
}
