-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-factory-override-fixture-1.0.0.tar",
            sha256 = "cc10c246cfaeeb644e2a458794262fd68ade2c0d76c0874a932a787ad088e001"
        },
    },
}