-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-generated-shell-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-generated-shell-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        kind = "custom",
        spec = {
            required_tools = {
                {
                    kind = "binary",
                    value = "bash"
                },
                {
                    kind = "binary",
                    value = "install"
                }
            },
            environment = {},
            phases = {
                setup = {
                    steps = {}
                },
                build = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/bash",
                                requirement = {
                                    kind = "binary",
                                    value = "bash"
                                }
                            },
                            declared_programs = {},
                            script = "\nprintf '%s\\n' \\\n    '#!/usr/bin/bash' \\\n    'set -euo pipefail' \\\n    '' \\\n    'if [[ \"$#\" -eq 0 ]]; then' \\\n    \"    printf '%s\\\\n' 'cast-generated-shell'\" \\\n    'elif [[ \"$#\" -eq 1 && \"$1\" == --self-test ]]; then' \\\n    \"    printf '%s\\\\n' 'cast-generated-shell: self-test passed'\" \\\n    'else' \\\n    \"    printf '%s\\\\n' 'usage: cast-generated-shell [--self-test]' >&2\" \\\n    '    exit 64' \\\n    'fi' \\\n    > cast-generated-shell\n"
                        }
                    }
                },
                install = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/bash",
                                requirement = {
                                    kind = "binary",
                                    value = "bash"
                                }
                            },
                            declared_programs = {
                                {
                                    path = "/usr/bin/install",
                                    requirement = {
                                        kind = "binary",
                                        value = "install"
                                    }
                                }
                            },
                            script = "install -Dm755 cast-generated-shell \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/cast-generated-shell\""
                        }
                    }
                },
                check = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/bash",
                                requirement = {
                                    kind = "binary",
                                    value = "bash"
                                }
                            },
                            declared_programs = {},
                            script = "\nactual=\"$(source ./cast-generated-shell --self-test)\"\nif [[ \"${actual}\" != 'cast-generated-shell: self-test passed' ]]; then\n    printf '%s\\n' 'generated shell self-test output differed' >&2\n    exit 1\nfi\n\nset +e\n(source ./cast-generated-shell --unexpected >/dev/null 2>&1)\nstatus=\"$?\"\nset -e\nif [[ \"${status}\" -ne 64 ]]; then\n    printf 'unexpected-argument status was %s, expected 64\\n' \"${status}\" >&2\n    exit 1\nfi\n"
                        }
                    }
                },
                workload = {
                    steps = {}
                }
            },
            supported_hooks = {
                setup = true,
                build = true,
                check = true,
                install = true,
                workload = true
            }
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Authored shell application fixture"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "binary",
                    value = "bash"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/cast-generated-shell"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}