-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-hooks-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-hooks-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        kind = "custom",
        spec = {
            required_tools = {
                {
                    kind = "binary",
                    value = "sh"
                },
                {
                    kind = "binary",
                    value = "ninja"
                }
            },
            environment = {
                "cmake"
            },
            phases = {
                setup = {
                    steps = {
                        {
                            kind = "cmake_configure",
                            flags = {}
                        }
                    }
                },
                build = {
                    steps = {
                        {
                            kind = "cmake_build"
                        }
                    }
                },
                install = {
                    steps = {
                        {
                            kind = "cmake_install"
                        }
                    }
                },
                check = {
                    steps = {
                        {
                            kind = "cmake_test"
                        }
                    }
                },
                workload = {
                    steps = {}
                }
            },
            supported_hooks = {
                setup = true,
                build = true,
                check = true,
                install = true,
                workload = true
            }
        }
    },
    hooks = {
        pre_setup = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {
                    {
                        path = "/usr/bin/patch",
                        requirement = {
                            kind = "binary",
                            value = "patch"
                        }
                    }
                },
                script = "patch -d . -p1 -i \"${CAST_SOURCE_DIR}/pre-setup.patch\""
            }
        },
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "patch"
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        },
        {
            name = "docs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Documentation for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Documentation files for the cast-hooks-fixture package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/gtk-doc"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Development files for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you intend to build software against\nthe cast-hooks-fixture package."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-hooks-fixture"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/aclocal"
                },
                {
                    kind = "any",
                    path = "/usr/share/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man2"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man3"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man9"
                },
                {
                    kind = "any",
                    path = "/usr/share/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/gir-1.0/*.gir"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.deps"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.vapi"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.prl"
                },
                {
                    kind = "any",
                    path = "/usr/lib/metatypes"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/metatypes/qt*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/mkspecs"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/modules/*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/sbom"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/plugins/designer/*.so"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.tags"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.tags"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the cast-hooks-fixture package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Library files for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Library files for cast-hooks-fixture, typically pulled in as a dependency of another package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {},
            conflicts = {}
        },
        {
            name = "32bit",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides 32-bit runtime libraries for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you need the 32-bit versions of the\ncast-hooks-fixture package libraries."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-hooks-fixture"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides development files for cast-hooks-fixture-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need to build software against\nthe 32-bit version of cast-hooks-fixture, cast-hooks-fixture-32bit."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-hooks-fixture"
                        },
                        output = "32bit"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-hooks-fixture"
                        },
                        output = "devel"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/pkgconfig"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for cast-hooks-fixture-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the cast-hooks-fixture-32bit package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "demos",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Example files for cast-hooks-fixture"
            },
            description = {
                kind = "some",
                value = "Example files for the cast-hooks-fixture package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/qt*/examples"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-hooks-fixture-1.0.0.tar.xz",
            hash = "238b6e91994ceecd1bc0d8365cc77f4166d5db22d1faa1f5eab80a0389c1210c",
            rename = {
                kind = "some",
                value = "cast-hooks-fixture.tar.xz"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-hooks-fixture"
            }
        },
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-hooks-fixture-1.0.0-pre-setup.patch",
            hash = "1766d7a2e9ae6316169aa88a452b134eed19151f9dc15e81a57c93a2ff7dc986",
            rename = {
                kind = "some",
                value = "pre-setup.patch"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = false,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {},
    tuning = {},
    emul32 = false,
    mold = false,
}