-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-header-only-library-fixture-1.0.0.tar",
            sha256 = "ab0bc1ad844befe29383465ad24872f6314ae01fa3c7456679a41372d37a492e"
        },
    },
}