-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-meson-fixture-1.0.0.tar",
            sha256 = "3119d25a8f56dc208c5dcc907b6c5a4203c87c7ad28897b85e2c0eeed28ab995"
        },
    },
}