-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-meson-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-meson-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "cmake"
            },
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            },
            {
                kind = "binary",
                value = "pkgconf"
            }
        },
        environment = {
            "meson"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "meson_setup",
                        flags = {}
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "meson_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "meson_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "meson_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {
        {
            kind = "pkg_config",
            value = "zlib"
        }
    },
    check_inputs = {
        {
            kind = "binary",
            value = "file"
        }
    },
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        },
        {
            name = "docs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Documentation for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Documentation files for the cast-meson-fixture package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/gtk-doc"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Development files for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you intend to build software against\nthe cast-meson-fixture package."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-meson-fixture"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/aclocal"
                },
                {
                    kind = "any",
                    path = "/usr/share/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man2"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man3"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man9"
                },
                {
                    kind = "any",
                    path = "/usr/share/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/gir-1.0/*.gir"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.deps"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.vapi"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.prl"
                },
                {
                    kind = "any",
                    path = "/usr/lib/metatypes"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/metatypes/qt*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/mkspecs"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/modules/*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/sbom"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/plugins/designer/*.so"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.tags"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.tags"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the cast-meson-fixture package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Library files for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Library files for cast-meson-fixture, typically pulled in as a dependency of another package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {},
            conflicts = {}
        },
        {
            name = "32bit",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides 32-bit runtime libraries for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Install this package if you need the 32-bit versions of the\ncast-meson-fixture package libraries."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-meson-fixture"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides development files for cast-meson-fixture-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need to build software against\nthe 32-bit version of cast-meson-fixture, cast-meson-fixture-32bit."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-meson-fixture"
                        },
                        output = "32bit"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "cast-meson-fixture"
                        },
                        output = "devel"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/pkgconfig"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for cast-meson-fixture-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the cast-meson-fixture-32bit package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "demos",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Example files for cast-meson-fixture"
            },
            description = {
                kind = "some",
                value = "Example files for the cast-meson-fixture package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/qt*/examples"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-meson-fixture-1.0.0.tar",
            hash = "3119d25a8f56dc208c5dcc907b6c5a4203c87c7ad28897b85e2c0eeed28ab995",
            rename = {
                kind = "some",
                value = "cast-meson-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-meson-fixture"
            }
        }
    },
    architectures = {},
    tuning = {},
    emul32 = false,
    mold = false,
}