-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-cargo-fixture-1.0.0.tar",
            sha256 = "a6ced421d2b8a8d319abc46c6c6d34e65bcf4fdf87a26778e3a450f4ed23a5a0"
        },
    },
}