-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-go-module-fixture-1.0.0.tar.zst",
            sha256 = "f4c4eb74304956e3f3e650d2004c78a39c4d4c009e447b9c28b3819370dbc78f"
        },
    },
}