-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "protocol-inspect-wrapper",
        version = "1.0.0",
        release = 1,
        homepage = "https://example.invalid/protocol-engine",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "output",
                value = {
                    package = {
                        name = "protocol-engine"
                    },
                    output = "tools"
                }
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/opt/protocol-engine/bin/protocol-inspect",
                            requirement = {
                                kind = "output",
                                value = {
                                    package = {
                                        name = "protocol-engine"
                                    },
                                    output = "tools"
                                }
                            }
                        },
                        args = {
                            "--emit-completions",
                            "protocol-inspect.completions"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\nprintf '%s\\n' '#!/usr/bin/bash' 'exec /opt/protocol-engine/bin/protocol-inspect \"$@\"' > protocol-inspect\ninstall -Dm755 protocol-inspect \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/protocol-inspect\"\ninstall -Dm644 protocol-inspect.completions \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/bash-completion/completions/protocol-inspect\"\n"
                    }
                }
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Protocol inspection command wrapper"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "protocol-engine"
                        },
                        output = "tools"
                    }
                },
                {
                    kind = "binary",
                    value = "bash"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/protocol-inspect"
                },
                {
                    kind = "any",
                    path = "/usr/share/bash-completion/completions/protocol-inspect"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}