-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "optional-source-graph",
        version = "3.0.0",
        release = 1,
        homepage = "https://example.invalid/optional-source-graph",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {},
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {}
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {
            {
                kind = "run",
                program = {
                    path = "/usr/bin/component-preparer",
                    requirement = {
                        kind = "binary",
                        value = "component-preparer"
                    }
                },
                args = {
                    "--source",
                    "../components"
                }
            }
        },
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "component-preparer"
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        },
        {
            name = "components",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Optional source-graph components"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/optional-source-graph/components"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/optional-source-graph-3.0.0.tar.xz",
            hash = "1111111111111111111111111111111111111111111111111111111111111111",
            rename = {
                kind = "some",
                value = "optional-source-graph.tar.xz"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "application"
            }
        },
        {
            kind = "archive",
            url = "https://example.invalid/optional-source-graph-components-3.0.0.tar.xz",
            hash = "2222222222222222222222222222222222222222222222222222222222222222",
            rename = {
                kind = "some",
                value = "optional-source-graph-components.tar.xz"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "components"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}