-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-desktop-integration-fixture-1.0.0.tar",
            sha256 = "0f39867b15a8ae8f5386fdc768fd83e2874ac41f6e5c8c8711b5ce9a67887169"
        },
    },
}