-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "hooked-library",
        version = "5.3.0",
        release = 1,
        homepage = "https://example.invalid/hooked-library",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DBUILD_TESTING=ON"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {
            {
                kind = "run",
                program = {
                    path = "/usr/bin/patch",
                    requirement = {
                        kind = "binary",
                        value = "patch"
                    }
                },
                args = {
                    "-p1",
                    "-i",
                    "compat.patch"
                }
            }
        },
        post_setup = {},
        pre_build = {},
        post_build = {
            {
                kind = "run",
                program = {
                    path = "/usr/bin/strip-nondeterminism",
                    requirement = {
                        kind = "binary",
                        value = "strip-nondeterminism"
                    }
                },
                args = {
                    "build/generated.dat"
                }
            }
        },
        pre_check = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {},
                script = "test -d \"${CAST_BUILDER_DIR}\"\ntest -f \"${CAST_BUILDER_DIR}/CMakeCache.txt\""
            }
        },
        post_check = {},
        pre_install = {},
        post_install = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {
                    {
                        path = "/usr/bin/install",
                        requirement = {
                            kind = "binary",
                            value = "install"
                        }
                    },
                    {
                        path = "/usr/bin/ln",
                        requirement = {
                            kind = "binary",
                            value = "ln"
                        }
                    }
                },
                script = "\ninstall -Dm644 packaging/hooked.conf \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/hooked/hooked.conf\"\nln -s hooked \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/hooked-compat\"\n"
            }
        },
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "patch"
        },
        {
            kind = "binary",
            value = "strip-nondeterminism"
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        },
        {
            name = "docs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Documentation for hooked-library"
            },
            description = {
                kind = "some",
                value = "Documentation files for the hooked-library package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/gtk-doc"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Development files for hooked-library"
            },
            description = {
                kind = "some",
                value = "Install this package if you intend to build software against\nthe hooked-library package."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "hooked-library"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/aclocal"
                },
                {
                    kind = "any",
                    path = "/usr/share/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man2"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man3"
                },
                {
                    kind = "any",
                    path = "/usr/share/man/man9"
                },
                {
                    kind = "any",
                    path = "/usr/share/pkgconfig"
                },
                {
                    kind = "any",
                    path = "/usr/share/gir-1.0/*.gir"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.deps"
                },
                {
                    kind = "any",
                    path = "/usr/share/vala/vapi/*.vapi"
                },
                {
                    kind = "any",
                    path = "/usr/lib/*.prl"
                },
                {
                    kind = "any",
                    path = "/usr/lib/metatypes"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/metatypes/qt*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/mkspecs"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/modules/*.json"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/sbom"
                },
                {
                    kind = "any",
                    path = "/usr/lib/qt*/plugins/designer/*.so"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt5/*.tags"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.qch"
                },
                {
                    kind = "any",
                    path = "/usr/share/doc/qt6/*.tags"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for hooked-library"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the hooked-library package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Library files for hooked-library"
            },
            description = {
                kind = "some",
                value = "Library files for hooked-library, typically pulled in as a dependency of another package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {},
            conflicts = {}
        },
        {
            name = "32bit",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides 32-bit runtime libraries for hooked-library"
            },
            description = {
                kind = "some",
                value = "Install this package if you need the 32-bit versions of the\nhooked-library package libraries."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "hooked-library"
                        },
                        output = "out"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Provides development files for hooked-library-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need to build software against\nthe 32-bit version of hooked-library, hooked-library-32bit."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "hooked-library"
                        },
                        output = "32bit"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "hooked-library"
                        },
                        output = "devel"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/*.a"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/cmake"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/lib*.so"
                },
                {
                    kind = "any",
                    path = "/usr/lib32/pkgconfig"
                }
            },
            conflicts = {}
        },
        {
            name = "32bit-dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Debugging symbols for hooked-library-32bit"
            },
            description = {
                kind = "some",
                value = "Install this package if you need debugging information + symbols\nfor the hooked-library-32bit package."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib32/debug"
                }
            },
            conflicts = {}
        },
        {
            name = "demos",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Example files for hooked-library"
            },
            description = {
                kind = "some",
                value = "Example files for the hooked-library package"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/qt*/examples"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/hooked-library-5.3.0.tar.gz",
            hash = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {},
    tuning = {},
    emul32 = false,
    mold = false,
}