-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "graphite-renderer-wrapper",
        version = "1.0.0",
        release = 1,
        homepage = "https://example.invalid/graphite-renderer",
        license = {
            "MIT"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "bash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "printf '%s' '#!/usr/bin/bash\nexport GRAPHITE_PLUGIN_DIR=/usr/lib/graphite-renderer/plugins\nexport GRAPHITE_DATA_DIR=/usr/share/graphite-renderer\nexport SSL_CERT_FILE=/usr/share/system-trust/ca-bundle.pem\nexport GSETTINGS_SCHEMA_DIR=/usr/share/glib-2.0/schemas\nexec /usr/libexec/graphite-renderer/graphite-renderer \"$@\"\n' > graphite-renderer\n/usr/bin/install -Dm755 graphite-renderer \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/graphite-renderer\""
                    }
                }
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Graphite renderer with a closed runtime environment"
            },
            description = {
                kind = "some",
                value = "A source-less wrapper that binds one absolute renderer and every runtime resource without ambient discovery."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "graphite-renderer"
                        },
                        output = "runtime"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "graphite-codecs"
                        },
                        output = "plugins"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "graphite-assets"
                        },
                        output = "data"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "system-trust"
                        },
                        output = "certificates"
                    }
                },
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "desktop-schema-registry"
                        },
                        output = "schemas"
                    }
                },
                {
                    kind = "binary",
                    value = "bash"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/graphite-renderer"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}