// SPDX-FileCopyrightText: 2026 AerynOS Developers
// SPDX-License-Identifier: MPL-2.0

use std::{
    collections::BTreeMap,
    error::Error,
    ffi::{CStr, CString, OsStr, OsString},
    fmt,
    fs::Metadata,
    io::{self, Read as _, Write as _},
    os::{
        fd::{AsRawFd as _, FromRawFd as _, OwnedFd},
        unix::{
            ffi::{OsStrExt as _, OsStringExt as _},
            fs::MetadataExt as _,
        },
    },
    path::{Component, Path, PathBuf},
};

use fs_err as fs;
use fs_err::os::unix::fs::OpenOptionsExt as _;
use gluon_config::{Evaluation, EvaluationFingerprint, Evaluator, Source, SourceRoot};

use super::{Config, Entry, Manager, Resolve};

pub const GENERATED_GLUON_MARKER: &str = "// @generated by os-tools. DO NOT EDIT.\n";

/// Maximum number of authored fragments considered by one manager load.
///
/// The count includes root fragments and fragments which are later shadowed
/// by a higher-precedence layer: an override cannot hide evaluation work from
/// this budget.
const MAX_GLUON_FRAGMENTS: usize = 1024;
const MAX_GLUON_DIRECTORY_ENTRIES: usize = 4096;
const MAX_GLUON_FRAGMENT_NAME_BYTES: usize = 251;

/// Maximum size of a fragment emitted and subsequently managed by this crate.
/// Authored fragments use the (possibly stricter) limit of their evaluator.
const MAX_GENERATED_GLUON_BYTES: usize = 1024 * 1024;

const TEMPORARY_RANDOM_BYTES: usize = 16;
const TEMPORARY_CREATE_ATTEMPTS: usize = 100;
const TEMPORARY_PREFIX: &str = ".gluon-tmp-";

pub type GluonConversionError = Box<dyn Error + Send + Sync + 'static>;

/// Result of evaluating and semantically converting a Gluon fragment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecodedGluon<T> {
    pub value: T,
    pub fingerprint: EvaluationFingerprint,
}

impl<T> From<Evaluation<T>> for DecodedGluon<T> {
    fn from(evaluation: Evaluation<T>) -> Self {
        Self {
            value: evaluation.value,
            fingerprint: evaluation.fingerprint,
        }
    }
}

/// Consumer-owned Gluon/Rust boundary for one configuration domain.
///
/// Implementations evaluate their stable Gluon DTO through the supplied
/// restricted evaluator, convert it into the domain type, and emit standalone
/// canonical literals for generated fragments.
pub trait GluonCodec {
    type Config: Config;

    fn decode(&self, evaluator: &Evaluator, source: &Source) -> Result<DecodedGluon<Self::Config>, GluonCodecError>;

    /// Return a standalone canonical Gluon expression without a generated
    /// marker. [`Manager::save_gluon`] adds the marker atomically.
    fn encode(&self, config: &Self::Config) -> Result<String, GluonCodecError>;
}

#[derive(Debug)]
pub enum GluonCodecError {
    Evaluation(gluon_config::Diagnostic),
    Conversion(GluonConversionError),
}

impl GluonCodecError {
    pub fn conversion(error: impl Error + Send + Sync + 'static) -> Self {
        Self::Conversion(Box::new(error))
    }
}

impl From<gluon_config::Diagnostic> for GluonCodecError {
    fn from(error: gluon_config::Diagnostic) -> Self {
        Self::Evaluation(error)
    }
}

impl fmt::Display for GluonCodecError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Evaluation(error) => write!(formatter, "evaluate Gluon value: {error}"),
            Self::Conversion(error) => write!(formatter, "convert Gluon value: {error}"),
        }
    }
}

impl Error for GluonCodecError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Evaluation(error) => Some(error),
            Self::Conversion(error) => Some(error.as_ref()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadedGluonConfig<T> {
    pub logical_name: String,
    pub path: PathBuf,
    pub value: T,
    pub fingerprint: EvaluationFingerprint,
}

#[derive(Debug)]
pub enum LoadGluonError {
    Enumerate {
        path: PathBuf,
        source: io::Error,
    },
    Read {
        path: PathBuf,
        source: io::Error,
    },
    Evaluation {
        path: PathBuf,
        source: gluon_config::Diagnostic,
    },
    Conversion {
        path: PathBuf,
        source: GluonConversionError,
    },
    FragmentLimit {
        limit: usize,
    },
    DirectoryEntryLimit {
        path: PathBuf,
        limit: usize,
    },
}

impl fmt::Display for LoadGluonError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Enumerate { path, .. } => write!(formatter, "enumerate Gluon fragments in {}", path.display()),
            Self::Read { path, .. } => write!(formatter, "read Gluon fragment {}", path.display()),
            Self::Evaluation { path, source } => {
                write!(formatter, "evaluate Gluon fragment {}: {source}", path.display())
            }
            Self::Conversion { path, source } => {
                write!(formatter, "convert Gluon fragment {}: {source}", path.display())
            }
            Self::FragmentLimit { limit } => {
                write!(formatter, "Gluon configuration exceeds the {limit}-fragment limit")
            }
            Self::DirectoryEntryLimit { path, limit } => {
                write!(
                    formatter,
                    "Gluon fragment directory {} exceeds the {limit}-entry scan limit",
                    path.display()
                )
            }
        }
    }
}

impl Error for LoadGluonError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Enumerate { source, .. } | Self::Read { source, .. } => Some(source),
            Self::Evaluation { source, .. } => Some(source),
            Self::Conversion { source, .. } => Some(source.as_ref()),
            Self::FragmentLimit { .. } | Self::DirectoryEntryLimit { .. } => None,
        }
    }
}

#[derive(Debug)]
pub enum SaveGluonError {
    InvalidName {
        name: String,
    },
    CreateDir {
        path: PathBuf,
        source: io::Error,
    },
    Encode {
        source: GluonCodecError,
    },
    ReadExisting {
        path: PathBuf,
        source: io::Error,
    },
    AuthoredFragment {
        path: PathBuf,
    },
    CreateTemporary {
        path: PathBuf,
        source: io::Error,
    },
    WriteTemporary {
        path: PathBuf,
        source: io::Error,
    },
    SyncTemporary {
        path: PathBuf,
        source: io::Error,
    },
    CleanupTemporary {
        path: PathBuf,
        source: io::Error,
    },
    GeneratedTooLarge {
        size: usize,
        limit: usize,
    },
    Rename {
        from: PathBuf,
        to: PathBuf,
        source: io::Error,
    },
    SyncDirectory {
        path: PathBuf,
        source: io::Error,
    },
}

impl fmt::Display for SaveGluonError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidName { name } => {
                write!(formatter, "invalid Gluon fragment name {name:?}")
            }
            Self::CreateDir { path, .. } => write!(formatter, "create Gluon config directory {}", path.display()),
            Self::Encode { .. } => formatter.write_str("encode generated Gluon fragment"),
            Self::ReadExisting { path, .. } => {
                write!(formatter, "read existing Gluon fragment {}", path.display())
            }
            Self::AuthoredFragment { path } => {
                write!(
                    formatter,
                    "refuse to overwrite authored Gluon fragment {}",
                    path.display()
                )
            }
            Self::CreateTemporary { path, .. } => {
                write!(formatter, "create temporary Gluon fragment {}", path.display())
            }
            Self::WriteTemporary { path, .. } => {
                write!(formatter, "write temporary Gluon fragment {}", path.display())
            }
            Self::SyncTemporary { path, .. } => {
                write!(formatter, "sync temporary Gluon fragment {}", path.display())
            }
            Self::CleanupTemporary { path, .. } => {
                write!(formatter, "clean up temporary Gluon fragment {}", path.display())
            }
            Self::GeneratedTooLarge { size, limit } => {
                write!(
                    formatter,
                    "generated Gluon fragment is {size} bytes; limit is {limit} bytes"
                )
            }
            Self::Rename { from, to, .. } => {
                write!(formatter, "rename {} to {}", from.display(), to.display())
            }
            Self::SyncDirectory { path, .. } => {
                write!(formatter, "sync Gluon config directory {}", path.display())
            }
        }
    }
}

impl Error for SaveGluonError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::CreateDir { source, .. }
            | Self::ReadExisting { source, .. }
            | Self::CreateTemporary { source, .. }
            | Self::WriteTemporary { source, .. }
            | Self::SyncTemporary { source, .. }
            | Self::CleanupTemporary { source, .. }
            | Self::Rename { source, .. }
            | Self::SyncDirectory { source, .. } => Some(source),
            Self::Encode { source } => Some(source),
            Self::InvalidName { .. } | Self::AuthoredFragment { .. } | Self::GeneratedTooLarge { .. } => None,
        }
    }
}

#[derive(Debug)]
pub enum DeleteGluonError {
    InvalidName { name: String },
    ReadExisting { path: PathBuf, source: io::Error },
    AuthoredFragment { path: PathBuf },
    Remove { path: PathBuf, source: io::Error },
    SyncDirectory { path: PathBuf, source: io::Error },
}

impl fmt::Display for DeleteGluonError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidName { name } => {
                write!(formatter, "invalid Gluon fragment name {name:?}")
            }
            Self::ReadExisting { path, .. } => {
                write!(formatter, "read existing Gluon fragment {}", path.display())
            }
            Self::AuthoredFragment { path } => {
                write!(formatter, "refuse to delete authored Gluon fragment {}", path.display())
            }
            Self::Remove { path, .. } => write!(formatter, "delete generated Gluon fragment {}", path.display()),
            Self::SyncDirectory { path, .. } => {
                write!(formatter, "sync Gluon config directory {}", path.display())
            }
        }
    }
}

impl Error for DeleteGluonError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::ReadExisting { source, .. } | Self::Remove { source, .. } | Self::SyncDirectory { source, .. } => {
                Some(source)
            }
            Self::InvalidName { .. } | Self::AuthoredFragment { .. } => None,
        }
    }
}

impl Manager {
    /// Load only `.glu` fragments using explicit vendor, admin, and user
    /// precedence. Higher-priority fragments replace lower-priority fragments
    /// with the same logical name.
    pub fn load_gluon<C: GluonCodec>(
        &self,
        evaluator: &Evaluator,
        codec: &C,
    ) -> Result<Vec<LoadedGluonConfig<C::Config>>, LoadGluonError> {
        self.load_gluon_with_hook(evaluator, codec, || {})
    }

    fn load_gluon_with_hook<C: GluonCodec>(
        &self,
        evaluator: &Evaluator,
        codec: &C,
        before_fragment_reads: impl FnOnce(),
    ) -> Result<Vec<LoadedGluonConfig<C::Config>>, LoadGluonError> {
        let domain = C::Config::domain();
        let max_source_bytes = evaluator.limits().max_source_bytes;
        let fragments = collect_gluon_paths(&self.scope, &domain)?;
        before_fragment_reads();
        let mut loaded = BTreeMap::new();

        for fragment in fragments {
            verify_source_root(&fragment.source_root_path, &fragment.source_root)?;
            verify_collection(fragment.collection.as_ref())?;
            let source = fragment
                .source_root
                .load(&fragment.relative_path, max_source_bytes)
                .map_err(|source| LoadGluonError::Evaluation {
                    path: fragment.path.clone(),
                    source,
                })?;
            verify_collection(fragment.collection.as_ref())?;
            verify_source_root(&fragment.source_root_path, &fragment.source_root)?;
            let evaluator = evaluator.clone().with_source_root(fragment.source_root);
            let decoded = codec.decode(&evaluator, &source).map_err(|error| match error {
                GluonCodecError::Evaluation(source) => LoadGluonError::Evaluation {
                    path: fragment.path.clone(),
                    source,
                },
                GluonCodecError::Conversion(source) => LoadGluonError::Conversion {
                    path: fragment.path.clone(),
                    source,
                },
            })?;

            loaded.insert(
                fragment.logical_name.clone(),
                LoadedGluonConfig {
                    logical_name: fragment.logical_name,
                    path: fragment.path,
                    value: decoded.value,
                    fingerprint: decoded.fingerprint,
                },
            );
        }

        Ok(loaded.into_values().collect())
    }

    /// Atomically save one generated `.glu` fragment.
    pub fn save_gluon<C: GluonCodec>(
        &self,
        name: impl fmt::Display,
        config: &C::Config,
        codec: &C,
    ) -> Result<PathBuf, SaveGluonError> {
        let name = name.to_string();
        if !is_safe_fragment_name(&name) {
            return Err(SaveGluonError::InvalidName { name });
        }
        let literal = codec
            .encode(config)
            .map_err(|source| SaveGluonError::Encode { source })?;
        let generated_size = GENERATED_GLUON_MARKER
            .len()
            .saturating_add(literal.len())
            .saturating_add(usize::from(!literal.ends_with('\n')));
        if generated_size > MAX_GENERATED_GLUON_BYTES {
            return Err(SaveGluonError::GeneratedTooLarge {
                size: generated_size,
                limit: MAX_GENERATED_GLUON_BYTES,
            });
        }
        let mut generated = String::with_capacity(generated_size);
        generated.push_str(GENERATED_GLUON_MARKER);
        generated.push_str(&literal);
        if !generated.ends_with('\n') {
            generated.push('\n');
        }

        let domain = C::Config::domain();
        let dir = self.scope.save_dir(&domain);
        fs::create_dir_all(&dir).map_err(|source| SaveGluonError::CreateDir {
            path: dir.clone(),
            source,
        })?;
        let directory = FragmentDirectory::open(&dir).map_err(|source| SaveGluonError::CreateDir {
            path: dir.clone(),
            source,
        })?;
        directory.verify_path().map_err(|source| SaveGluonError::CreateDir {
            path: dir.clone(),
            source,
        })?;
        let file_name = OsString::from(format!("{name}.glu"));
        let path = dir.join(&file_name);
        let expected =
            match inspect_existing_fragment(&directory, &file_name, MAX_GENERATED_GLUON_BYTES).map_err(|source| {
                SaveGluonError::ReadExisting {
                    path: path.clone(),
                    source,
                }
            })? {
                None => ExpectedTarget::Missing,
                Some(existing) if existing.generated => ExpectedTarget::Generated(existing.identity),
                Some(_) => {
                    return Err(SaveGluonError::AuthoredFragment { path });
                }
            };
        atomic_write(&directory, &file_name, &path, generated.as_bytes(), expected)?;
        Ok(path)
    }

    /// Delete only the named generated Gluon fragment, leaving unrelated
    /// files untouched.
    pub fn delete_gluon<T: Config>(&self, name: impl fmt::Display) -> Result<(), DeleteGluonError> {
        self.delete_gluon_with_hook::<T>(name, || {})
    }

    fn delete_gluon_with_hook<T: Config>(
        &self,
        name: impl fmt::Display,
        before_remove: impl FnOnce(),
    ) -> Result<(), DeleteGluonError> {
        let name = name.to_string();
        if !is_safe_fragment_name(&name) {
            return Err(DeleteGluonError::InvalidName { name });
        }
        let dir = self.scope.save_dir(&T::domain());
        let file_name = OsString::from(format!("{name}.glu"));
        let path = dir.join(&file_name);
        let directory = match FragmentDirectory::open(&dir) {
            Ok(directory) => directory,
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
            Err(source) => {
                return Err(DeleteGluonError::ReadExisting { path, source });
            }
        };
        directory
            .verify_path()
            .map_err(|source| DeleteGluonError::ReadExisting {
                path: path.clone(),
                source,
            })?;
        let existing =
            match inspect_existing_fragment(&directory, &file_name, MAX_GENERATED_GLUON_BYTES).map_err(|source| {
                DeleteGluonError::ReadExisting {
                    path: path.clone(),
                    source,
                }
            })? {
                None => return Ok(()),
                Some(existing) if existing.generated => existing,
                Some(_) => return Err(DeleteGluonError::AuthoredFragment { path }),
            };
        before_remove();
        directory
            .verify_path()
            .map_err(|source| DeleteGluonError::ReadExisting {
                path: path.clone(),
                source,
            })?;
        require_same_generated_fragment(&directory, &file_name, existing.identity).map_err(|source| {
            DeleteGluonError::ReadExisting {
                path: path.clone(),
                source,
            }
        })?;
        directory
            .unlink(&file_name)
            .map_err(|source| DeleteGluonError::Remove {
                path: path.clone(),
                source,
            })?;
        directory.sync().map_err(|source| DeleteGluonError::SyncDirectory {
            path: dir.clone(),
            source,
        })?;
        directory
            .verify_path()
            .map_err(|source| DeleteGluonError::SyncDirectory { path: dir, source })
    }
}

#[derive(Debug)]
struct GluonPath {
    logical_name: String,
    source_root_path: PathBuf,
    source_root: SourceRoot,
    relative_path: PathBuf,
    path: PathBuf,
    collection: Option<CollectionIdentity>,
}

#[derive(Debug, Clone)]
struct CollectionIdentity {
    path: PathBuf,
    identity: FileSnapshot,
}

fn collect_gluon_paths(scope: &super::Scope, domain: &str) -> Result<Vec<GluonPath>, LoadGluonError> {
    let mut paths = Vec::new();
    for (entry, resolve) in scope.load_with() {
        let remaining = MAX_GLUON_FRAGMENTS.saturating_sub(paths.len());
        let layer = enumerate_gluon_paths(entry, resolve, domain, remaining)?;
        if paths.len().saturating_add(layer.len()) > MAX_GLUON_FRAGMENTS {
            return Err(LoadGluonError::FragmentLimit {
                limit: MAX_GLUON_FRAGMENTS,
            });
        }
        paths.extend(layer);
    }
    Ok(paths)
}

fn enumerate_gluon_paths(
    entry: Entry,
    resolve: Resolve<'_>,
    domain: &str,
    remaining: usize,
) -> Result<Vec<GluonPath>, LoadGluonError> {
    let source_root_path = resolve.config_dir();
    let source_root = match fs::symlink_metadata(&source_root_path) {
        Ok(_) => SourceRoot::new(&source_root_path).map_err(|source| LoadGluonError::Evaluation {
            path: source_root_path.clone(),
            source,
        })?,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(source) => {
            return Err(LoadGluonError::Enumerate {
                path: source_root_path,
                source,
            });
        }
    };
    match entry {
        Entry::File => {
            let relative_path = PathBuf::from(format!("{domain}.glu"));
            let path = resolve.file(domain, "glu");
            let metadata = match fs::symlink_metadata(&path) {
                Ok(metadata) => metadata,
                Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
                Err(source) => return Err(LoadGluonError::Enumerate { path, source }),
            };
            require_regular_fragment(&path, &metadata)?;
            if remaining == 0 {
                return Err(LoadGluonError::FragmentLimit {
                    limit: MAX_GLUON_FRAGMENTS,
                });
            }
            verify_source_root(&source_root_path, &source_root)?;
            Ok(vec![GluonPath {
                logical_name: domain.to_owned(),
                source_root_path,
                source_root,
                relative_path,
                path,
                collection: None,
            }])
        }
        Entry::Directory => {
            let relative_dir = PathBuf::from(format!("{domain}.d"));
            let dir = source_root_path.join(&relative_dir);
            let metadata = match fs::symlink_metadata(&dir) {
                Ok(metadata) => metadata,
                Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Vec::new()),
                Err(source) => return Err(LoadGluonError::Enumerate { path: dir, source }),
            };
            if !metadata.file_type().is_dir() {
                return Err(invalid_entry(&dir, "Gluon fragment collection is not a real directory"));
            }
            let directory = FragmentDirectory::open(&dir).map_err(|source| LoadGluonError::Enumerate {
                path: dir.clone(),
                source,
            })?;
            let opened_metadata = directory.file.metadata().map_err(|source| LoadGluonError::Enumerate {
                path: dir.clone(),
                source,
            })?;
            let collection = CollectionIdentity {
                path: dir.clone(),
                identity: FileSnapshot::from_metadata(&metadata),
            };
            if !opened_metadata.file_type().is_dir()
                || FileSnapshot::from_metadata(&opened_metadata) != collection.identity
            {
                return Err(invalid_entry(
                    &dir,
                    "Gluon fragment collection changed while its descriptor was being opened",
                ));
            }
            let entries = match directory.entry_names(MAX_GLUON_DIRECTORY_ENTRIES).map_err(|source| {
                LoadGluonError::Enumerate {
                    path: dir.clone(),
                    source,
                }
            })? {
                BoundedDirectoryEntries::Complete(entries) => entries,
                BoundedDirectoryEntries::LimitExceeded => {
                    return Err(LoadGluonError::DirectoryEntryLimit {
                        path: dir,
                        limit: MAX_GLUON_DIRECTORY_ENTRIES,
                    });
                }
            };
            let mut paths = Vec::new();
            for name in entries {
                let path = dir.join(&name);
                if Path::new(&name).extension() != Some(OsStr::new("glu")) {
                    continue;
                }
                let entry_metadata = directory
                    .metadata_at(&name)
                    .map_err(|source| LoadGluonError::Enumerate {
                        path: path.clone(),
                        source,
                    })?;
                if !entry_metadata.file_type().is_file() {
                    return Err(invalid_entry(
                        &path,
                        "matching Gluon fragment is not a real regular file",
                    ));
                }
                let logical_name = path
                    .file_stem()
                    .and_then(|name| name.to_str())
                    .ok_or_else(|| LoadGluonError::Enumerate {
                        path: dir.clone(),
                        source: io::Error::new(io::ErrorKind::InvalidData, "Gluon fragment name is not UTF-8"),
                    })?
                    .to_owned();
                if !is_safe_fragment_name(&logical_name) {
                    return Err(invalid_entry(
                        &path,
                        "Gluon fragment name is not a safe normalized component",
                    ));
                }
                if paths.len() == remaining {
                    return Err(LoadGluonError::FragmentLimit {
                        limit: MAX_GLUON_FRAGMENTS,
                    });
                }
                let relative_path = relative_dir.join(&name);
                paths.push(GluonPath {
                    logical_name,
                    source_root_path: source_root_path.clone(),
                    source_root: source_root.clone(),
                    relative_path,
                    path,
                    collection: Some(collection.clone()),
                });
            }
            paths.sort_by(|left, right| left.logical_name.cmp(&right.logical_name));
            verify_collection(Some(&collection))?;
            verify_source_root(&source_root_path, &source_root)?;
            Ok(paths)
        }
    }
}

fn verify_source_root(path: &Path, expected: &SourceRoot) -> Result<(), LoadGluonError> {
    let current = SourceRoot::new(path).map_err(|source| LoadGluonError::Evaluation {
        path: path.to_owned(),
        source,
    })?;
    if &current == expected {
        Ok(())
    } else {
        Err(LoadGluonError::Enumerate {
            path: path.to_owned(),
            source: io::Error::new(
                io::ErrorKind::PermissionDenied,
                "Gluon source root changed while fragments were being loaded",
            ),
        })
    }
}

fn verify_collection(collection: Option<&CollectionIdentity>) -> Result<(), LoadGluonError> {
    let Some(collection) = collection else {
        return Ok(());
    };
    let metadata = fs::symlink_metadata(&collection.path).map_err(|source| LoadGluonError::Enumerate {
        path: collection.path.clone(),
        source,
    })?;
    if metadata.file_type().is_dir() && FileSnapshot::from_metadata(&metadata) == collection.identity {
        Ok(())
    } else {
        Err(LoadGluonError::Enumerate {
            path: collection.path.clone(),
            source: io::Error::new(
                io::ErrorKind::PermissionDenied,
                "Gluon fragment collection changed while fragments were being loaded",
            ),
        })
    }
}

fn require_regular_fragment(path: &Path, metadata: &Metadata) -> Result<(), LoadGluonError> {
    if metadata.file_type().is_file() {
        Ok(())
    } else {
        Err(invalid_entry(
            path,
            "matching Gluon fragment is not a real regular file",
        ))
    }
}

fn invalid_entry(path: &Path, message: &'static str) -> LoadGluonError {
    LoadGluonError::Enumerate {
        path: path.to_owned(),
        source: io::Error::new(io::ErrorKind::InvalidData, message),
    }
}

fn is_safe_fragment_name(name: &str) -> bool {
    if name.is_empty()
        || name.len() > MAX_GLUON_FRAGMENT_NAME_BYTES
        || name.contains('\\')
        || name.chars().any(char::is_control)
    {
        return false;
    }
    let mut components = Path::new(name).components();
    matches!(
        (components.next(), components.next()),
        (Some(Component::Normal(component)), None) if component == OsStr::new(name)
    )
}

#[derive(Debug)]
struct FragmentDirectory {
    path: PathBuf,
    file: fs::File,
    identity: NodeIdentity,
}

impl FragmentDirectory {
    fn open(path: &Path) -> io::Result<Self> {
        let file = fs::OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_CLOEXEC | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_NONBLOCK)
            .open(path)?;
        let metadata = file.metadata()?;
        if !metadata.file_type().is_dir() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "Gluon config path is not a real directory",
            ));
        }
        Ok(Self {
            path: path.to_owned(),
            file,
            identity: NodeIdentity::from_metadata(&metadata),
        })
    }

    fn verify_path(&self) -> io::Result<()> {
        let metadata = fs::symlink_metadata(&self.path)?;
        if metadata.file_type().is_dir() && NodeIdentity::from_metadata(&metadata) == self.identity {
            Ok(())
        } else {
            Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                "Gluon config directory changed while it was being managed",
            ))
        }
    }

    fn entry_names(&self, limit: usize) -> io::Result<BoundedDirectoryEntries> {
        // fdopendir owns and closes its descriptor. Open `.` relative to the
        // held directory instead of duplicating the descriptor: dup would
        // share a directory-stream offset, making a second enumeration start
        // at the previous end position.
        // SAFETY: the base descriptor is valid and the C string is static.
        let descriptor = unsafe {
            libc::openat(
                self.file.as_raw_fd(),
                c".".as_ptr(),
                libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC | libc::O_NOFOLLOW | libc::O_NONBLOCK,
                0,
            )
        };
        if descriptor == -1 {
            return Err(io::Error::last_os_error());
        }
        // SAFETY: descriptor is a fresh duplicate referring to a directory.
        let stream = unsafe { libc::fdopendir(descriptor) };
        if stream.is_null() {
            let error = io::Error::last_os_error();
            // SAFETY: fdopendir failed and therefore did not consume the
            // duplicated descriptor.
            unsafe {
                libc::close(descriptor);
            }
            return Err(error);
        }
        let stream = DirectoryStream(stream);
        let mut names = Vec::new();
        loop {
            // POSIX distinguishes end-of-directory from failure through
            // errno. This stream is private to this call.
            // SAFETY: Linux exposes thread-local errno through this pointer.
            unsafe {
                *libc::__errno_location() = 0;
            }
            // SAFETY: stream remains live and exclusively used until the end
            // of this loop iteration.
            let entry = unsafe { libc::readdir(stream.0) };
            if entry.is_null() {
                // SAFETY: errno is thread-local and was cleared immediately
                // before readdir.
                let errno = unsafe { *libc::__errno_location() };
                if errno == 0 {
                    break;
                }
                return Err(io::Error::from_raw_os_error(errno));
            }
            // SAFETY: readdir returned a dirent whose d_name is NUL-terminated
            // and remains valid until the next operation on this stream.
            let bytes = unsafe { CStr::from_ptr((*entry).d_name.as_ptr()) }.to_bytes();
            if matches!(bytes, b"." | b"..") {
                continue;
            }
            if names.len() == limit {
                return Ok(BoundedDirectoryEntries::LimitExceeded);
            }
            names.push(OsString::from_vec(bytes.to_vec()));
        }
        Ok(BoundedDirectoryEntries::Complete(names))
    }

    fn metadata_at(&self, name: &OsStr) -> io::Result<Metadata> {
        self.open_at(name, libc::O_PATH | libc::O_CLOEXEC | libc::O_NOFOLLOW, 0)?
            .metadata()
    }

    fn open_at(&self, name: &OsStr, flags: i32, mode: libc::mode_t) -> io::Result<fs::File> {
        let diagnostic_path = self.display_path(name);
        let name = c_name(name)?;
        // SAFETY: name is NUL-terminated, the directory descriptor remains
        // owned by self, and a successful openat returns a fresh descriptor.
        let descriptor = unsafe { libc::openat(self.file.as_raw_fd(), name.as_ptr(), flags, mode) };
        if descriptor == -1 {
            return Err(io::Error::last_os_error());
        }
        // SAFETY: openat returned a fresh owned descriptor.
        let descriptor = unsafe { OwnedFd::from_raw_fd(descriptor) };
        Ok(fs::File::from_parts(descriptor.into(), diagnostic_path))
    }

    fn rename(&self, from: &OsStr, to: &OsStr, no_replace: bool) -> io::Result<()> {
        let from = c_name(from)?;
        let to = c_name(to)?;
        let result = if no_replace {
            // Cast targets Linux (glibc and musl). Invoke renameat2 directly
            // so a concurrently-created authored target is never replaced.
            // SAFETY: both names are NUL-terminated and both directory FDs
            // remain valid for the duration of the syscall.
            unsafe {
                libc::syscall(
                    libc::SYS_renameat2,
                    self.file.as_raw_fd(),
                    from.as_ptr(),
                    self.file.as_raw_fd(),
                    to.as_ptr(),
                    1_u32, // RENAME_NOREPLACE
                )
            }
        } else {
            // SAFETY: both names are NUL-terminated and both directory FDs
            // remain valid for the duration of the call.
            unsafe {
                libc::c_long::from(libc::renameat(
                    self.file.as_raw_fd(),
                    from.as_ptr(),
                    self.file.as_raw_fd(),
                    to.as_ptr(),
                ))
            }
        };
        if result == -1 {
            Err(io::Error::last_os_error())
        } else {
            Ok(())
        }
    }

    fn unlink(&self, name: &OsStr) -> io::Result<()> {
        let name = c_name(name)?;
        // SAFETY: name is NUL-terminated and the directory descriptor remains
        // valid for the duration of unlinkat.
        let result = unsafe { libc::unlinkat(self.file.as_raw_fd(), name.as_ptr(), 0) };
        if result == -1 {
            Err(io::Error::last_os_error())
        } else {
            Ok(())
        }
    }

    fn sync(&self) -> io::Result<()> {
        self.file.sync_all()
    }

    fn display_path(&self, name: &OsStr) -> PathBuf {
        self.path.join(name)
    }
}

enum BoundedDirectoryEntries {
    Complete(Vec<OsString>),
    LimitExceeded,
}

struct DirectoryStream(*mut libc::DIR);

impl Drop for DirectoryStream {
    fn drop(&mut self) {
        // SAFETY: fdopendir returned this stream and it is closed exactly once
        // here. closedir also closes the duplicate descriptor it owns.
        unsafe {
            libc::closedir(self.0);
        }
    }
}

fn c_name(name: &OsStr) -> io::Result<CString> {
    CString::new(name.as_bytes())
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "fragment name contains a NUL byte"))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct NodeIdentity {
    device: u64,
    inode: u64,
}

impl NodeIdentity {
    fn from_metadata(metadata: &Metadata) -> Self {
        Self {
            device: metadata.dev(),
            inode: metadata.ino(),
        }
    }
}

/// Identity plus the kernel-maintained generation data available to an
/// unprivileged writer. Unlike modification time, ctime cannot be restored by
/// `utimensat`, so it detects in-place edits as well as inode replacement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct FileSnapshot {
    node: NodeIdentity,
    size: u64,
    ctime: i64,
    ctime_nsec: i64,
}

impl FileSnapshot {
    fn from_metadata(metadata: &Metadata) -> Self {
        Self {
            node: NodeIdentity::from_metadata(metadata),
            size: metadata.size(),
            ctime: metadata.ctime(),
            ctime_nsec: metadata.ctime_nsec(),
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct ExistingFragment {
    identity: FileSnapshot,
    generated: bool,
}

fn inspect_existing_fragment(
    directory: &FragmentDirectory,
    name: &OsStr,
    limit: usize,
) -> io::Result<Option<ExistingFragment>> {
    let mut file = match directory.open_at(
        name,
        libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW | libc::O_NONBLOCK | libc::O_NOCTTY,
        0,
    ) {
        Ok(file) => file,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    let metadata = file.metadata()?;
    if !metadata.file_type().is_file() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "managed Gluon fragment is not a real regular file",
        ));
    }
    if metadata.len() > u64::try_from(limit).unwrap_or(u64::MAX) {
        return Err(fragment_too_large(metadata.len(), limit));
    }

    let mut bytes = Vec::with_capacity(usize::try_from(metadata.len()).unwrap_or(limit).min(limit));
    io::Read::by_ref(&mut file)
        .take(u64::try_from(limit).unwrap_or(u64::MAX).saturating_add(1))
        .read_to_end(&mut bytes)?;
    if bytes.len() > limit {
        return Err(fragment_too_large(
            u64::try_from(bytes.len()).unwrap_or(u64::MAX),
            limit,
        ));
    }
    let final_metadata = file.metadata()?;
    let initial = FileSnapshot::from_metadata(&metadata);
    let final_snapshot = FileSnapshot::from_metadata(&final_metadata);
    if initial != final_snapshot {
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "managed Gluon fragment changed while its marker was being read",
        ));
    }
    Ok(Some(ExistingFragment {
        identity: final_snapshot,
        generated: bytes.starts_with(GENERATED_GLUON_MARKER.as_bytes()),
    }))
}

fn fragment_too_large(size: u64, limit: usize) -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        format!("managed Gluon fragment is {size} bytes; limit is {limit} bytes"),
    )
}

fn require_same_generated_fragment(
    directory: &FragmentDirectory,
    name: &OsStr,
    expected: FileSnapshot,
) -> io::Result<()> {
    match inspect_existing_fragment(directory, name, MAX_GENERATED_GLUON_BYTES)? {
        Some(current) if current.generated && current.identity == expected => Ok(()),
        _ => Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "managed Gluon fragment changed after generated-marker verification",
        )),
    }
}

#[derive(Debug, Clone, Copy)]
enum ExpectedTarget {
    Missing,
    Generated(FileSnapshot),
}

fn atomic_write(
    directory: &FragmentDirectory,
    file_name: &OsStr,
    path: &Path,
    bytes: &[u8],
    expected: ExpectedTarget,
) -> Result<(), SaveGluonError> {
    atomic_write_with_hook(directory, file_name, path, bytes, expected, |_| {})
}

fn atomic_write_with_hook(
    directory: &FragmentDirectory,
    file_name: &OsStr,
    path: &Path,
    bytes: &[u8],
    expected: ExpectedTarget,
    before_commit: impl FnOnce(&Path),
) -> Result<(), SaveGluonError> {
    directory
        .verify_path()
        .map_err(|source| SaveGluonError::CreateTemporary {
            path: directory.path.clone(),
            source,
        })?;
    let mut temporary = None;
    for _ in 0..TEMPORARY_CREATE_ATTEMPTS {
        let random = random_hex().map_err(|source| SaveGluonError::CreateTemporary {
            path: directory.path.clone(),
            source,
        })?;
        let candidate = OsString::from(format!("{TEMPORARY_PREFIX}{random}"));
        match directory.open_at(
            &candidate,
            libc::O_WRONLY | libc::O_CREAT | libc::O_EXCL | libc::O_CLOEXEC | libc::O_NOFOLLOW,
            // Preserve the previous OpenOptions default: the process umask
            // derives the final managed-fragment mode from 0o666.
            0o666,
        ) {
            Ok(file) => {
                temporary = Some((candidate, file));
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
            Err(source) => {
                return Err(SaveGluonError::CreateTemporary {
                    path: directory.display_path(&candidate),
                    source,
                });
            }
        }
    }
    let (temporary_name, mut file) = temporary.ok_or_else(|| SaveGluonError::CreateTemporary {
        path: directory.path.clone(),
        source: io::Error::new(
            io::ErrorKind::AlreadyExists,
            "unable to allocate a temporary fragment name",
        ),
    })?;
    let temporary_path = directory.display_path(&temporary_name);
    let mut guard = TemporaryGuard {
        directory,
        name: Some(temporary_name.clone()),
    };
    let result = (|| {
        file.write_all(bytes).map_err(|source| SaveGluonError::WriteTemporary {
            path: temporary_path.clone(),
            source,
        })?;
        file.sync_all().map_err(|source| SaveGluonError::SyncTemporary {
            path: temporary_path.clone(),
            source,
        })?;
        drop(file);
        before_commit(&temporary_path);
        directory.verify_path().map_err(|source| SaveGluonError::ReadExisting {
            path: path.to_owned(),
            source,
        })?;
        let no_replace = match expected {
            ExpectedTarget::Missing => true,
            ExpectedTarget::Generated(identity) => {
                require_same_generated_fragment(directory, file_name, identity).map_err(|source| {
                    SaveGluonError::ReadExisting {
                        path: path.to_owned(),
                        source,
                    }
                })?;
                false
            }
        };
        directory
            .rename(&temporary_name, file_name, no_replace)
            .map_err(|source| SaveGluonError::Rename {
                from: temporary_path.clone(),
                to: path.to_owned(),
                source,
            })?;
        guard.name = None;
        directory.sync().map_err(|source| SaveGluonError::SyncDirectory {
            path: directory.path.clone(),
            source,
        })?;
        directory.verify_path().map_err(|source| SaveGluonError::SyncDirectory {
            path: directory.path.clone(),
            source,
        })
    })();

    match result {
        Ok(()) => Ok(()),
        Err(error) => match guard.cleanup() {
            Ok(()) => Err(error),
            Err(source) => Err(SaveGluonError::CleanupTemporary {
                path: temporary_path,
                source,
            }),
        },
    }
}

fn random_hex() -> io::Result<String> {
    let mut bytes = [0_u8; TEMPORARY_RANDOM_BYTES];
    let mut filled = 0;
    while filled < bytes.len() {
        // SAFETY: the pointer addresses the remaining initialized byte array,
        // and getrandom writes at most the supplied length.
        let result = unsafe { libc::getrandom(bytes[filled..].as_mut_ptr().cast(), bytes.len() - filled, 0) };
        if result == -1 {
            let error = io::Error::last_os_error();
            if error.kind() == io::ErrorKind::Interrupted {
                continue;
            }
            return Err(error);
        }
        if result == 0 {
            return Err(io::Error::new(
                io::ErrorKind::UnexpectedEof,
                "getrandom returned no temporary-name entropy",
            ));
        }
        filled += usize::try_from(result).expect("getrandom returned a non-negative byte count");
    }
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(char::from(HEX[usize::from(byte >> 4)]));
        encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    Ok(encoded)
}

struct TemporaryGuard<'a> {
    directory: &'a FragmentDirectory,
    name: Option<OsString>,
}

impl TemporaryGuard<'_> {
    fn cleanup(&mut self) -> io::Result<()> {
        let Some(name) = self.name.take() else {
            return Ok(());
        };
        match self.directory.unlink(&name) {
            Ok(()) => self.directory.sync(),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error),
        }
    }
}

impl Drop for TemporaryGuard<'_> {
    fn drop(&mut self) {
        let _ = self.cleanup();
    }
}

#[cfg(test)]
mod tests {
    use std::{os::unix::fs::symlink, sync::mpsc, thread, time::Duration};

    use super::*;
    use crate::Scope;
    use gluon_config::{DiagnosticCategory, LimitKind, Limits};

    impl Config for String {
        fn domain() -> String {
            "dummy".to_owned()
        }
    }

    struct StringCodec;

    impl GluonCodec for StringCodec {
        type Config = String;

        fn decode(
            &self,
            evaluator: &Evaluator,
            source: &Source,
        ) -> Result<DecodedGluon<Self::Config>, GluonCodecError> {
            let evaluation = evaluator.evaluate::<String>(source)?;
            if evaluation.value == "reject" {
                return Err(GluonCodecError::conversion(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "rejected dummy value",
                )));
            }
            Ok(evaluation.into())
        }

        fn encode(&self, config: &Self::Config) -> Result<String, GluonCodecError> {
            Ok(format!("\"{config}\""))
        }
    }

    struct RawCodec;

    impl GluonCodec for RawCodec {
        type Config = String;

        fn decode(
            &self,
            evaluator: &Evaluator,
            source: &Source,
        ) -> Result<DecodedGluon<Self::Config>, GluonCodecError> {
            Ok(evaluator.evaluate::<String>(source)?.into())
        }

        fn encode(&self, config: &Self::Config) -> Result<String, GluonCodecError> {
            Ok(config.clone())
        }
    }

    fn write(path: impl AsRef<Path>, content: &str) {
        let path = path.as_ref();
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    fn layered_manager(root: &Path, user: &Path, program: &str) -> Manager {
        Manager {
            scope: Scope::User {
                root: root.to_owned(),
                config: user.to_owned(),
                program: program.to_owned(),
            },
        }
    }

    fn mkfifo(path: &Path) {
        let path = CString::new(path.as_os_str().as_bytes()).unwrap();
        // SAFETY: path is a valid NUL-terminated pathname and mode contains
        // only ordinary permission bits.
        let result = unsafe { libc::mkfifo(path.as_ptr(), 0o600) };
        assert_eq!(result, 0, "mkfifo failed: {}", io::Error::last_os_error());
    }

    fn finish_nonblocking<T: Send + 'static>(fifo: &Path, operation: impl FnOnce() -> T + Send + 'static) -> T {
        let (sender, receiver) = mpsc::channel();
        let worker = thread::spawn(move || {
            let _ = sender.send(operation());
        });
        let result = match receiver.recv_timeout(Duration::from_secs(1)) {
            Ok(result) => result,
            Err(timeout) => {
                // Rescue a regressed blocking FIFO open so this test fails
                // instead of leaving the test process stuck forever.
                let writer = fs::OpenOptions::new()
                    .write(true)
                    .custom_flags(libc::O_NONBLOCK)
                    .open(fifo)
                    .unwrap();
                drop(writer);
                let _ = receiver.recv_timeout(Duration::from_secs(1));
                worker.join().unwrap();
                panic!("managed fragment operation blocked on a FIFO: {timeout}");
            }
        };
        worker.join().unwrap();
        result
    }

    fn generated_literal_with_total_size(total: usize) -> String {
        let literal_len = total.checked_sub(GENERATED_GLUON_MARKER.len()).unwrap();
        assert!(literal_len > 0);
        let mut literal = "x".repeat(literal_len);
        literal.replace_range(literal_len - 1.., "\n");
        literal
    }

    fn temporary_fragment_names(directory: &Path) -> Vec<OsString> {
        let mut names = fs::read_dir(directory)
            .unwrap()
            .filter_map(Result::ok)
            .map(|entry| entry.file_name())
            .filter(|name| name.as_bytes().starts_with(TEMPORARY_PREFIX.as_bytes()))
            .collect::<Vec<_>>();
        names.sort();
        names
    }

    fn assert_no_temporary_fragments(directory: &Path) {
        assert_eq!(temporary_fragment_names(directory), Vec::<OsString>::new());
    }

    #[test]
    fn gluon_fragments_have_deterministic_order_and_explicit_precedence() {
        let temporary = tempfile::tempdir().unwrap();
        let root = temporary.path().join("root");
        let user = temporary.path().join("user");
        let program = "config-gluon-precedence";
        let vendor = root.join("usr/share").join(program);
        let admin = root.join("etc").join(program);
        let user_program = user.join(program);

        write(vendor.join("dummy.glu"), "\"vendor-base\"");
        write(vendor.join("dummy.d/z.glu"), "\"vendor-z\"");
        write(vendor.join("dummy.d/a.glu"), "\"vendor-a\"");
        write(vendor.join("dummy.d/shared.glu"), "\"vendor-shared\"");
        write(admin.join("dummy.glu"), "\"admin-base\"");
        write(admin.join("dummy.d/shared.glu"), "\"admin-shared\"");
        write(user_program.join("dummy.glu"), "\"user-base\"");
        write(user_program.join("dummy.d/shared.glu"), "\"user-shared\"");

        let loaded = layered_manager(&root, &user, program)
            .load_gluon(&Evaluator::default(), &StringCodec)
            .unwrap();
        assert_eq!(
            loaded
                .iter()
                .map(|fragment| (fragment.logical_name.as_str(), fragment.value.as_str()))
                .collect::<Vec<_>>(),
            [
                ("a", "vendor-a"),
                ("dummy", "user-base"),
                ("shared", "user-shared"),
                ("z", "vendor-z"),
            ]
        );
    }

    #[test]
    fn authored_fragment_reads_accept_n_bytes_and_reject_n_plus_one() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let fragment = temporary.path().join("dummy.d/bounded.glu");
        let mut limits = Limits::default();
        limits.max_source_bytes = 6;
        let evaluator = Evaluator::new(limits);

        write(&fragment, "\"1234\"");
        let loaded = manager.load_gluon(&evaluator, &StringCodec).unwrap();
        assert_eq!(loaded[0].value, "1234");

        write(&fragment, "\"12345\"");
        let error = manager.load_gluon(&evaluator, &StringCodec).unwrap_err();
        let LoadGluonError::Evaluation { path, source } = error else {
            panic!("expected source-size evaluation error");
        };
        assert_eq!(path, fragment);
        assert_eq!(source.category, DiagnosticCategory::Limit);
        assert_eq!(source.limit, Some(LimitKind::SourceSize));
    }

    #[test]
    fn fragment_count_accepts_n_and_rejects_n_plus_one_before_evaluation() {
        let temporary = tempfile::tempdir().unwrap();
        let directory = temporary.path().join("dummy.d");
        fs::create_dir(&directory).unwrap();
        let manager = Manager::custom(temporary.path());
        for index in 0..MAX_GLUON_FRAGMENTS {
            fs::write(directory.join(format!("fragment-{index:04}.glu")), "not evaluated").unwrap();
        }

        assert_eq!(
            collect_gluon_paths(&manager.scope, "dummy").unwrap().len(),
            MAX_GLUON_FRAGMENTS
        );

        fs::write(directory.join("overflow.glu"), "not evaluated").unwrap();
        let error = collect_gluon_paths(&manager.scope, "dummy").unwrap_err();
        assert!(matches!(
            error,
            LoadGluonError::FragmentLimit {
                limit: MAX_GLUON_FRAGMENTS
            }
        ));
    }

    #[test]
    fn directory_scan_accepts_n_ignored_entries_and_rejects_n_plus_one() {
        let temporary = tempfile::tempdir().unwrap();
        let directory = temporary.path().join("dummy.d");
        fs::create_dir(&directory).unwrap();
        let manager = Manager::custom(temporary.path());
        for index in 0..MAX_GLUON_DIRECTORY_ENTRIES {
            fs::write(directory.join(format!("ignored-{index:04}.txt")), "ignored").unwrap();
        }

        assert!(collect_gluon_paths(&manager.scope, "dummy").unwrap().is_empty());

        fs::write(directory.join("overflow.txt"), "ignored").unwrap();
        let error = collect_gluon_paths(&manager.scope, "dummy").unwrap_err();
        assert!(matches!(
            error,
            LoadGluonError::DirectoryEntryLimit {
                path,
                limit: MAX_GLUON_DIRECTORY_ENTRIES
            } if path == directory
        ));
    }

    #[test]
    fn matching_symlinks_are_rejected_instead_of_followed() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let outside = temporary.path().join("outside.glu");
        let linked = temporary.path().join("dummy.d/linked.glu");
        write(&outside, "\"outside\"");
        fs::create_dir_all(linked.parent().unwrap()).unwrap();
        symlink(&outside, &linked).unwrap();

        let error = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { path, .. } if path == linked));
    }

    #[test]
    fn a_symlinked_fragment_collection_is_rejected() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let real = temporary.path().join("real-fragments");
        let linked = temporary.path().join("dummy.d");
        write(real.join("value.glu"), "\"outside\"");
        symlink(&real, &linked).unwrap();

        let error = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { path, .. } if path == linked));
    }

    #[test]
    fn an_open_collection_descriptor_cannot_be_redirected() {
        let temporary = tempfile::tempdir().unwrap();
        let collection = temporary.path().join("dummy.d");
        let held = temporary.path().join("held");
        let outside = temporary.path().join("outside");
        write(collection.join("inside.txt"), "inside");
        write(outside.join("outside.txt"), "outside");
        let directory = FragmentDirectory::open(&collection).unwrap();

        fs::rename(&collection, &held).unwrap();
        symlink(&outside, &collection).unwrap();
        let BoundedDirectoryEntries::Complete(names) = directory.entry_names(8).unwrap() else {
            panic!("one held entry cannot exceed the scan limit");
        };
        assert_eq!(names, [OsString::from("inside.txt")]);

        let BoundedDirectoryEntries::Complete(repeated) = directory.entry_names(8).unwrap() else {
            panic!("a repeated held-directory scan cannot exceed the limit");
        };
        assert_eq!(repeated, [OsString::from("inside.txt")]);
    }

    #[test]
    fn matching_fifos_are_rejected_without_waiting_for_a_writer() {
        let temporary = tempfile::tempdir().unwrap();
        let fifo = temporary.path().join("dummy.d/blocking.glu");
        fs::create_dir_all(fifo.parent().unwrap()).unwrap();
        mkfifo(&fifo);
        let manager = Manager::custom(temporary.path());
        let fifo_for_timeout = fifo.clone();

        let result = finish_nonblocking(&fifo_for_timeout, move || {
            manager.load_gluon(&Evaluator::default(), &StringCodec)
        });

        assert!(matches!(result, Err(LoadGluonError::Enumerate { path, .. }) if path == fifo));
    }

    #[test]
    fn replacing_a_layer_root_during_load_fails_closed() {
        let temporary = tempfile::tempdir().unwrap();
        let configured = temporary.path().join("configured");
        let held = temporary.path().join("held");
        write(configured.join("dummy.d/value.glu"), "\"original\"");
        let manager = Manager::custom(&configured);

        let error = manager
            .load_gluon_with_hook(&Evaluator::default(), &StringCodec, || {
                fs::rename(&configured, &held).unwrap();
                write(configured.join("dummy.d/value.glu"), "\"replacement\"");
            })
            .unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { source, .. }
            if source.to_string().contains("source root changed")));
    }

    #[test]
    fn replacing_an_enumerated_fragment_with_a_symlink_fails_closed() {
        let temporary = tempfile::tempdir().unwrap();
        let fragment = temporary.path().join("dummy.d/value.glu");
        let outside = temporary.path().join("outside.glu");
        write(&fragment, "\"original\"");
        write(&outside, "\"replacement\"");
        let manager = Manager::custom(temporary.path());

        let error = manager
            .load_gluon_with_hook(&Evaluator::default(), &StringCodec, || {
                fs::remove_file(&fragment).unwrap();
                symlink(&outside, &fragment).unwrap();
            })
            .unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { path, source }
            if path == fragment.parent().unwrap()
                && source.to_string().contains("fragment collection changed")));
    }

    #[test]
    fn replacing_an_enumerated_collection_fails_closed() {
        let temporary = tempfile::tempdir().unwrap();
        let collection = temporary.path().join("dummy.d");
        let held = temporary.path().join("held");
        write(collection.join("value.glu"), "\"original\"");
        let manager = Manager::custom(temporary.path());

        let error = manager
            .load_gluon_with_hook(&Evaluator::default(), &StringCodec, || {
                fs::rename(&collection, &held).unwrap();
                write(collection.join("value.glu"), "\"replacement\"");
            })
            .unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { source, .. }
            if source.to_string().contains("fragment collection changed")));
    }

    #[test]
    fn changing_an_enumerated_collection_fails_closed() {
        let temporary = tempfile::tempdir().unwrap();
        let collection = temporary.path().join("dummy.d");
        write(collection.join("value.glu"), "\"original\"");
        let manager = Manager::custom(temporary.path());

        let error = manager
            .load_gluon_with_hook(&Evaluator::default(), &StringCodec, || {
                fs::write(collection.join("late.glu"), "\"late\"").unwrap();
            })
            .unwrap_err();

        assert!(matches!(error, LoadGluonError::Enumerate { source, .. }
            if source.to_string().contains("fragment collection changed")));
    }

    #[test]
    fn malformed_and_conversion_errors_are_visible_with_their_paths() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let malformed = temporary.path().join("dummy.d/malformed.glu");
        write(&malformed, "let value = in value");

        let error = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap_err();
        let LoadGluonError::Evaluation { path, source } = error else {
            panic!("expected evaluation error");
        };
        assert_eq!(path, malformed);
        assert_eq!(source.source_name.as_deref(), Some("dummy.d/malformed.glu"));
        assert!(source.span.is_some());

        fs::remove_file(&path).unwrap();
        let rejected = temporary.path().join("dummy.d/rejected.glu");
        write(&rejected, "\"reject\"");
        let error = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap_err();
        let LoadGluonError::Conversion { path, source } = error else {
            panic!("expected conversion error");
        };
        assert_eq!(path, rejected);
        assert!(source.to_string().contains("rejected dummy value"));
    }

    #[test]
    fn load_gluon_never_falls_back_to_yaml_or_kdl() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        write(temporary.path().join("dummy.yaml"), "not: valid: yaml");
        write(temporary.path().join("dummy.kdl"), "not valid kdl {");
        write(temporary.path().join("dummy.d/fragment.yaml"), "\"yaml\"");
        write(temporary.path().join("dummy.d/fragment.kdl"), "\"kdl\"");

        let loaded = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap();
        assert!(loaded.is_empty());

        write(temporary.path().join("dummy.d/fragment.glu"), "\"gluon\"");
        let loaded = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].value, "gluon");
    }

    #[test]
    fn fragment_relative_imports_are_contained_to_the_layer_root() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        write(temporary.path().join("dummy.d/modules/value.glu"), "\"imported\"");
        write(
            temporary.path().join("dummy.d/fragment.glu"),
            "import! \"modules/value.glu\"",
        );

        let loaded = manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap();

        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].value, "imported");
        assert_eq!(
            loaded[0]
                .fingerprint
                .imported_modules
                .iter()
                .map(|module| module.logical_name.as_str())
                .collect::<Vec<_>>(),
            ["dummy.d/modules/value.glu"]
        );
    }

    #[test]
    fn save_and_delete_gluon_use_a_generated_atomic_fragment() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let value = "saved".to_owned();
        let path = manager.save_gluon("example", &value, &StringCodec).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, format!("{GENERATED_GLUON_MARKER}\"saved\"\n"));
        manager
            .save_gluon("example", &"updated".to_owned(), &StringCodec)
            .unwrap();
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            format!("{GENERATED_GLUON_MARKER}\"updated\"\n")
        );
        assert_eq!(
            manager.load_gluon(&Evaluator::default(), &StringCodec).unwrap()[0].value,
            "updated"
        );
        assert_no_temporary_fragments(path.parent().unwrap());

        write(path.with_extension("yaml"), "legacy: true");
        write(path.with_extension("kdl"), "legacy #true");
        manager.delete_gluon::<String>("example").unwrap();
        assert!(!path.exists());
        assert!(path.with_extension("yaml").exists());
        assert!(path.with_extension("kdl").exists());
        manager.delete_gluon::<String>("example").unwrap();
    }

    #[test]
    fn save_and_delete_reject_traversal_and_non_normal_names() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let value = "value".to_owned();

        for name in [
            "",
            ".",
            "..",
            "../escape",
            "nested/name",
            r"nested\name",
            "/absolute",
            "name/",
            "./name",
            "name/../other",
            "line\nbreak",
        ] {
            assert!(matches!(
                manager.save_gluon(name, &value, &StringCodec),
                Err(SaveGluonError::InvalidName { .. })
            ));
            assert!(matches!(
                manager.delete_gluon::<String>(name),
                Err(DeleteGluonError::InvalidName { .. })
            ));
        }
        let accepted = "x".repeat(MAX_GLUON_FRAGMENT_NAME_BYTES);
        let rejected = "x".repeat(MAX_GLUON_FRAGMENT_NAME_BYTES + 1);
        let accepted_path = manager.save_gluon(&accepted, &value, &StringCodec).unwrap();
        assert_eq!(accepted_path.file_name().unwrap().as_bytes().len(), 255);
        assert!(matches!(
            manager.save_gluon(&rejected, &value, &StringCodec),
            Err(SaveGluonError::InvalidName { .. })
        ));
        manager.delete_gluon::<String>(&accepted).unwrap();
        assert!(!temporary.path().join("escape.glu").exists());
    }

    #[test]
    fn generated_output_accepts_n_bytes_and_rejects_n_plus_one() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let accepted = generated_literal_with_total_size(MAX_GENERATED_GLUON_BYTES);
        let rejected = generated_literal_with_total_size(MAX_GENERATED_GLUON_BYTES + 1);

        let path = manager.save_gluon("bounded", &accepted, &RawCodec).unwrap();
        assert_eq!(fs::metadata(path).unwrap().len(), MAX_GENERATED_GLUON_BYTES as u64);
        let error = manager.save_gluon("overflow", &rejected, &RawCodec).unwrap_err();
        assert!(matches!(
            error,
            SaveGluonError::GeneratedTooLarge {
                size,
                limit: MAX_GENERATED_GLUON_BYTES
            } if size == MAX_GENERATED_GLUON_BYTES + 1
        ));
    }

    #[test]
    fn existing_fragment_inspection_accepts_n_bytes_and_rejects_n_plus_one() {
        let temporary = tempfile::tempdir().unwrap();
        let directory = FragmentDirectory::open(temporary.path()).unwrap();
        let name = OsStr::new("bounded.glu");
        let path = temporary.path().join(name);
        let limit = 64;
        let mut content = GENERATED_GLUON_MARKER.as_bytes().to_vec();
        content.resize(limit, b'x');
        fs::write(&path, &content).unwrap();

        assert!(
            inspect_existing_fragment(&directory, name, limit)
                .unwrap()
                .unwrap()
                .generated
        );

        content.push(b'x');
        fs::write(path, content).unwrap();
        let error = inspect_existing_fragment(&directory, name, limit).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::InvalidData);
        assert!(error.to_string().contains("65 bytes; limit is 64 bytes"));
    }

    #[test]
    fn save_and_delete_never_follow_a_managed_fragment_symlink() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let target = temporary.path().join("dummy.d/linked.glu");
        let outside = temporary.path().join("outside.glu");
        write(&outside, &format!("{GENERATED_GLUON_MARKER}\"outside\"\n"));
        fs::create_dir_all(target.parent().unwrap()).unwrap();
        symlink(&outside, &target).unwrap();

        assert!(matches!(
            manager.save_gluon("linked", &"replacement".to_owned(), &StringCodec),
            Err(SaveGluonError::ReadExisting { .. })
        ));
        assert!(matches!(
            manager.delete_gluon::<String>("linked"),
            Err(DeleteGluonError::ReadExisting { .. })
        ));
        assert_eq!(
            fs::read_to_string(outside).unwrap(),
            format!("{GENERATED_GLUON_MARKER}\"outside\"\n")
        );
        assert!(target.is_symlink());
    }

    #[test]
    fn save_and_delete_reject_a_fifo_without_blocking() {
        let temporary = tempfile::tempdir().unwrap();
        let fifo = temporary.path().join("dummy.d/blocking.glu");
        fs::create_dir_all(fifo.parent().unwrap()).unwrap();
        mkfifo(&fifo);
        let save_manager = Manager::custom(temporary.path());
        let fifo_for_save = fifo.clone();
        let save = finish_nonblocking(&fifo_for_save, move || {
            save_manager.save_gluon("blocking", &"replacement".to_owned(), &StringCodec)
        });
        assert!(matches!(save, Err(SaveGluonError::ReadExisting { .. })));

        let delete_manager = Manager::custom(temporary.path());
        let fifo_for_delete = fifo.clone();
        let delete = finish_nonblocking(&fifo_for_delete, move || {
            delete_manager.delete_gluon::<String>("blocking")
        });
        assert!(matches!(delete, Err(DeleteGluonError::ReadExisting { .. })));
    }

    #[test]
    fn a_failed_atomic_commit_removes_its_unpredictable_staging_file() {
        let temporary = tempfile::tempdir().unwrap();
        let directory = FragmentDirectory::open(temporary.path()).unwrap();
        let name = OsStr::new("target.glu");
        let target = temporary.path().join(name);

        let error = atomic_write_with_hook(
            &directory,
            name,
            &target,
            GENERATED_GLUON_MARKER.as_bytes(),
            ExpectedTarget::Missing,
            |temporary_path| {
                let temporary_name = temporary_path.file_name().unwrap().to_string_lossy();
                let random = temporary_name.strip_prefix(TEMPORARY_PREFIX).unwrap();
                assert_eq!(random.len(), TEMPORARY_RANDOM_BYTES * 2);
                assert!(random.bytes().all(|byte| byte.is_ascii_hexdigit()));
                fs::create_dir(&target).unwrap();
            },
        )
        .unwrap_err();

        assert!(matches!(error, SaveGluonError::Rename { .. }));
        assert!(target.is_dir());
        assert_no_temporary_fragments(temporary.path());
    }

    #[test]
    fn replacing_a_managed_directory_cannot_redirect_an_atomic_save() {
        let temporary = tempfile::tempdir().unwrap();
        let managed = temporary.path().join("managed");
        let held = temporary.path().join("held");
        fs::create_dir(&managed).unwrap();
        let directory = FragmentDirectory::open(&managed).unwrap();
        let name = OsStr::new("target.glu");
        let target = managed.join(name);

        let error = atomic_write_with_hook(
            &directory,
            name,
            &target,
            GENERATED_GLUON_MARKER.as_bytes(),
            ExpectedTarget::Missing,
            |_| {
                fs::rename(&managed, &held).unwrap();
                fs::create_dir(&managed).unwrap();
            },
        )
        .unwrap_err();

        assert!(matches!(error, SaveGluonError::ReadExisting { .. }));
        assert!(fs::read_dir(&managed).unwrap().next().is_none());
        assert!(!held.join(name).exists());
        assert_no_temporary_fragments(&held);
    }

    #[test]
    fn generated_marker_rechecks_fail_closed_when_the_target_is_replaced() {
        let temporary = tempfile::tempdir().unwrap();
        let directory = FragmentDirectory::open(temporary.path()).unwrap();
        let name = OsStr::new("race.glu");
        let target = temporary.path().join(name);
        fs::write(&target, format!("{GENERATED_GLUON_MARKER}\"old\"\n")).unwrap();
        let expected = inspect_existing_fragment(&directory, name, MAX_GENERATED_GLUON_BYTES)
            .unwrap()
            .unwrap()
            .identity;

        let error = atomic_write_with_hook(
            &directory,
            name,
            &target,
            format!("{GENERATED_GLUON_MARKER}\"new\"\n").as_bytes(),
            ExpectedTarget::Generated(expected),
            |_| {
                fs::remove_file(&target).unwrap();
                fs::write(&target, "\"authored replacement\"\n").unwrap();
            },
        )
        .unwrap_err();

        assert!(matches!(error, SaveGluonError::ReadExisting { .. }));
        assert_eq!(fs::read_to_string(&target).unwrap(), "\"authored replacement\"\n");
        assert_no_temporary_fragments(temporary.path());
    }

    #[test]
    fn delete_rechecks_the_generated_inode_before_unlinking() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let target = manager
            .save_gluon("race", &"generated".to_owned(), &StringCodec)
            .unwrap();
        let outside = temporary.path().join("outside.glu");
        fs::write(&outside, "outside").unwrap();

        let error = manager
            .delete_gluon_with_hook::<String>("race", || {
                fs::remove_file(&target).unwrap();
                symlink(&outside, &target).unwrap();
            })
            .unwrap_err();

        assert!(matches!(error, DeleteGluonError::ReadExisting { .. }));
        assert!(target.is_symlink());
        assert_eq!(fs::read_to_string(outside).unwrap(), "outside");
    }

    #[test]
    fn replacing_a_managed_directory_cannot_redirect_delete() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let target = manager
            .save_gluon("race", &"generated".to_owned(), &StringCodec)
            .unwrap();
        let managed = target.parent().unwrap().to_owned();
        let held = temporary.path().join("held");

        let error = manager
            .delete_gluon_with_hook::<String>("race", || {
                fs::rename(&managed, &held).unwrap();
                fs::create_dir(&managed).unwrap();
            })
            .unwrap_err();

        assert!(matches!(error, DeleteGluonError::ReadExisting { .. }));
        assert!(held.join("race.glu").is_file());
        assert!(!managed.join("race.glu").exists());
    }

    #[test]
    fn save_never_overwrites_an_authored_fragment() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let path = temporary.path().join("dummy.d/authored.glu");
        write(&path, "\"user expression\"\n");

        let error = manager
            .save_gluon("authored", &"generated replacement".to_owned(), &StringCodec)
            .unwrap_err();

        assert!(matches!(error, SaveGluonError::AuthoredFragment { path: ref found } if found == &path));
        assert_eq!(fs::read_to_string(path).unwrap(), "\"user expression\"\n");
    }

    #[test]
    fn delete_never_removes_an_authored_fragment() {
        let temporary = tempfile::tempdir().unwrap();
        let manager = Manager::custom(temporary.path());
        let path = temporary.path().join("dummy.d/authored.glu");
        write(&path, "\"user expression\"\n");

        let error = manager.delete_gluon::<String>("authored").unwrap_err();

        assert!(matches!(error, DeleteGluonError::AuthoredFragment { path: ref found } if found == &path));
        assert_eq!(fs::read_to_string(path).unwrap(), "\"user expression\"\n");
    }
}
