-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-userspace-profile-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-userspace-profile-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        kind = "custom",
        spec = {
            required_tools = {},
            environment = {},
            phases = {
                setup = {
                    steps = {}
                },
                build = {
                    steps = {}
                },
                install = {
                    steps = {}
                },
                check = {
                    steps = {}
                },
                workload = {
                    steps = {}
                }
            },
            supported_hooks = {
                setup = true,
                build = true,
                check = true,
                install = true,
                workload = true
            }
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Declarative userspace profile fixture"
            },
            description = {
                kind = "some",
                value = "Shell, core commands, discovery, trust, and archive roles composed as one explicit closure."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "package",
                    value = {
                        name = "bash"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "uutils-coreutils"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "findutils"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "ca-certificates"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "xz"
                    }
                }
            },
            runtime_exclude = {},
            paths = {},
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}