-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "frame-codec",
        version = "2.6.1",
        release = 1,
        homepage = "https://example.invalid/frame-codec",
        license = {
            "BSD-2-Clause"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DBUILD_TESTING=ON",
                            "-DFRAME_CODEC_EXTERNAL_VECTOR_FILE=external-test-vectors.json"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {
                    {
                        path = "/usr/bin/cp",
                        requirement = {
                            kind = "binary",
                            value = "cp"
                        }
                    }
                },
                script = "test ! -e \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && cp --preserve=mode,timestamps -- \"${CAST_SOURCE_DIR}/frame-codec-conformance.json\" \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && test -s \"${CAST_BUILDER_DIR}/external-test-vectors.json\""
            }
        },
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "cp"
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Frame codec checked against an independently locked corpus"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/frame-codec"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Frame codec debugging symbols"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/frame-codec-2.6.1.tar.xz",
            hash = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            rename = {
                kind = "some",
                value = "frame-codec.tar.xz"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "frame-codec"
            }
        },
        {
            kind = "archive",
            url = "https://example.invalid/frame-codec-conformance-2026-07.json",
            hash = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            rename = {
                kind = "some",
                value = "frame-codec-conformance.json"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = false,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}