//! Canonical standalone Gluon encoding for generated system snapshots.

use std::fmt::Write as _;

use super::SYSTEM_ABI_VERSION;
use crate::system_model::spec::{RepositorySourceSpec, SystemSpec};

/// Marker emitted at the start of every normalized Gluon system snapshot.
pub const GENERATED_GLUON_MARKER: &str = "// @generated by cast. DO NOT EDIT.\n";

const SOURCE_FINGERPRINT_PREFIX: &str = "// Authored source fingerprint: ";

const STANDALONE_GLUON_TYPES: &str = r#"type Bool =
    | False
    | True

type Option a =
    | None
    | Some a

type RepositorySourceSpec =
    | DirectIndex { uri : String }
    | RootIndex {
        base_uri : String,
        channel : Option String,
        version : String,
        arch : Option String,
    }

type RepositorySpec = {
    id : String,
    description : Option String,
    source : RepositorySourceSpec,
    priority : Option Int,
    enabled : Option Bool,
}

type SystemSpec = {
    disable_warning : Bool,
    repositories : Array RepositorySpec,
    packages : Array String,
}

"#;

/// Encode a canonical, import-free Gluon value for a generated system
/// snapshot.
///
/// Repositories and packages are sorted before emission, and every optional
/// field remains explicit. The result is normalized state, not authored source.
pub(super) fn encode_generated(spec: &SystemSpec) -> String {
    let mut repositories = spec.repositories.iter().collect::<Vec<_>>();
    repositories.sort_by(|left, right| left.id.cmp(&right.id));
    let mut packages = spec.packages.iter().collect::<Vec<_>>();
    packages.sort();

    let mut output = String::from(GENERATED_GLUON_MARKER);
    writeln!(
        output,
        "// Canonical standalone SystemSpec snapshot (ABI {SYSTEM_ABI_VERSION})."
    )
    .unwrap();
    output.push_str(STANDALONE_GLUON_TYPES);
    output.push_str("{\n");
    writeln!(output, "    disable_warning = {},", gluon_bool(spec.disable_warning)).unwrap();
    output.push_str("    repositories = [\n");
    for repository in repositories {
        output.push_str("        {\n");
        writeln!(output, "            id = {},", gluon_string(&repository.id)).unwrap();
        writeln!(
            output,
            "            description = {},",
            gluon_optional_string(repository.description.as_deref())
        )
        .unwrap();
        encode_repository_source(&mut output, &repository.source);
        writeln!(
            output,
            "            priority = {},",
            gluon_optional_integer(repository.priority)
        )
        .unwrap();
        writeln!(
            output,
            "            enabled = {},",
            gluon_optional_bool(repository.enabled)
        )
        .unwrap();
        output.push_str("        },\n");
    }
    output.push_str("    ],\n");
    output.push_str("    packages = [\n");
    for package in packages {
        writeln!(output, "        {},", gluon_string(package)).unwrap();
    }
    output.push_str("    ],\n");
    output.push_str("}\n");
    output
}

pub(super) fn is_generated(source: &str) -> bool {
    source.starts_with(GENERATED_GLUON_MARKER)
}

pub(super) fn source_fingerprint(source: &str) -> Option<String> {
    source
        .lines()
        .find_map(|line| line.strip_prefix(SOURCE_FINGERPRINT_PREFIX))
        .filter(|fingerprint| {
            fingerprint.len() == 64
                && fingerprint.bytes().all(|byte| byte.is_ascii_hexdigit())
        })
        .map(ToOwned::to_owned)
}

pub(super) fn with_source_fingerprint(generated: &str, source_fingerprint: &str) -> String {
    let generated = generated
        .strip_prefix(GENERATED_GLUON_MARKER)
        .expect("Cast-generated system snapshots always carry the generated marker");
    format!(
        "{GENERATED_GLUON_MARKER}{SOURCE_FINGERPRINT_PREFIX}{source_fingerprint}\n{generated}"
    )
}

fn encode_repository_source(output: &mut String, source: &RepositorySourceSpec) {
    match source {
        RepositorySourceSpec::DirectIndex { uri } => {
            output.push_str("            source = DirectIndex {\n");
            writeln!(output, "                uri = {},", gluon_string(uri)).unwrap();
            output.push_str("            },\n");
        }
        RepositorySourceSpec::RootIndex {
            base_uri,
            channel,
            version,
            arch,
        } => {
            output.push_str("            source = RootIndex {\n");
            writeln!(output, "                base_uri = {},", gluon_string(base_uri)).unwrap();
            writeln!(
                output,
                "                channel = {},",
                gluon_optional_string(channel.as_deref())
            )
            .unwrap();
            writeln!(output, "                version = {},", gluon_string(version)).unwrap();
            writeln!(
                output,
                "                arch = {},",
                gluon_optional_string(arch.as_deref())
            )
            .unwrap();
            output.push_str("            },\n");
        }
    }
}

fn gluon_bool(value: bool) -> &'static str {
    if value { "True" } else { "False" }
}

fn gluon_optional_bool(value: Option<bool>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {}", gluon_bool(value)))
}

fn gluon_optional_integer(value: Option<i64>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {value}"))
}

fn gluon_optional_string(value: Option<&str>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {}", gluon_string(value)))
}

fn gluon_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}
