-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-system-integration-assets-fixture-1.0.0.tar",
            sha256 = "27d04653529db216023599d2f6122f503acb59e0ebe26c5bce351dc970d58113"
        },
    },
}