-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-system-integration-assets-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-system-integration-assets-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "dash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "install -Dm755 integration/cast-system-integration-fixture \"${CAST_INSTALL_ROOT}/usr/libexec/cast-system-integration-fixture\"\ninstall -Dm644 integration/cast-system-integration-fixture.service \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/systemd/system/cast-system-integration-fixture.service\"\ninstall -Dm644 integration/cast-system-integration-fixture.sysusers \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/sysusers.d/cast-system-integration-fixture.conf\"\ninstall -Dm644 integration/cast-system-integration-fixture.tmpfiles \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/tmpfiles.d/cast-system-integration-fixture.conf\"\ninstall -Dm644 integration/70-cast-system-integration-fixture.rules \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/udev/rules.d/70-cast-system-integration-fixture.rules\"\ninstall -Dm644 integration/io.cast.SystemIntegrationFixture.rules \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/polkit-1/rules.d/io.cast.SystemIntegrationFixture.rules\"\ninstall -Dm644 integration/io.cast.SystemIntegrationFixture.policy \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/polkit-1/actions/io.cast.SystemIntegrationFixture.policy\"\ninstall -Dm644 LICENSE \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/licenses/cast-system-integration-assets-fixture/LICENSE\""
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {},
                        script = "\"${CAST_INSTALL_ROOT}/usr/libexec/cast-system-integration-fixture\" --self-test"
                    },
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/systemd-analyze",
                                requirement = {
                                    kind = "binary",
                                    value = "systemd-analyze"
                                }
                            },
                            {
                                path = "/usr/bin/systemd-sysusers",
                                requirement = {
                                    kind = "binary",
                                    value = "systemd-sysusers"
                                }
                            },
                            {
                                path = "/usr/bin/systemd-tmpfiles",
                                requirement = {
                                    kind = "binary",
                                    value = "systemd-tmpfiles"
                                }
                            },
                            {
                                path = "/usr/bin/udevadm",
                                requirement = {
                                    kind = "binary",
                                    value = "udevadm"
                                }
                            },
                            {
                                path = "/usr/bin/xmllint",
                                requirement = {
                                    kind = "binary",
                                    value = "xmllint"
                                }
                            }
                        },
                        script = "SYSTEMD_UNIT_PATH=/usr/lib/systemd/system systemd-analyze --root=\"${CAST_INSTALL_ROOT}\" --recursive-errors=no --man=no --generators=no verify cast-system-integration-fixture.service\nsystemd-sysusers --dry-run --root=\"${CAST_INSTALL_ROOT}\" \"${CAST_INSTALL_ROOT}/usr/lib/sysusers.d/cast-system-integration-fixture.conf\"\nsystemd-tmpfiles --create --dry-run --root=\"${CAST_INSTALL_ROOT}\" --graceful -E \"${CAST_INSTALL_ROOT}/usr/lib/tmpfiles.d/cast-system-integration-fixture.conf\"\nudevadm verify --root=\"${CAST_INSTALL_ROOT}\" --resolve-names=never --no-summary --no-style /usr/lib/udev/rules.d/70-cast-system-integration-fixture.rules\nxmllint --nonet --noout \"${CAST_INSTALL_ROOT}/usr/share/polkit-1/actions/io.cast.SystemIntegrationFixture.policy\""
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {
        {
            kind = "binary",
            value = "systemd-analyze"
        },
        {
            kind = "binary",
            value = "systemd-sysusers"
        },
        {
            kind = "binary",
            value = "systemd-tmpfiles"
        },
        {
            kind = "binary",
            value = "udevadm"
        },
        {
            kind = "binary",
            value = "xmllint"
        }
    },
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Declarative system integration assets fixture"
            },
            description = {
                kind = "some",
                value = "A staged helper plus systemd, sysusers, tmpfiles, udev, and self-contained polkit declarations with offline syntax checks."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "binary",
                    value = "dash"
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd-sysusers"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd-tmpfiles"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "systemd-udev"
                    }
                },
                {
                    kind = "package",
                    value = {
                        name = "polkit"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/libexec/cast-system-integration-fixture"
                },
                {
                    kind = "any",
                    path = "/usr/lib/systemd/system/cast-system-integration-fixture.service"
                },
                {
                    kind = "any",
                    path = "/usr/lib/sysusers.d/cast-system-integration-fixture.conf"
                },
                {
                    kind = "any",
                    path = "/usr/lib/tmpfiles.d/cast-system-integration-fixture.conf"
                },
                {
                    kind = "any",
                    path = "/usr/lib/udev/rules.d/70-cast-system-integration-fixture.rules"
                },
                {
                    kind = "any",
                    path = "/usr/share/polkit-1/rules.d/io.cast.SystemIntegrationFixture.rules"
                },
                {
                    kind = "any",
                    path = "/usr/share/polkit-1/actions/io.cast.SystemIntegrationFixture.policy"
                },
                {
                    kind = "any",
                    path = "/usr/share/licenses/cast-system-integration-assets-fixture/LICENSE"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-system-integration-assets-fixture-1.0.0.tar",
            hash = "27d04653529db216023599d2f6122f503acb59e0ebe26c5bce351dc970d58113",
            rename = {
                kind = "some",
                value = "cast-system-integration-assets-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-system-integration-assets-fixture"
            }
        }
    },
    architectures = {},
    tuning = {},
    emul32 = false,
    mold = false,
}