-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "typed-backend-client",
        version = "4.0.0",
        release = 1,
        homepage = "https://example.invalid/typed-backend-client",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DTLS_BACKEND=libressl"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {
        {
            kind = "pkg_config",
            value = "libressl"
        }
    },
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "soname",
                    value = "libtls.so.28"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/typed-backend-client-4.0.0.tar.xz",
            hash = "456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}