-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "staged-probe",
        version = "1.2.0",
        release = 1,
        homepage = "https://example.invalid/staged-probe",
        license = {
            "BSD-3-Clause"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DBUILD_TESTING=ON"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {},
                script = "\"${CAST_INSTALL_ROOT}${CAST_BINDIR}/staged-probe\" --self-test"
            }
        },
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Probe validated from the staged install tree"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/staged-probe"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/staged-probe-1.2.0.tar.xz",
            hash = "89abcdef0123456789abcdef0123456789abcdef0123456789abcdef01234567",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}