use std::{collections::TryReserveError, path::PathBuf, time::Instant};

use thiserror::Error;

use super::super::active_reblit_publication_plan::ActiveReblitBootPublicationPlanError;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::client) enum ActiveReblitBlsComponentKind {
    Namespace,
    OsId,
    KernelVersion,
    InitrdBasename,
    EntryFilename,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::client) enum ActiveReblitBlsComponentReason {
    Empty,
    NonAscii,
    Control,
    Dot,
    Parent,
    TooLong,
    FatForbidden,
    FatTrailingDotOrSpace,
    FatShortNameMarker,
    FatReserved,
}

#[derive(Debug, Error)]
pub(in crate::client) enum ActiveReblitBlsRendererError {
    #[error("boot BLS rendering exceeded the retained caller deadline at {checkpoint}")]
    DeadlineExceeded { checkpoint: &'static str },
    #[error(
        "boot render inputs and mounted topology were revalidated under different deadlines ({inputs:?} != {topology:?})"
    )]
    DeadlineMismatch { inputs: Instant, topology: Instant },
    #[error("boot BLS rendering work {actual} exceeds limit {limit}")]
    WorkLimit { limit: usize, actual: usize },
    #[error("boot BLS request count {actual} exceeds limit {limit}")]
    RequestCountLimit { limit: usize, actual: usize },
    #[error("boot BLS path bytes {actual} exceed limit {limit}")]
    PathByteLimit { limit: usize, actual: usize },
    #[error("boot BLS generated file {path:?} has {actual} bytes, exceeding limit {limit}")]
    GeneratedFileByteLimit { path: PathBuf, limit: usize, actual: usize },
    #[error("boot BLS generated bytes {actual} exceed limit {limit}")]
    GeneratedTotalByteLimit { limit: usize, actual: usize },
    #[error("boot BLS {kind:?} component is invalid: {reason:?}")]
    InvalidComponent {
        kind: ActiveReblitBlsComponentKind,
        reason: ActiveReblitBlsComponentReason,
    },
    #[error("boot BLS initrds {first:?} and {second:?} collide case-insensitively")]
    InitrdCaseCollision { first: Box<str>, second: Box<str> },
    #[error("boot payload path {path:?} has conflicting sealed content")]
    PayloadCollision { path: PathBuf },
    #[error("boot payload paths {first:?} and {second:?} collide case-insensitively")]
    PayloadCaseCollision { first: PathBuf, second: PathBuf },
    #[error("boot BLS sealed source coordinate is absent from the retained renderer catalog")]
    MissingSealedSource,
    #[error("allocate {resource} while rendering boot BLS requests")]
    Allocation {
        resource: &'static str,
        #[source]
        source: TryReserveError,
    },
    #[error("prepare the bounded topology-aware boot publication plan")]
    PublicationPlan(#[from] ActiveReblitBootPublicationPlanError),
}
