-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-external-test-vectors-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-external-test-vectors-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "sh"
            },
            {
                kind = "binary",
                value = "ninja"
            }
        },
        environment = {
            "cmake"
        },
        phases = {
            setup = {
                steps = {
                    {
                        kind = "cmake_configure",
                        flags = {
                            "-DBUILD_TESTING=ON",
                            "-DCAST_EXTERNAL_VECTOR_FILE=external-test-vectors.json"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "cmake_build"
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "cmake_install"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "cmake_test"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {
            {
                kind = "shell",
                interpreter = {
                    path = "/usr/bin/bash",
                    requirement = {
                        kind = "binary",
                        value = "bash"
                    }
                },
                declared_programs = {
                    {
                        path = "/usr/bin/cp",
                        requirement = {
                            kind = "binary",
                            value = "cp"
                        }
                    }
                },
                script = "test ! -e \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && cp --preserve=mode,timestamps -- \"${CAST_SOURCE_DIR}/external-test-vectors.json\" \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && test -f \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && test ! -L \"${CAST_BUILDER_DIR}/external-test-vectors.json\" && test -s \"${CAST_BUILDER_DIR}/external-test-vectors.json\""
            }
        },
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "cp"
        }
    },
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Frame codec checked against an independently locked corpus"
            },
            description = {
                kind = "some",
                value = "A real CMake/CTest build whose check-only corpus never enters the installed output."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/cast-external-test-vectors-fixture"
                }
            },
            conflicts = {}
        },
        {
            name = "dbginfo",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Frame codec debugging symbols"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/debug"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-external-test-vectors-fixture-1.0.0.tar",
            hash = "c04932c66a3399d95fda58b459b7f3e903454e5d2963f3529667216fdad50404",
            rename = {
                kind = "some",
                value = "cast-external-test-vectors-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-external-test-vectors-fixture"
            }
        },
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-external-test-vectors-fixture-1.0.0-vectors.json",
            hash = "c957dce5105c8add6e581f9aa0ee34002cbff8c9d403fab5132cebf0a8c7685c",
            rename = {
                kind = "some",
                value = "external-test-vectors.json"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = false,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}