
//! Format-neutral data transfer objects for declarative system configuration.
//!
//! These types deliberately contain only primitive values, collections,
//! options, and explicit variants. Parsing into domain types happens at this
//! boundary so configuration frontends do not expose Cast internals as their
//! public schema.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;
use std::fmt::Write as _;

use crate::{Repository, dependency, repository};

use super::{SystemModel, SystemParts};

/// A declarative system configuration before domain conversion.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SystemSpec {
    pub disable_warning: bool,
    pub repositories: Vec<RepositorySpec>,
    /// Package names and explicit provider expressions such as
    /// `soname(libc.so.6)`.
    pub packages: Vec<String>,
}

/// A repository entry before URL and repository-format validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositorySpec {
    pub id: String,
    pub description: Option<String>,
    pub source: RepositorySourceSpec,
    /// Signed at the DTO boundary so a negative configuration value is
    /// rejected with a field-path diagnostic instead of being coerced.
    pub priority: Option<i64>,
    pub enabled: Option<bool>,
}

/// The supported repository source variants before semantic validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RepositorySourceSpec {
    DirectIndex {
        uri: String,
    },
    RootIndex {
        base_uri: String,
        channel: Option<String>,
        version: String,
        arch: Option<String>,
    },
}

/// Marker emitted at the start of every normalized system snapshot.
pub const GENERATED_GLUON_MARKER: &str = "// @generated by cast. DO NOT EDIT.\n";

const STANDALONE_GLUON_TYPES: &str = r#"type Bool =
    | False
    | True

type Option a =
    | None
    | Some a

type RepositorySourceSpec =
    | DirectIndex { uri : String }
    | RootIndex {
        base_uri : String,
        channel : Option String,
        version : String,
        arch : Option String,
    }

type RepositorySpec = {
    id : String,
    description : Option String,
    source : RepositorySourceSpec,
    priority : Option Int,
    enabled : Option Bool,
}

type SystemSpec = {
    disable_warning : Bool,
    repositories : Array RepositorySpec,
    packages : Array String,
}

"#;

/// A semantic conversion error tied to its DTO field path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConversionError {
    path: String,
    message: String,
}

impl ConversionError {
    fn new(path: impl Into<String>, error: impl fmt::Display) -> Self {
        Self {
            path: path.into(),
            message: error.to_string(),
        }
    }

    fn at(mut self, parent: impl fmt::Display) -> Self {
        self.path = if self.path.is_empty() {
            parent.to_string()
        } else {
            format!("{parent}.{}", self.path)
        };
        self
    }

    pub fn path(&self) -> &str {
        &self.path
    }

    pub fn message(&self) -> &str {
        &self.message
    }
}

impl fmt::Display for ConversionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "invalid system specification at `{}`: {}", self.path, self.message)
    }
}

impl Error for ConversionError {}

impl TryFrom<&SystemModel> for SystemSpec {
    type Error = ConversionError;

    fn try_from(model: &SystemModel) -> Result<Self, Self::Error> {
        from_domain(model.disable_warning, &model.repositories, &model.packages)
    }
}

pub(super) fn from_domain(
    disable_warning: bool,
    repositories: &repository::Map,
    packages: &BTreeSet<dependency::Provider>,
) -> Result<SystemSpec, ConversionError> {
    let repositories = repositories
        .iter()
        .enumerate()
        .map(|(index, (id, repository))| {
            let priority = i64::try_from(u64::from(repository.priority))
                .map_err(|error| ConversionError::new(format!("repositories[{index}].priority"), error))?;
            let source = match &repository.source {
                repository::Source::DirectIndex(uri) => RepositorySourceSpec::DirectIndex { uri: uri.to_string() },
                repository::Source::RootIndex(source) => RepositorySourceSpec::RootIndex {
                    base_uri: source.base_uri.to_string(),
                    channel: Some(source.channel.to_string()),
                    version: source.version.to_string(),
                    arch: Some(source.arch.clone()),
                },
            };

            Ok(RepositorySpec {
                id: id.to_string(),
                description: Some(repository.description.clone()),
                source,
                priority: Some(priority),
                enabled: Some(repository.active),
            })
        })
        .collect::<Result<Vec<_>, ConversionError>>()?;
    let mut packages = packages.iter().map(dependency::Provider::to_name).collect::<Vec<_>>();
    packages.sort();

    Ok(SystemSpec {
        disable_warning,
        repositories,
        packages,
    })
}

impl TryFrom<SystemModel> for SystemSpec {
    type Error = ConversionError;

    fn try_from(model: SystemModel) -> Result<Self, Self::Error> {
        Self::try_from(&model)
    }
}

/// Encode a canonical, import-free Gluon value for a generated system
/// snapshot.
///
/// Repositories and packages are sorted before emission, and every optional
/// field remains explicit. The result is normalized state, not authored source.
pub fn encode_generated_gluon(spec: &SystemSpec) -> String {
    let mut repositories = spec.repositories.iter().collect::<Vec<_>>();
    repositories.sort_by(|left, right| left.id.cmp(&right.id));
    let mut packages = spec.packages.iter().collect::<Vec<_>>();
    packages.sort();

    let mut output = String::from(GENERATED_GLUON_MARKER);
    output.push_str("// Canonical standalone SystemSpec snapshot (ABI 1).\n");
    output.push_str(STANDALONE_GLUON_TYPES);
    output.push_str("{\n");
    writeln!(output, "    disable_warning = {},", gluon_bool(spec.disable_warning)).unwrap();
    output.push_str("    repositories = [\n");
    for repository in repositories {
        output.push_str("        {\n");
        writeln!(output, "            id = {},", gluon_string(&repository.id)).unwrap();
        writeln!(
            output,
            "            description = {},",
            gluon_optional_string(repository.description.as_deref())
        )
        .unwrap();
        encode_repository_source(&mut output, &repository.source);
        writeln!(
            output,
            "            priority = {},",
            gluon_optional_integer(repository.priority)
        )
        .unwrap();
        writeln!(
            output,
            "            enabled = {},",
            gluon_optional_bool(repository.enabled)
        )
        .unwrap();
        output.push_str("        },\n");
    }
    output.push_str("    ],\n");
    output.push_str("    packages = [\n");
    for package in packages {
        writeln!(output, "        {},", gluon_string(package)).unwrap();
    }
    output.push_str("    ],\n");
    output.push_str("}\n");
    output
}

fn encode_repository_source(output: &mut String, source: &RepositorySourceSpec) {
    match source {
        RepositorySourceSpec::DirectIndex { uri } => {
            output.push_str("            source = DirectIndex {\n");
            writeln!(output, "                uri = {},", gluon_string(uri)).unwrap();
            output.push_str("            },\n");
        }
        RepositorySourceSpec::RootIndex {
            base_uri,
            channel,
            version,
            arch,
        } => {
            output.push_str("            source = RootIndex {\n");
            writeln!(output, "                base_uri = {},", gluon_string(base_uri)).unwrap();
            writeln!(
                output,
                "                channel = {},",
                gluon_optional_string(channel.as_deref())
            )
            .unwrap();
            writeln!(output, "                version = {},", gluon_string(version)).unwrap();
            writeln!(
                output,
                "                arch = {},",
                gluon_optional_string(arch.as_deref())
            )
            .unwrap();
            output.push_str("            },\n");
        }
    }
}

fn gluon_bool(value: bool) -> &'static str {
    if value { "True" } else { "False" }
}

fn gluon_optional_bool(value: Option<bool>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {}", gluon_bool(value)))
}

fn gluon_optional_integer(value: Option<i64>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {value}"))
}

fn gluon_optional_string(value: Option<&str>) -> String {
    value.map_or_else(|| "None".to_owned(), |value| format!("Some {}", gluon_string(value)))
}

fn gluon_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

impl TryFrom<SystemSpec> for SystemModel {
    type Error = ConversionError;

    fn try_from(spec: SystemSpec) -> Result<Self, Self::Error> {
        let parts = into_domain(spec)?;
        Ok(super::create_with_options(
            parts.disable_warning,
            parts.repositories,
            parts.packages,
        ))
    }
}

pub(super) fn into_domain(spec: SystemSpec) -> Result<SystemParts, ConversionError> {
    let mut repository_ids = BTreeSet::new();
    let repositories = spec
        .repositories
        .into_iter()
        .enumerate()
        .map(|(index, repository)| {
            let path = format!("repositories[{index}]");
            let (id, repository) = convert_repository(repository).map_err(|error| error.at(&path))?;

            if !repository_ids.insert(id.clone()) {
                return Err(ConversionError::new(
                    format!("{path}.id"),
                    format_args!("duplicate repository identifier `{id}`"),
                ));
            }

            Ok((id, repository))
        })
        .collect::<Result<repository::Map, _>>()?;

    let packages = spec
        .packages
        .into_iter()
        .enumerate()
        .map(|(index, package)| {
            dependency::Provider::from_name(&package)
                .map_err(|error| ConversionError::new(format!("packages[{index}]"), error))
        })
        .collect::<Result<BTreeSet<_>, _>>()?;

    Ok(SystemParts {
        disable_warning: spec.disable_warning,
        repositories,
        packages,
    })
}

impl TryFrom<RepositorySpec> for (repository::Id, Repository) {
    type Error = ConversionError;

    fn try_from(spec: RepositorySpec) -> Result<Self, Self::Error> {
        convert_repository(spec)
    }
}

fn convert_repository(spec: RepositorySpec) -> Result<(repository::Id, Repository), ConversionError> {
    let id = repository::Id::new(&spec.id);
    let source = repository::Source::try_from(spec.source).map_err(|error| error.at("source"))?;
    let priority = spec
        .priority
        .unwrap_or_default()
        .try_into()
        .map(repository::Priority::new)
        .map_err(|error| ConversionError::new("priority", error))?;

    Ok((
        id,
        Repository {
            description: spec.description.unwrap_or_default(),
            source,
            priority,
            active: spec.enabled.unwrap_or(true),
        },
    ))
}

impl TryFrom<RepositorySourceSpec> for repository::Source {
    type Error = ConversionError;

    fn try_from(spec: RepositorySourceSpec) -> Result<Self, Self::Error> {
        match spec {
            RepositorySourceSpec::DirectIndex { uri } => uri
                .parse()
                .map(Self::DirectIndex)
                .map_err(|error| ConversionError::new("uri", error)),
            RepositorySourceSpec::RootIndex {
                base_uri,
                channel,
                version,
                arch,
            } => {
                let base_uri = base_uri
                    .parse()
                    .map_err(|error| ConversionError::new("base_uri", error))?;
                let channel = channel
                    .unwrap_or_else(|| repository::DEFAULT_CHANNEL.to_owned())
                    .try_into()
                    .map_err(|error| ConversionError::new("channel", error))?;
                let version = version
                    .parse()
                    .map_err(|error| ConversionError::new("version", error))?;

                Ok(Self::RootIndex(repository::RootIndexSource {
                    base_uri,
                    channel,
                    version,
                    arch: arch.unwrap_or_else(|| repository::DEFAULT_ARCH.to_owned()),
                }))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn structural_round_trip(spec: SystemSpec) -> SystemSpec {
        let model = SystemModel::try_from(spec).expect("convert spec to domain model");
        let normalized = SystemSpec::try_from(&model).expect("convert domain model to normalized spec");
        let rebuilt = SystemModel::try_from(normalized.clone()).expect("rebuild domain model");
        let rebuilt = SystemSpec::try_from(&rebuilt).expect("normalize rebuilt domain model");
        assert_eq!(rebuilt, normalized);
        normalized
    }

    fn direct_repository(uri: &str) -> RepositorySpec {
        RepositorySpec {
            id: "local".to_owned(),
            description: None,
            source: RepositorySourceSpec::DirectIndex { uri: uri.to_owned() },
            priority: None,
            enabled: None,
        }
    }

    fn root_repository() -> RepositorySpec {
        RepositorySpec {
            id: "volatile".to_owned(),
            description: None,
            source: RepositorySourceSpec::RootIndex {
                base_uri: "https://packages.example.test".to_owned(),
                channel: None,
                version: "stream/volatile".to_owned(),
                arch: None,
            },
            priority: None,
            enabled: None,
        }
    }

    fn conversion_error(spec: SystemSpec) -> ConversionError {
        SystemModel::try_from(spec).expect_err("spec should be invalid")
    }

    #[test]
    fn empty_spec_uses_system_defaults() {
        let model = SystemModel::try_from(SystemSpec::default()).expect("convert empty spec");

        assert!(!model.disable_warning);
        assert_eq!(model.repositories.iter().count(), 0);
        assert!(model.packages.is_empty());
    }

    #[test]
    fn empty_domain_model_round_trips_to_a_standalone_generated_literal() {
        let normalized = structural_round_trip(SystemSpec::default());

        assert_eq!(normalized, SystemSpec::default());
        assert_eq!(
            encode_generated_gluon(&normalized),
            concat!(
                "// @generated by cast. DO NOT EDIT.\n",
                "// Canonical standalone SystemSpec snapshot (ABI 1).\n",
                "type Bool =\n",
                "    | False\n",
                "    | True\n",
                "\n",
                "type Option a =\n",
                "    | None\n",
                "    | Some a\n",
                "\n",
                "type RepositorySourceSpec =\n",
                "    | DirectIndex { uri : String }\n",
                "    | RootIndex {\n",
                "        base_uri : String,\n",
                "        channel : Option String,\n",
                "        version : String,\n",
                "        arch : Option String,\n",
                "    }\n",
                "\n",
                "type RepositorySpec = {\n",
                "    id : String,\n",
                "    description : Option String,\n",
                "    source : RepositorySourceSpec,\n",
                "    priority : Option Int,\n",
                "    enabled : Option Bool,\n",
                "}\n",
                "\n",
                "type SystemSpec = {\n",
                "    disable_warning : Bool,\n",
                "    repositories : Array RepositorySpec,\n",
                "    packages : Array String,\n",
                "}\n",
                "\n",
                "{\n",
                "    disable_warning = False,\n",
                "    repositories = [\n",
                "    ],\n",
                "    packages = [\n",
                "    ],\n",
                "}\n",
            )
        );
    }

    #[test]
    fn populated_domain_model_round_trips_and_normalizes_all_repository_fields() {
        let mut root = root_repository();
        root.id = "z-root".to_owned();
        let mut direct = direct_repository("file:///var/cache/local.index");
        direct.id = "a-direct".to_owned();
        direct.description = Some("line \"quoted\"\npath\\leaf\t雪".to_owned());
        direct.priority = Some(5);
        direct.enabled = Some(false);

        let normalized = structural_round_trip(SystemSpec {
            disable_warning: true,
            repositories: vec![root, direct],
            packages: vec![
                "soname(libc.so.6)".to_owned(),
                "alpha".to_owned(),
                "binary(tool)".to_owned(),
            ],
        });

        assert_eq!(
            normalized.packages,
            ["alpha", "binary(tool)", "soname(libc.so.6)"].map(str::to_owned)
        );
        assert_eq!(
            normalized
                .repositories
                .iter()
                .map(|repository| repository.id.as_str())
                .collect::<Vec<_>>(),
            ["a-direct", "z-root"]
        );

        let direct = &normalized.repositories[0];
        assert_eq!(direct.priority, Some(5));
        assert_eq!(direct.enabled, Some(false));
        assert!(matches!(direct.source, RepositorySourceSpec::DirectIndex { .. }));

        let root = &normalized.repositories[1];
        assert_eq!(root.description.as_deref(), Some(""));
        assert_eq!(root.priority, Some(0));
        assert_eq!(root.enabled, Some(true));
        assert_eq!(
            root.source,
            RepositorySourceSpec::RootIndex {
                base_uri: "https://packages.example.test/".to_owned(),
                channel: Some(repository::DEFAULT_CHANNEL.to_owned()),
                version: "stream/volatile".to_owned(),
                arch: Some(repository::DEFAULT_ARCH.to_owned()),
            }
        );
    }

    #[test]
    fn generated_gluon_is_marked_escaped_and_independent_of_input_order() {
        let mut direct = direct_repository("file:///var/cache/local.index");
        direct.id = "a-direct".to_owned();
        direct.description = Some("line \"quoted\"\npath\\leaf\t雪".to_owned());
        direct.priority = Some(5);
        direct.enabled = Some(false);
        let mut root = root_repository();
        root.id = "z-root".to_owned();
        let spec = SystemSpec {
            disable_warning: true,
            repositories: vec![root, direct],
            packages: vec!["soname(libc.so.6)".to_owned(), "alpha".to_owned()],
        };
        let encoded = encode_generated_gluon(&spec);

        let mut reordered = spec.clone();
        reordered.repositories.reverse();
        reordered.packages.reverse();

        assert_eq!(encoded, encode_generated_gluon(&reordered));
        assert!(encoded.starts_with(GENERATED_GLUON_MARKER));
        assert!(!encoded.contains("import!"));
        assert!(encoded.contains("type RepositorySourceSpec ="));
        assert!(encoded.contains("type SystemSpec ="));
        assert!(encoded.contains("description = Some \"line \\\"quoted\\\"\\npath\\\\leaf\\t雪\","));
        assert!(encoded.find("id = \"a-direct\"").unwrap() < encoded.find("id = \"z-root\"").unwrap());
        assert!(encoded.find("\"alpha\"").unwrap() < encoded.find("\"soname(libc.so.6)\"").unwrap());
    }

    #[test]
    fn converts_repository_defaults_and_package_provider_selections() {
        let model = SystemModel::try_from(SystemSpec {
            disable_warning: true,
            repositories: vec![root_repository(), direct_repository("file:///var/cache/local.index")],
            packages: vec!["cast".to_owned(), "soname(libc.so.6)".to_owned()],
        })
        .expect("convert populated spec");

        assert!(model.disable_warning);
        assert!(model.encoded().starts_with(GENERATED_GLUON_MARKER));
        assert!(model.encoded().contains("disable_warning = True,"));

        let root = model
            .repositories
            .get(&repository::Id::new("volatile"))
            .expect("root repository");
        assert_eq!(root.description, "");
        assert_eq!(u64::from(root.priority), 0);
        assert!(root.active);
        let repository::Source::RootIndex(root_source) = &root.source else {
            panic!("expected root-index source");
        };
        assert_eq!(root_source.base_uri.as_str(), "https://packages.example.test/");
        assert_eq!(root_source.channel.as_ref(), repository::DEFAULT_CHANNEL);
        assert_eq!(root_source.version.to_string(), "stream/volatile");
        assert_eq!(root_source.arch, repository::DEFAULT_ARCH);

        let direct = model
            .repositories
            .get(&repository::Id::new("local"))
            .expect("direct repository");
        assert_eq!(u64::from(direct.priority), 0);
        assert!(direct.active);
        assert_eq!(
            direct.source.direct_index().map(|uri| uri.as_str()),
            Some("file:///var/cache/local.index")
        );

        assert_eq!(
            model.packages,
            BTreeSet::from([
                dependency::Provider::package_name("cast"),
                dependency::Provider::from_name("soname(libc.so.6)").unwrap(),
            ])
        );
    }

    #[test]
    fn converts_explicit_repository_fields() {
        let (id, repository) = <(repository::Id, Repository)>::try_from(RepositorySpec {
            id: "testing".to_owned(),
            description: Some("testing packages".to_owned()),
            source: RepositorySourceSpec::RootIndex {
                base_uri: "https://packages.example.test/base".to_owned(),
                channel: Some("testing".to_owned()),
                version: "tag/2026-07".to_owned(),
                arch: Some("aarch64".to_owned()),
            },
            priority: Some(50),
            enabled: Some(false),
        })
        .expect("convert repository");

        assert_eq!(id.to_string(), "testing");
        assert_eq!(repository.description, "testing packages");
        assert_eq!(u64::from(repository.priority), 50);
        assert!(!repository.active);
        let repository::Source::RootIndex(source) = repository.source else {
            panic!("expected root-index source");
        };
        assert_eq!(source.channel.as_ref(), "testing");
        assert_eq!(source.version.to_string(), "tag/2026-07");
        assert_eq!(source.arch, "aarch64");
    }

    #[test]
    fn reports_url_field_paths() {
        let direct = conversion_error(SystemSpec {
            repositories: vec![direct_repository("not a url")],
            ..SystemSpec::default()
        });
        assert_eq!(direct.path(), "repositories[0].source.uri");

        let mut root = root_repository();
        let RepositorySourceSpec::RootIndex { base_uri, .. } = &mut root.source else {
            unreachable!();
        };
        *base_uri = "not a url".to_owned();
        let root = conversion_error(SystemSpec {
            repositories: vec![root],
            ..SystemSpec::default()
        });
        assert_eq!(root.path(), "repositories[0].source.base_uri");
    }

    #[test]
    fn reports_channel_and_version_field_paths() {
        let mut invalid_channel = root_repository();
        let RepositorySourceSpec::RootIndex { channel, .. } = &mut invalid_channel.source else {
            unreachable!();
        };
        *channel = Some("-testing".to_owned());
        let error = conversion_error(SystemSpec {
            repositories: vec![invalid_channel],
            ..SystemSpec::default()
        });
        assert_eq!(error.path(), "repositories[0].source.channel");

        let mut invalid_version = root_repository();
        let RepositorySourceSpec::RootIndex { version, .. } = &mut invalid_version.source else {
            unreachable!();
        };
        *version = "volatile".to_owned();
        let error = conversion_error(SystemSpec {
            repositories: vec![invalid_version],
            ..SystemSpec::default()
        });
        assert_eq!(error.path(), "repositories[0].source.version");
    }

    #[test]
    fn reports_priority_and_provider_field_paths() {
        let mut repository = direct_repository("https://packages.example.test/index.stone");
        repository.priority = Some(-1);
        let error = conversion_error(SystemSpec {
            repositories: vec![repository],
            ..SystemSpec::default()
        });
        assert_eq!(error.path(), "repositories[0].priority");

        let error = conversion_error(SystemSpec {
            packages: vec!["soname(incomplete".to_owned()],
            ..SystemSpec::default()
        });
        assert_eq!(error.path(), "packages[0]");
    }

    #[test]
    fn rejects_duplicate_normalized_repository_ids() {
        let mut original = direct_repository("https://packages.example.test/one.index");
        original.id = "local?".to_owned();
        let mut duplicate = direct_repository("https://packages.example.test/two.index");
        duplicate.id = "local!".to_owned();
        let error = conversion_error(SystemSpec {
            repositories: vec![original, duplicate],
            ..SystemSpec::default()
        });

        assert_eq!(error.path(), "repositories[1].id");
        assert!(error.message().contains("duplicate repository identifier"));
    }
}
