-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-split-fixture-1.0.0.tar",
            sha256 = "bd78efc34e46566f967ae963c895c1e7d9de45da7d7022c5c4f6683425ae567d"
        },
    },
}