-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "shared-capability-origins",
        version = "1.0.0",
        release = 1,
        homepage = "https://example.invalid/shared-capability-origins",
        license = {
            "MIT"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "bash"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {},
                        script = "printf '%s\\n' shared-capability > capability.marker"
                    }
                }
            },
            install = {
                steps = {}
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "bash"
        }
    },
    build_inputs = {
        {
            kind = "binary",
            value = "bash"
        }
    },
    check_inputs = {
        {
            kind = "binary",
            value = "bash"
        }
    },
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "binary",
                    value = "bash"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}