// SPDX-FileCopyrightText: 2026 AerynOS Developers
// SPDX-License-Identifier: MPL-2.0

//! Canonical generated dependency and policy resolution data.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    str,
};

use gluon_config::{Diagnostic, Evaluator, Source};
use sha2::{Digest, Sha256};
use thiserror::Error;

use super::CanonicalEncoder;

pub const BUILD_LOCK_FILE_NAME: &str = "build.lock.glu";
pub const BUILD_LOCK_SCHEMA_VERSION: u32 = 2;

const BUILD_LOCK_HASH_DOMAIN: &[u8] = b"os-tools-build-lock\0";
const GENERATED_GLUON_MARKER: &str = "// @generated by boulder. DO NOT EDIT.\n";

const STANDALONE_GLUON_TYPES: &str = r#"type LockedIdentity = {
    name : String,
    fingerprint : String,
}

type Platform = {
    architecture : String,
    vendor : String,
    operating_system : String,
    abi : String,
}

type RepositorySnapshot = {
    id : String,
    index_uri : String,
    snapshot : String,
}

type LockedOutput = {
    name : String,
}

type LockedOutputRef = {
    package_id : String,
    output : String,
}

type LockedPackage = {
    package_id : String,
    name : String,
    version : String,
    architecture : String,
    repository : String,
    outputs : Array LockedOutput,
    dependencies : Array LockedOutputRef,
}

type LockedRequest = {
    request : String,
    package_id : String,
    output : String,
}

type BuildLock = {
    schema_version : Int,
    request_fingerprint : String,
    repositories : Array RepositorySnapshot,
    requests : Array LockedRequest,
    packages : Array LockedPackage,
    build_platform : Platform,
    host_platform : Platform,
    target_platform : Platform,
    policy : LockedIdentity,
    target : LockedIdentity,
    profile : LockedIdentity,
    toolchain : LockedIdentity,
    builder : LockedIdentity,
}

"#;

/// Exact package, repository, platform, and policy resolution used by a plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuildLock {
    pub schema_version: u32,
    pub request_fingerprint: String,
    pub repositories: Vec<RepositorySnapshot>,
    pub requests: Vec<LockedRequest>,
    pub packages: Vec<LockedPackage>,
    pub build_platform: Platform,
    pub host_platform: Platform,
    pub target_platform: Platform,
    pub policy: LockedIdentity,
    pub target: LockedIdentity,
    pub profile: LockedIdentity,
    pub toolchain: LockedIdentity,
    pub builder: LockedIdentity,
}

impl BuildLock {
    /// Normalize semantically unordered lock collections.
    pub fn normalize(&mut self) {
        self.repositories
            .sort_by(|left, right| left.id.cmp(&right.id).then_with(|| left.snapshot.cmp(&right.snapshot)));
        self.requests.sort_by(|left, right| left.request.cmp(&right.request));
        self.packages
            .sort_by(|left, right| left.package_id.cmp(&right.package_id));
        for package in &mut self.packages {
            package.outputs.sort_by(|left, right| left.name.cmp(&right.name));
            package.dependencies.sort();
        }
    }

    /// Validate that the lock describes an exact, internally consistent
    /// package/output closure.
    pub fn validate(&self) -> Result<(), BuildLockValidationError> {
        if self.schema_version != BUILD_LOCK_SCHEMA_VERSION {
            return Err(BuildLockValidationError::UnsupportedSchema {
                found: self.schema_version,
                expected: BUILD_LOCK_SCHEMA_VERSION,
            });
        }
        require_nonempty("request_fingerprint", &self.request_fingerprint)?;
        self.build_platform.validate("build_platform")?;
        self.host_platform.validate("host_platform")?;
        self.target_platform.validate("target_platform")?;
        self.policy.validate("policy")?;
        self.target.validate("target")?;
        self.profile.validate("profile")?;
        self.toolchain.validate("toolchain")?;
        self.builder.validate("builder")?;

        let mut repositories = BTreeMap::new();
        for (index, repository) in self.repositories.iter().enumerate() {
            require_nonempty(&format!("repositories[{index}].id"), &repository.id)?;
            require_nonempty(&format!("repositories[{index}].index_uri"), &repository.index_uri)?;
            require_nonempty(&format!("repositories[{index}].snapshot"), &repository.snapshot)?;
            if let Some(first_index) = repositories.insert(repository.id.as_str(), index) {
                return Err(BuildLockValidationError::DuplicateRepository {
                    id: repository.id.clone(),
                    first_index,
                    duplicate_index: index,
                });
            }
        }

        let mut packages = BTreeMap::new();
        let mut used_repositories = BTreeSet::new();
        for (index, package) in self.packages.iter().enumerate() {
            package.validate(index)?;
            if let Some(first_index) = packages.insert(package.package_id.as_str(), index) {
                return Err(BuildLockValidationError::DuplicatePackage {
                    id: package.package_id.clone(),
                    first_index,
                    duplicate_index: index,
                });
            }
            if !repositories.contains_key(package.repository.as_str()) {
                return Err(BuildLockValidationError::UnknownRepository {
                    package: package.package_id.clone(),
                    repository: package.repository.clone(),
                });
            }
            used_repositories.insert(package.repository.as_str());
        }
        for (index, repository) in self.repositories.iter().enumerate() {
            if !used_repositories.contains(repository.id.as_str()) {
                return Err(BuildLockValidationError::UnusedRepository {
                    index,
                    id: repository.id.clone(),
                });
            }
        }

        let mut requests = BTreeMap::new();
        for (index, request) in self.requests.iter().enumerate() {
            require_nonempty(&format!("requests[{index}].request"), &request.request)?;
            require_nonempty(&format!("requests[{index}].package_id"), &request.package_id)?;
            require_nonempty(&format!("requests[{index}].output"), &request.output)?;
            if let Some(first_index) = requests.insert(request.request.as_str(), index) {
                return Err(BuildLockValidationError::DuplicateRequest {
                    request: request.request.clone(),
                    first_index,
                    duplicate_index: index,
                });
            }
            let Some(package_index) = packages.get(request.package_id.as_str()) else {
                return Err(BuildLockValidationError::UnknownPackage {
                    field: format!("requests[{index}]"),
                    package: request.package_id.clone(),
                });
            };
            if !self.packages[*package_index]
                .outputs
                .iter()
                .any(|output| output.name == request.output)
            {
                return Err(BuildLockValidationError::UnknownOutput {
                    field: format!("requests[{index}]"),
                    package: request.package_id.clone(),
                    output: request.output.clone(),
                });
            }
        }

        for (package_index, package) in self.packages.iter().enumerate() {
            for (dependency_index, dependency) in package.dependencies.iter().enumerate() {
                let Some(target_index) = packages.get(dependency.package_id.as_str()) else {
                    return Err(BuildLockValidationError::UnknownPackage {
                        field: format!("packages[{package_index}].dependencies[{dependency_index}]"),
                        package: dependency.package_id.clone(),
                    });
                };
                let target = &self.packages[*target_index];
                if !target.outputs.iter().any(|output| output.name == dependency.output) {
                    return Err(BuildLockValidationError::UnknownOutput {
                        field: format!("packages[{package_index}].dependencies[{dependency_index}]"),
                        package: dependency.package_id.clone(),
                        output: dependency.output.clone(),
                    });
                }
            }
        }

        detect_dependency_cycles(&self.packages, &packages)?;
        require_reachable_packages(&self.packages, &self.requests, &packages)?;

        Ok(())
    }

    /// Return the stable binary encoding used when the lock contributes to a
    /// derivation identity.
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut encoder = CanonicalEncoder::new(BUILD_LOCK_HASH_DOMAIN);
        self.encode_canonical(&mut encoder);
        encoder.finish()
    }

    /// Hash the canonical lock independently from the presentation encoding.
    pub fn digest(&self) -> String {
        format!("{:x}", Sha256::digest(self.canonical_bytes()))
    }

    /// Return whether an exact package/output identity is present in the
    /// locked closure.
    pub fn contains_output(&self, reference: &LockedOutputRef) -> bool {
        self.packages.iter().any(|package| {
            package.package_id == reference.package_id
                && package.outputs.iter().any(|output| output.name == reference.output)
        })
    }

    pub(super) fn encode_canonical(&self, encoder: &mut CanonicalEncoder) {
        encoder.u32(self.schema_version);
        encoder.string(&self.request_fingerprint);

        let mut repositories = self.repositories.iter().collect::<Vec<_>>();
        repositories.sort_by(|left, right| left.id.cmp(&right.id).then_with(|| left.snapshot.cmp(&right.snapshot)));
        encoder.sequence(&repositories, |encoder, repository| repository.encode(encoder));

        let mut requests = self.requests.iter().collect::<Vec<_>>();
        requests.sort_by(|left, right| left.request.cmp(&right.request));
        encoder.sequence(&requests, |encoder, request| request.encode(encoder));

        let mut packages = self.packages.iter().collect::<Vec<_>>();
        packages.sort_by(|left, right| left.package_id.cmp(&right.package_id));
        encoder.sequence(&packages, |encoder, package| package.encode(encoder));

        self.build_platform.encode(encoder);
        self.host_platform.encode(encoder);
        self.target_platform.encode(encoder);
        self.policy.encode(encoder);
        self.target.encode(encoder);
        self.profile.encode(encoder);
        self.toolchain.encode(encoder);
        self.builder.encode(encoder);
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Platform {
    pub architecture: String,
    pub vendor: String,
    pub operating_system: String,
    pub abi: String,
}

impl Platform {
    fn validate(&self, field: &str) -> Result<(), BuildLockValidationError> {
        require_nonempty(&format!("{field}.architecture"), &self.architecture)?;
        require_nonempty(&format!("{field}.vendor"), &self.vendor)?;
        require_nonempty(&format!("{field}.operating_system"), &self.operating_system)?;
        require_nonempty(&format!("{field}.abi"), &self.abi)
    }

    fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.architecture);
        encoder.string(&self.vendor);
        encoder.string(&self.operating_system);
        encoder.string(&self.abi);
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepositorySnapshot {
    pub id: String,
    pub index_uri: String,
    pub snapshot: String,
}

impl RepositorySnapshot {
    fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.id);
        encoder.string(&self.index_uri);
        encoder.string(&self.snapshot);
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedIdentity {
    pub name: String,
    pub fingerprint: String,
}

impl LockedIdentity {
    pub(super) fn validate(&self, field: &str) -> Result<(), BuildLockValidationError> {
        require_nonempty(&format!("{field}.name"), &self.name)?;
        require_nonempty(&format!("{field}.fingerprint"), &self.fingerprint)
    }

    pub(super) fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.name);
        encoder.string(&self.fingerprint);
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    pub package_id: String,
    pub name: String,
    pub version: String,
    pub architecture: String,
    pub repository: String,
    pub outputs: Vec<LockedOutput>,
    pub dependencies: Vec<LockedOutputRef>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedRequest {
    pub request: String,
    pub package_id: String,
    pub output: String,
}

impl LockedRequest {
    fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.request);
        encoder.string(&self.package_id);
        encoder.string(&self.output);
    }
}

impl LockedPackage {
    fn validate(&self, index: usize) -> Result<(), BuildLockValidationError> {
        for (field, value) in [
            ("package_id", &self.package_id),
            ("name", &self.name),
            ("version", &self.version),
            ("architecture", &self.architecture),
            ("repository", &self.repository),
        ] {
            require_nonempty(&format!("packages[{index}].{field}"), value)?;
        }
        if self.outputs.is_empty() {
            return Err(BuildLockValidationError::MissingOutputs {
                package: self.package_id.clone(),
            });
        }

        let mut outputs = BTreeMap::new();
        for (output_index, output) in self.outputs.iter().enumerate() {
            require_nonempty(&format!("packages[{index}].outputs[{output_index}].name"), &output.name)?;
            if let Some(first_index) = outputs.insert(output.name.as_str(), output_index) {
                return Err(BuildLockValidationError::DuplicateOutput {
                    package: self.package_id.clone(),
                    output: output.name.clone(),
                    first_index,
                    duplicate_index: output_index,
                });
            }
        }
        let mut dependencies = BTreeMap::new();
        for (dependency_index, dependency) in self.dependencies.iter().enumerate() {
            require_nonempty(
                &format!("packages[{index}].dependencies[{dependency_index}].package_id"),
                &dependency.package_id,
            )?;
            require_nonempty(
                &format!("packages[{index}].dependencies[{dependency_index}].output"),
                &dependency.output,
            )?;
            if let Some(first_index) = dependencies.insert(
                (dependency.package_id.as_str(), dependency.output.as_str()),
                dependency_index,
            ) {
                return Err(BuildLockValidationError::DuplicateDependency {
                    package: self.package_id.clone(),
                    dependency_package: dependency.package_id.clone(),
                    output: dependency.output.clone(),
                    first_index,
                    duplicate_index: dependency_index,
                });
            }
        }
        Ok(())
    }

    fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.package_id);
        encoder.string(&self.name);
        encoder.string(&self.version);
        encoder.string(&self.architecture);
        encoder.string(&self.repository);

        let mut outputs = self.outputs.iter().collect::<Vec<_>>();
        outputs.sort_by(|left, right| left.name.cmp(&right.name));
        encoder.sequence(&outputs, |encoder, output| output.encode(encoder));

        let mut dependencies = self.dependencies.iter().collect::<Vec<_>>();
        dependencies.sort();
        encoder.sequence(&dependencies, |encoder, dependency| dependency.encode(encoder));
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedOutput {
    pub name: String,
}

impl LockedOutput {
    fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.name);
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockedOutputRef {
    pub package_id: String,
    pub output: String,
}

impl LockedOutputRef {
    pub(super) fn encode(&self, encoder: &mut CanonicalEncoder) {
        encoder.string(&self.package_id);
        encoder.string(&self.output);
    }
}

/// Decode a standalone generated lock using the restricted Gluon evaluator.
pub fn decode_build_lock(logical_name: &str, bytes: &[u8]) -> Result<BuildLock, BuildLockDecodeError> {
    let source = str::from_utf8(bytes)?;
    let evaluated = Evaluator::default()
        .evaluate::<GluonBuildLock>(&Source::new(logical_name, source))
        .map_err(|error| BuildLockDecodeError::Evaluation(Box::new(error)))?;
    let mut lock = BuildLock::try_from(evaluated.value)?;
    lock.normalize();
    lock.validate()?;
    Ok(lock)
}

/// Encode a canonical, import-free `build.lock.glu` value.
pub fn encode_build_lock(lock: &BuildLock) -> String {
    let mut lock = lock.clone();
    lock.normalize();

    let mut output = String::from(GENERATED_GLUON_MARKER);
    output.push_str("// Canonical standalone build lock. Schema version is explicit below.\n");
    output.push_str(STANDALONE_GLUON_TYPES);
    output.push_str("{\n");
    writeln!(output, "    schema_version = {},", lock.schema_version).unwrap();
    writeln!(
        output,
        "    request_fingerprint = {},",
        gluon_string(&lock.request_fingerprint)
    )
    .unwrap();
    output.push_str("    repositories = [\n");
    for repository in &lock.repositories {
        output.push_str("        {\n");
        writeln!(output, "            id = {},", gluon_string(&repository.id)).unwrap();
        writeln!(
            output,
            "            index_uri = {},",
            gluon_string(&repository.index_uri)
        )
        .unwrap();
        writeln!(output, "            snapshot = {},", gluon_string(&repository.snapshot)).unwrap();
        output.push_str("        },\n");
    }
    output.push_str("    ],\n");
    output.push_str("    requests = [\n");
    for request in &lock.requests {
        output.push_str("        {\n");
        writeln!(output, "            request = {},", gluon_string(&request.request)).unwrap();
        writeln!(
            output,
            "            package_id = {},",
            gluon_string(&request.package_id)
        )
        .unwrap();
        writeln!(output, "            output = {},", gluon_string(&request.output)).unwrap();
        output.push_str("        },\n");
    }
    output.push_str("    ],\n");
    output.push_str("    packages = [\n");
    for package in &lock.packages {
        encode_package(&mut output, package);
    }
    output.push_str("    ],\n");
    encode_platform(&mut output, "build_platform", &lock.build_platform, 4);
    encode_platform(&mut output, "host_platform", &lock.host_platform, 4);
    encode_platform(&mut output, "target_platform", &lock.target_platform, 4);
    encode_identity(&mut output, "policy", &lock.policy, 4);
    encode_identity(&mut output, "target", &lock.target, 4);
    encode_identity(&mut output, "profile", &lock.profile, 4);
    encode_identity(&mut output, "toolchain", &lock.toolchain, 4);
    encode_identity(&mut output, "builder", &lock.builder, 4);
    output.push_str("}\n");
    output
}

fn encode_package(output: &mut String, package: &LockedPackage) {
    output.push_str("        {\n");
    writeln!(
        output,
        "            package_id = {},",
        gluon_string(&package.package_id)
    )
    .unwrap();
    writeln!(output, "            name = {},", gluon_string(&package.name)).unwrap();
    writeln!(output, "            version = {},", gluon_string(&package.version)).unwrap();
    writeln!(
        output,
        "            architecture = {},",
        gluon_string(&package.architecture)
    )
    .unwrap();
    writeln!(
        output,
        "            repository = {},",
        gluon_string(&package.repository)
    )
    .unwrap();
    output.push_str("            outputs = [\n");
    for locked_output in &package.outputs {
        output.push_str("                {\n");
        writeln!(
            output,
            "                    name = {},",
            gluon_string(&locked_output.name)
        )
        .unwrap();
        output.push_str("                },\n");
    }
    output.push_str("            ],\n");
    output.push_str("            dependencies = [\n");
    for dependency in &package.dependencies {
        output.push_str("                {\n");
        writeln!(
            output,
            "                    package_id = {},",
            gluon_string(&dependency.package_id)
        )
        .unwrap();
        writeln!(
            output,
            "                    output = {},",
            gluon_string(&dependency.output)
        )
        .unwrap();
        output.push_str("                },\n");
    }
    output.push_str("            ],\n");
    output.push_str("        },\n");
}

fn encode_platform(output: &mut String, field: &str, platform: &Platform, indent: usize) {
    let pad = " ".repeat(indent);
    writeln!(output, "{pad}{field} = {{").unwrap();
    writeln!(
        output,
        "{pad}    architecture = {},",
        gluon_string(&platform.architecture)
    )
    .unwrap();
    writeln!(output, "{pad}    vendor = {},", gluon_string(&platform.vendor)).unwrap();
    writeln!(
        output,
        "{pad}    operating_system = {},",
        gluon_string(&platform.operating_system)
    )
    .unwrap();
    writeln!(output, "{pad}    abi = {},", gluon_string(&platform.abi)).unwrap();
    writeln!(output, "{pad}}},").unwrap();
}

fn encode_identity(output: &mut String, field: &str, identity: &LockedIdentity, indent: usize) {
    let pad = " ".repeat(indent);
    writeln!(output, "{pad}{field} = {{").unwrap();
    writeln!(output, "{pad}    name = {},", gluon_string(&identity.name)).unwrap();
    writeln!(
        output,
        "{pad}    fingerprint = {},",
        gluon_string(&identity.fingerprint)
    )
    .unwrap();
    writeln!(output, "{pad}}},").unwrap();
}

fn gluon_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonBuildLock {
    schema_version: i64,
    request_fingerprint: String,
    repositories: Vec<GluonRepositorySnapshot>,
    requests: Vec<GluonLockedRequest>,
    packages: Vec<GluonLockedPackage>,
    build_platform: GluonPlatform,
    host_platform: GluonPlatform,
    target_platform: GluonPlatform,
    policy: GluonLockedIdentity,
    target: GluonLockedIdentity,
    profile: GluonLockedIdentity,
    toolchain: GluonLockedIdentity,
    builder: GluonLockedIdentity,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonPlatform {
    architecture: String,
    vendor: String,
    operating_system: String,
    abi: String,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonRepositorySnapshot {
    id: String,
    index_uri: String,
    snapshot: String,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonLockedIdentity {
    name: String,
    fingerprint: String,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonLockedPackage {
    package_id: String,
    name: String,
    version: String,
    architecture: String,
    repository: String,
    outputs: Vec<GluonLockedOutput>,
    dependencies: Vec<GluonLockedOutputRef>,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonLockedRequest {
    request: String,
    package_id: String,
    output: String,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonLockedOutput {
    name: String,
}

#[derive(Debug, gluon_codegen::Getable, gluon_codegen::VmType)]
struct GluonLockedOutputRef {
    package_id: String,
    output: String,
}

impl TryFrom<GluonBuildLock> for BuildLock {
    type Error = BuildLockValidationError;

    fn try_from(lock: GluonBuildLock) -> Result<Self, Self::Error> {
        Ok(Self {
            schema_version: u32::try_from(lock.schema_version).map_err(|_| {
                BuildLockValidationError::IntegerOutOfRange {
                    field: "schema_version".to_owned(),
                    value: lock.schema_version,
                    expected: "non-negative 32-bit integer",
                }
            })?,
            request_fingerprint: lock.request_fingerprint,
            repositories: lock.repositories.into_iter().map(Into::into).collect(),
            requests: lock.requests.into_iter().map(Into::into).collect(),
            packages: lock.packages.into_iter().map(Into::into).collect(),
            build_platform: lock.build_platform.into(),
            host_platform: lock.host_platform.into(),
            target_platform: lock.target_platform.into(),
            policy: lock.policy.into(),
            target: lock.target.into(),
            profile: lock.profile.into(),
            toolchain: lock.toolchain.into(),
            builder: lock.builder.into(),
        })
    }
}

impl From<GluonPlatform> for Platform {
    fn from(platform: GluonPlatform) -> Self {
        Self {
            architecture: platform.architecture,
            vendor: platform.vendor,
            operating_system: platform.operating_system,
            abi: platform.abi,
        }
    }
}

impl From<GluonRepositorySnapshot> for RepositorySnapshot {
    fn from(repository: GluonRepositorySnapshot) -> Self {
        Self {
            id: repository.id,
            index_uri: repository.index_uri,
            snapshot: repository.snapshot,
        }
    }
}

impl From<GluonLockedIdentity> for LockedIdentity {
    fn from(identity: GluonLockedIdentity) -> Self {
        Self {
            name: identity.name,
            fingerprint: identity.fingerprint,
        }
    }
}

impl From<GluonLockedPackage> for LockedPackage {
    fn from(package: GluonLockedPackage) -> Self {
        Self {
            package_id: package.package_id,
            name: package.name,
            version: package.version,
            architecture: package.architecture,
            repository: package.repository,
            outputs: package.outputs.into_iter().map(Into::into).collect(),
            dependencies: package.dependencies.into_iter().map(Into::into).collect(),
        }
    }
}

impl From<GluonLockedRequest> for LockedRequest {
    fn from(request: GluonLockedRequest) -> Self {
        Self {
            request: request.request,
            package_id: request.package_id,
            output: request.output,
        }
    }
}

impl From<GluonLockedOutput> for LockedOutput {
    fn from(output: GluonLockedOutput) -> Self {
        Self { name: output.name }
    }
}

impl From<GluonLockedOutputRef> for LockedOutputRef {
    fn from(output: GluonLockedOutputRef) -> Self {
        Self {
            package_id: output.package_id,
            output: output.output,
        }
    }
}

#[derive(Debug, Error)]
pub enum BuildLockDecodeError {
    #[error("build lock is not UTF-8")]
    Utf8(#[from] str::Utf8Error),
    #[error("evaluate build lock")]
    Evaluation(#[source] Box<Diagnostic>),
    #[error(transparent)]
    Validation(#[from] BuildLockValidationError),
}

#[derive(Debug, Error)]
pub enum BuildLockValidationError {
    #[error("schema_version: unsupported schema {found}; expected {expected}")]
    UnsupportedSchema { found: u32, expected: u32 },
    #[error("{field}: `{value}` is outside the valid {expected} range")]
    IntegerOutOfRange {
        field: String,
        value: i64,
        expected: &'static str,
    },
    #[error("{field}: value must not be empty")]
    Empty { field: String },
    #[error("repositories[{duplicate_index}].id: duplicate `{id}`, first used by repositories[{first_index}]")]
    DuplicateRepository {
        id: String,
        first_index: usize,
        duplicate_index: usize,
    },
    #[error("packages[{duplicate_index}].package_id: duplicate `{id}`, first used by packages[{first_index}]")]
    DuplicatePackage {
        id: String,
        first_index: usize,
        duplicate_index: usize,
    },
    #[error("requests[{duplicate_index}].request: duplicate `{request}`, first used by requests[{first_index}]")]
    DuplicateRequest {
        request: String,
        first_index: usize,
        duplicate_index: usize,
    },
    #[error("package `{package}` references unknown repository `{repository}`")]
    UnknownRepository { package: String, repository: String },
    #[error("repositories[{index}]: repository `{id}` is unused by the locked package closure")]
    UnusedRepository { index: usize, id: String },
    #[error("package `{package}` has no locked outputs")]
    MissingOutputs { package: String },
    #[error("package `{package}` output `{output}` is duplicated at indexes {first_index} and {duplicate_index}")]
    DuplicateOutput {
        package: String,
        output: String,
        first_index: usize,
        duplicate_index: usize,
    },
    #[error(
        "package `{package}` dependency `{dependency_package}:{output}` is duplicated at indexes {first_index} and {duplicate_index}"
    )]
    DuplicateDependency {
        package: String,
        dependency_package: String,
        output: String,
        first_index: usize,
        duplicate_index: usize,
    },
    #[error("{field}: unknown locked package `{package}`")]
    UnknownPackage { field: String, package: String },
    #[error("{field}: package `{package}` has no locked output `{output}`")]
    UnknownOutput {
        field: String,
        package: String,
        output: String,
    },
    #[error("{field}: package dependency cycle: {}", cycle.join(" -> "))]
    DependencyCycle { field: String, cycle: Vec<String> },
    #[error("packages[{index}]: locked package `{package}` is unreachable from every request")]
    UnreachablePackage { index: usize, package: String },
}

fn require_nonempty(field: &str, value: &str) -> Result<(), BuildLockValidationError> {
    if value.is_empty() {
        Err(BuildLockValidationError::Empty {
            field: field.to_owned(),
        })
    } else {
        Ok(())
    }
}

fn detect_dependency_cycles(
    packages: &[LockedPackage],
    indexes: &BTreeMap<&str, usize>,
) -> Result<(), BuildLockValidationError> {
    // 0 = unvisited, 1 = in the current DFS stack, 2 = complete.
    let mut states = vec![0_u8; packages.len()];
    let mut stack = Vec::new();
    for index in 0..packages.len() {
        visit_dependency(index, packages, indexes, &mut states, &mut stack)?;
    }
    Ok(())
}

fn require_reachable_packages(
    packages: &[LockedPackage],
    requests: &[LockedRequest],
    indexes: &BTreeMap<&str, usize>,
) -> Result<(), BuildLockValidationError> {
    let mut reachable = vec![false; packages.len()];
    let mut pending = requests
        .iter()
        .map(|request| indexes[request.package_id.as_str()])
        .collect::<Vec<_>>();

    while let Some(index) = pending.pop() {
        if std::mem::replace(&mut reachable[index], true) {
            continue;
        }
        pending.extend(
            packages[index]
                .dependencies
                .iter()
                .map(|dependency| indexes[dependency.package_id.as_str()]),
        );
    }

    if let Some((index, package)) = packages.iter().enumerate().find(|(index, _)| !reachable[*index]) {
        return Err(BuildLockValidationError::UnreachablePackage {
            index,
            package: package.package_id.clone(),
        });
    }
    Ok(())
}

fn visit_dependency(
    index: usize,
    packages: &[LockedPackage],
    indexes: &BTreeMap<&str, usize>,
    states: &mut [u8],
    stack: &mut Vec<usize>,
) -> Result<(), BuildLockValidationError> {
    if states[index] == 2 {
        return Ok(());
    }
    states[index] = 1;
    stack.push(index);

    for (dependency_index, dependency) in packages[index].dependencies.iter().enumerate() {
        // Reference validation runs before cycle detection, so every package
        // is known here.
        let target = indexes[dependency.package_id.as_str()];
        if states[target] == 1 {
            let start = stack.iter().position(|candidate| *candidate == target).unwrap_or(0);
            let mut cycle = stack[start..]
                .iter()
                .map(|package_index| packages[*package_index].package_id.clone())
                .collect::<Vec<_>>();
            cycle.push(packages[target].package_id.clone());
            return Err(BuildLockValidationError::DependencyCycle {
                field: format!("packages[{index}].dependencies[{dependency_index}]"),
                cycle,
            });
        }
        if states[target] == 0 {
            visit_dependency(target, packages, indexes, states, stack)?;
        }
    }

    stack.pop();
    states[index] = 2;
    Ok(())
}

#[cfg(test)]
pub(super) fn sample_lock() -> BuildLock {
    let platform = Platform {
        architecture: "x86_64".to_owned(),
        vendor: "unknown".to_owned(),
        operating_system: "linux".to_owned(),
        abi: "gnu".to_owned(),
    };
    BuildLock {
        schema_version: BUILD_LOCK_SCHEMA_VERSION,
        request_fingerprint: "request-fingerprint".to_owned(),
        repositories: vec![RepositorySnapshot {
            id: "volatile".to_owned(),
            index_uri: "https://example.invalid/stone.index".to_owned(),
            snapshot: "repository-snapshot".to_owned(),
        }],
        requests: vec![LockedRequest {
            request: "binary(hello)".to_owned(),
            package_id: "hello-id".to_owned(),
            output: "out".to_owned(),
        }],
        packages: vec![
            LockedPackage {
                package_id: "cmake-id".to_owned(),
                name: "cmake".to_owned(),
                version: "3.31.0-1".to_owned(),
                architecture: "x86_64".to_owned(),
                repository: "volatile".to_owned(),
                outputs: vec![LockedOutput { name: "out".to_owned() }],
                dependencies: Vec::new(),
            },
            LockedPackage {
                package_id: "hello-id".to_owned(),
                name: "hello".to_owned(),
                version: "1.0.0-1".to_owned(),
                architecture: "x86_64".to_owned(),
                repository: "volatile".to_owned(),
                outputs: vec![LockedOutput { name: "out".to_owned() }],
                dependencies: vec![LockedOutputRef {
                    package_id: "cmake-id".to_owned(),
                    output: "out".to_owned(),
                }],
            },
        ],
        build_platform: platform.clone(),
        host_platform: platform.clone(),
        target_platform: platform,
        policy: LockedIdentity {
            name: "aerynos".to_owned(),
            fingerprint: "policy-fingerprint".to_owned(),
        },
        target: LockedIdentity {
            name: "x86_64".to_owned(),
            fingerprint: "target-fingerprint".to_owned(),
        },
        profile: LockedIdentity {
            name: "default-x86_64".to_owned(),
            fingerprint: "profile-fingerprint".to_owned(),
        },
        toolchain: LockedIdentity {
            name: "llvm".to_owned(),
            fingerprint: "toolchain-fingerprint".to_owned(),
        },
        builder: LockedIdentity {
            name: "cmake".to_owned(),
            fingerprint: "builder-fingerprint".to_owned(),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_gluon_round_trips_through_restricted_evaluator() {
        let mut expected = sample_lock();
        expected.normalize();
        expected.validate().unwrap();
        let encoded = encode_build_lock(&expected);
        let decoded = decode_build_lock(BUILD_LOCK_FILE_NAME, encoded.as_bytes()).unwrap();

        assert_eq!(decoded, expected);
        assert!(encoded.starts_with(GENERATED_GLUON_MARKER));
        assert!(encoded.contains("schema_version = 2,"));
        assert!(!encoded.contains("base_state"));
        assert!(encoded.contains("    policy = {\n        name = \"aerynos\","));
        assert!(encoded.contains("    target = {\n        name = \"x86_64\","));
    }

    #[test]
    fn construction_order_does_not_change_encoding_or_digest() {
        let first = sample_lock();
        let mut reordered = first.clone();
        reordered.packages.reverse();
        reordered.packages[0].outputs.reverse();
        reordered.packages[0].dependencies.reverse();

        assert_eq!(encode_build_lock(&first), encode_build_lock(&reordered));
        assert_eq!(first.canonical_bytes(), reordered.canonical_bytes());
        assert_eq!(first.digest(), reordered.digest());
    }

    #[test]
    fn string_encoding_is_unambiguous_and_round_trips() {
        let mut lock = sample_lock();
        lock.profile.name = "quote \" slash \\ newline\n".to_owned();
        let decoded = decode_build_lock(BUILD_LOCK_FILE_NAME, encode_build_lock(&lock).as_bytes()).unwrap();

        assert_eq!(decoded.profile.name, lock.profile.name);
    }

    #[test]
    fn mutation_of_every_locked_identity_changes_digest() {
        let original = sample_lock();
        let original_digest = original.digest();
        let mutations: Vec<Box<dyn Fn(&mut BuildLock)>> = vec![
            Box::new(|lock| lock.repositories[0].snapshot.push_str("-changed")),
            Box::new(|lock| lock.requests[0].package_id.push_str("-changed")),
            Box::new(|lock| lock.packages[0].outputs[0].name.push_str("-changed")),
            Box::new(|lock| lock.target_platform.architecture = "aarch64".to_owned()),
            Box::new(|lock| lock.policy.fingerprint.push_str("-changed")),
            Box::new(|lock| lock.target.name.push_str("-changed")),
            Box::new(|lock| lock.target.fingerprint.push_str("-changed")),
            Box::new(|lock| lock.profile.fingerprint.push_str("-changed")),
            Box::new(|lock| lock.toolchain.fingerprint.push_str("-changed")),
            Box::new(|lock| lock.builder.fingerprint.push_str("-changed")),
        ];

        for mutate in mutations {
            let mut changed = original.clone();
            mutate(&mut changed);
            assert_ne!(changed.digest(), original_digest);
        }
    }

    #[test]
    fn validation_rejects_unresolved_output_references() {
        let mut lock = sample_lock();
        lock.packages[1].dependencies[0].output = "missing".to_owned();

        assert!(matches!(
            lock.validate(),
            Err(BuildLockValidationError::UnknownOutput { .. })
        ));
    }

    #[test]
    fn validation_rejects_packages_disconnected_from_all_requests() {
        let mut lock = sample_lock();
        lock.packages.push(LockedPackage {
            package_id: "orphan-id".to_owned(),
            name: "orphan".to_owned(),
            version: "1.0.0-1".to_owned(),
            architecture: "x86_64".to_owned(),
            repository: "volatile".to_owned(),
            outputs: vec![LockedOutput { name: "out".to_owned() }],
            dependencies: Vec::new(),
        });

        assert!(matches!(
            lock.validate(),
            Err(BuildLockValidationError::UnreachablePackage { index: 2, package })
                if package == "orphan-id"
        ));
    }

    #[test]
    fn validation_rejects_repository_snapshots_unused_by_the_closure() {
        let mut lock = sample_lock();
        lock.repositories.push(RepositorySnapshot {
            id: "unused".to_owned(),
            index_uri: "https://example.invalid/unused.stone.index".to_owned(),
            snapshot: "unused-snapshot".to_owned(),
        });

        assert!(matches!(
            lock.validate(),
            Err(BuildLockValidationError::UnusedRepository { index: 1, id })
                if id == "unused"
        ));
    }

    #[test]
    fn validation_requires_independent_policy_and_target_identities() {
        let mut missing_policy = sample_lock();
        missing_policy.policy.name.clear();
        assert!(matches!(
            missing_policy.validate(),
            Err(BuildLockValidationError::Empty { field }) if field == "policy.name"
        ));

        let mut missing_target = sample_lock();
        missing_target.target.fingerprint.clear();
        assert!(matches!(
            missing_target.validate(),
            Err(BuildLockValidationError::Empty { field }) if field == "target.fingerprint"
        ));
    }

    #[test]
    fn validation_rejects_dependency_cycles_with_the_closing_edge() {
        let mut lock = sample_lock();
        lock.packages[0].dependencies.push(LockedOutputRef {
            package_id: "hello-id".to_owned(),
            output: "out".to_owned(),
        });

        let error = lock.validate().unwrap_err();
        assert!(matches!(
            &error,
            BuildLockValidationError::DependencyCycle { field, cycle }
                if field == "packages[1].dependencies[0]"
                    && cycle.iter().map(String::as_str).eq(["cmake-id", "hello-id", "cmake-id"])
        ));
        assert!(error.to_string().contains("cmake-id -> hello-id -> cmake-id"));
    }

    #[test]
    fn decoder_rejects_unsupported_schema() {
        let encoded = encode_build_lock(&sample_lock()).replacen("schema_version = 2", "schema_version = 3", 1);
        let error = decode_build_lock(BUILD_LOCK_FILE_NAME, encoded.as_bytes()).unwrap_err();

        assert!(matches!(
            error,
            BuildLockDecodeError::Validation(BuildLockValidationError::UnsupportedSchema { found: 3, .. })
        ));
    }
}
