-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "target-profile-specialization",
        version = "2.0.0",
        release = 1,
        homepage = "https://example.invalid/target-profile-specialization",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "base-builder-tool"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/base-phase-runner",
                            requirement = {
                                kind = "binary",
                                value = "base-phase-runner"
                            }
                        },
                        args = {
                            "--generic"
                        }
                    }
                }
            },
            install = {
                steps = {}
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {
            {
                kind = "run",
                program = {
                    path = "/usr/bin/base-hook-runner",
                    requirement = {
                        kind = "binary",
                        value = "base-hook-runner"
                    }
                },
                args = {
                    "--generic"
                }
            }
        },
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "binary",
            value = "base-native-tool"
        }
    },
    build_inputs = {
        {
            kind = "pkg_config",
            value = "base-target-library"
        }
    },
    check_inputs = {
        {
            kind = "binary",
            value = "base-check-tool"
        }
    },
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "none"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "*"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {
        {
            name = "x86_64",
            builder = {
                required_tools = {
                    {
                        kind = "binary",
                        value = "profile-builder-tool"
                    }
                },
                environment = {},
                phases = {
                    setup = {
                        steps = {}
                    },
                    build = {
                        steps = {
                            {
                                kind = "run",
                                program = {
                                    path = "/usr/bin/profile-phase-runner",
                                    requirement = {
                                        kind = "binary",
                                        value = "profile-phase-runner"
                                    }
                                },
                                args = {
                                    "--target",
                                    "x86_64"
                                }
                            }
                        }
                    },
                    install = {
                        steps = {}
                    },
                    check = {
                        steps = {}
                    },
                    workload = {
                        steps = {}
                    }
                },
                supported_hooks = {
                    setup = true,
                    build = true,
                    check = true,
                    install = true,
                    workload = true
                }
            },
            hooks = {
                pre_setup = {},
                post_setup = {},
                pre_build = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/profile-hook-runner",
                            requirement = {
                                kind = "binary",
                                value = "profile-hook-runner"
                            }
                        },
                        args = {
                            "--target",
                            "x86_64"
                        }
                    }
                },
                post_build = {},
                pre_check = {},
                post_check = {},
                pre_install = {},
                post_install = {},
                pre_workload = {},
                post_workload = {}
            },
            native_build_inputs = {
                {
                    kind = "binary",
                    value = "profile-native-tool"
                }
            },
            build_inputs = {
                {
                    kind = "pkg_config",
                    value = "profile-target-library"
                }
            },
            check_inputs = {
                {
                    kind = "binary",
                    value = "profile-check-tool"
                }
            }
        }
    },
    sources = {},
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}