-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "wire-schema-runtime",
        version = "2.0.0",
        release = 1,
        homepage = "https://example.invalid/wire-schema",
        license = {
            "Apache-2.0"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "mkdir"
            },
            {
                kind = "output",
                value = {
                    package = {
                        name = "wire-schema"
                    },
                    output = "compiler"
                }
            },
            {
                kind = "binary",
                value = "cc"
            },
            {
                kind = "binary",
                value = "install"
            },
            {
                kind = "binary",
                value = "ln"
            },
            {
                kind = "binary",
                value = "test"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/mkdir",
                            requirement = {
                                kind = "binary",
                                value = "mkdir"
                            }
                        },
                        args = {
                            "-p",
                            "build"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/libexec/wire-schema/wire-codegen",
                            requirement = {
                                kind = "output",
                                value = {
                                    package = {
                                        name = "wire-schema"
                                    },
                                    output = "compiler"
                                }
                            }
                        },
                        args = {
                            "--language",
                            "c",
                            "--input",
                            "protocol/wire.schema",
                            "--header",
                            "build/wire-schema.h",
                            "--source",
                            "build/wire-schema.c"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-fPIC",
                            "-O2",
                            "-c",
                            "build/wire-schema.c",
                            "-o",
                            "build/wire-schema.o"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/cc",
                            requirement = {
                                kind = "binary",
                                value = "cc"
                            }
                        },
                        args = {
                            "-shared",
                            "-Wl,-soname,libwire-schema.so.2",
                            "build/wire-schema.o",
                            "-o",
                            "build/libwire-schema.so.2.0.0"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            },
                            {
                                path = "/usr/bin/ln",
                                requirement = {
                                    kind = "binary",
                                    value = "ln"
                                }
                            }
                        },
                        script = "\ninstall -Dm644 protocol/wire.schema \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/wire-schema/wire.schema\"\ninstall -Dm755 build/libwire-schema.so.2.0.0 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libwire-schema.so.2.0.0\"\nln -s libwire-schema.so.2.0.0 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libwire-schema.so.2\"\nln -s libwire-schema.so.2 \"${CAST_INSTALL_ROOT}${CAST_LIBDIR}/libwire-schema.so\"\ninstall -Dm644 build/wire-schema.h \"${CAST_INSTALL_ROOT}${CAST_PREFIX}/include/wire-schema/wire-schema.h\"\n"
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/test",
                            requirement = {
                                kind = "binary",
                                value = "test"
                            }
                        },
                        args = {
                            "-s",
                            "build/wire-schema.c"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/test",
                            requirement = {
                                kind = "binary",
                                value = "test"
                            }
                        },
                        args = {
                            "-s",
                            "build/wire-schema.h"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Wire protocol schema data"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/wire-schema"
                }
            },
            conflicts = {}
        },
        {
            name = "libs",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Generated wire schema runtime library"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/lib/libwire-schema.so.*"
                }
            },
            conflicts = {}
        },
        {
            name = "devel",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Generated wire schema C interface"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "output",
                    value = {
                        package = {
                            name = "wire-schema-runtime"
                        },
                        output = "libs"
                    }
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/include/wire-schema"
                },
                {
                    kind = "symlink",
                    path = "/usr/lib/libwire-schema.so"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/wire-schema-runtime-2.0.0.tar.xz",
            hash = "789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "x86_64",
        "aarch64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}