-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-relation-policy-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-relation-policy-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        kind = "custom",
        spec = {
            required_tools = {
                {
                    kind = "binary",
                    value = "bash"
                },
                {
                    kind = "binary",
                    value = "install"
                }
            },
            environment = {},
            phases = {
                setup = {
                    steps = {}
                },
                build = {
                    steps = {}
                },
                install = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/bash",
                                requirement = {
                                    kind = "binary",
                                    value = "bash"
                                }
                            },
                            declared_programs = {
                                {
                                    path = "/usr/bin/install",
                                    requirement = {
                                        kind = "binary",
                                        value = "install"
                                    }
                                }
                            },
                            script = "\nprintf '%s\\n' \\\n    'schema = 1' \\\n    'native-build = \"sysbinary(ldconfig)\"' \\\n    'build = \"pkgconfig32(zlib)\"' \\\n    'runtime-interpreter = \"interpreter(/usr/lib/ld-linux-x86-64.so.2(x86_64))\"' \\\n    'runtime-library = \"soname(libz.so.1(x86_64))\"' \\\n    > relation-policy.conf\ninstall -Dm644 relation-policy.conf \\\n    \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/cast/relation-policy.conf\"\n"
                        }
                    }
                },
                check = {
                    steps = {}
                },
                workload = {
                    steps = {}
                }
            },
            supported_hooks = {
                setup = true,
                build = true,
                check = true,
                install = true,
                workload = true
            }
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {
        {
            kind = "system_binary",
            value = "ldconfig"
        }
    },
    build_inputs = {
        {
            kind = "pkg_config32",
            value = "zlib"
        }
    },
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Typed dependency-role policy fixture"
            },
            description = {
                kind = "some",
                value = "Pinned build and runtime capabilities with exact provider identities."
            },
            provides_exclude = {},
            runtime_inputs = {
                {
                    kind = "interpreter",
                    value = "/usr/lib/ld-linux-x86-64.so.2(x86_64)"
                },
                {
                    kind = "soname",
                    value = "libz.so.1(x86_64)"
                }
            },
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/cast/relation-policy.conf"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {},
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}