-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "aster-fonts",
        version = "1.3.0",
        release = 1,
        homepage = "https://example.invalid/aster-fonts",
        license = {
            "OFL-1.1"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "\ninstall -d \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/fonts/truetype/aster\"\ninstall -m644 fonts/*.otf \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/fonts/truetype/aster/\"\ninstall -Dm644 OFL.txt \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/doc/aster-fonts/OFL.txt\"\n"
                    }
                }
            },
            check = {
                steps = {}
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Aster text and display fonts"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/fonts/truetype/aster"
                }
            },
            conflicts = {}
        },
        {
            name = "docs",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "Aster font license"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/doc/aster-fonts"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/aster-fonts-1.3.0.tar.gz",
            hash = "3456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef012",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "aster-fonts"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}