//! Pure destination planning for an ActiveReblit boot publication.
//!
//! This module owns no filesystem descriptors and performs no path I/O.  It
//! turns already-sealed payloads and already-generated control bytes into one
//! bounded, canonical publication list for the later descriptor-safe worker.

use std::{
    collections::BTreeMap,
    os::unix::ffi::OsStrExt,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

use thiserror::Error;

pub(in crate::client) const ACTIVE_REBLIT_BOOT_OUTPUT_MODE: u32 = 0o644;
pub(in crate::client) const MAX_ACTIVE_REBLIT_BOOT_PUBLICATIONS: usize = 8_336;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_PATH_BYTES: usize = 8 * 1024 * 1024;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_COMPONENTS: usize = 16;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_SINGLE_PATH_BYTES: usize = nix::libc::PATH_MAX as usize - 1;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_LOGICAL_BYTES: u64 = 10 * 1024 * 1024 * 1024;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_SEALED_FILE_BYTES: u64 = 512 * 1024 * 1024;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_GENERATED_BYTES: usize = 16 * 1024 * 1024;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_GENERATED_FILE_BYTES: usize = 1024 * 1024;
const MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_WORK: usize = 1_000_000;
const ACTIVE_REBLIT_BOOT_PUBLICATION_TIMEOUT: Duration = Duration::from_secs(30);

/// The pre-opened destination root selected by the later publication worker.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub(in crate::client) enum ActiveReblitBootDestinationRoot {
    Esp,
    Boot,
}

/// Publication order, from independent payloads through control-plane files.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub(in crate::client) enum ActiveReblitBootPublicationPhase {
    Payload,
    Entry,
    LoaderControl,
    Bootloader,
}

/// Immutable bytes backing one planned destination.
///
/// This type is deliberately non-`Clone`: generated bytes have one owner and
/// sealed snapshot identity must not silently fan out outside the plan.
#[derive(Debug, Eq, PartialEq)]
pub(in crate::client) enum ActiveReblitBootPublicationSource {
    SealedSnapshot { digest: u128, length: u64 },
    Generated { bytes: Box<[u8]>, digest: u128 },
}

impl ActiveReblitBootPublicationSource {
    pub(in crate::client) fn digest(&self) -> u128 {
        match self {
            Self::SealedSnapshot { digest, .. } | Self::Generated { digest, .. } => *digest,
        }
    }

    pub(in crate::client) fn length(&self) -> u64 {
        match self {
            Self::SealedSnapshot { length, .. } => *length,
            Self::Generated { bytes, .. } => u64::try_from(bytes.len()).expect("usize fits in u64"),
        }
    }

    pub(in crate::client) fn generated_bytes(&self) -> Option<&[u8]> {
        match self {
            Self::Generated { bytes, .. } => Some(bytes),
            Self::SealedSnapshot { .. } => None,
        }
    }
}

/// An owned declaration admitted by [`PreparedActiveReblitBootPublicationPlan`].
///
/// The destination mode is intentionally absent. Every admitted output has the
/// single fixed mode [`ACTIVE_REBLIT_BOOT_OUTPUT_MODE`].
pub(in crate::client) struct ActiveReblitBootPublicationRequest {
    root: ActiveReblitBootDestinationRoot,
    phase: ActiveReblitBootPublicationPhase,
    relative_path: PathBuf,
    source: ActiveReblitBootPublicationSource,
}

impl ActiveReblitBootPublicationRequest {
    pub(in crate::client) fn sealed_snapshot(
        root: ActiveReblitBootDestinationRoot,
        phase: ActiveReblitBootPublicationPhase,
        relative_path: PathBuf,
        digest: u128,
        length: u64,
    ) -> Self {
        Self {
            root,
            phase,
            relative_path,
            source: ActiveReblitBootPublicationSource::SealedSnapshot { digest, length },
        }
    }

    pub(in crate::client) fn generated(
        root: ActiveReblitBootDestinationRoot,
        phase: ActiveReblitBootPublicationPhase,
        relative_path: PathBuf,
        bytes: Box<[u8]>,
        digest: u128,
    ) -> Self {
        Self {
            root,
            phase,
            relative_path,
            source: ActiveReblitBootPublicationSource::Generated { bytes, digest },
        }
    }
}

/// One canonical, executor-visible output.
///
/// Instances are created only by the prepared plan, after collision and bound
/// checks. The type is deliberately non-`Clone`.
#[derive(Debug, Eq, PartialEq)]
pub(in crate::client) struct PlannedActiveReblitBootPublication {
    root: ActiveReblitBootDestinationRoot,
    phase: ActiveReblitBootPublicationPhase,
    relative_path: PathBuf,
    source: ActiveReblitBootPublicationSource,
}

impl PlannedActiveReblitBootPublication {
    pub(in crate::client) fn root(&self) -> ActiveReblitBootDestinationRoot {
        self.root
    }

    pub(in crate::client) fn phase(&self) -> ActiveReblitBootPublicationPhase {
        self.phase
    }

    pub(in crate::client) fn relative_path(&self) -> &Path {
        &self.relative_path
    }

    pub(in crate::client) fn mode(&self) -> u32 {
        ACTIVE_REBLIT_BOOT_OUTPUT_MODE
    }

    pub(in crate::client) fn source(&self) -> &ActiveReblitBootPublicationSource {
        &self.source
    }
}

/// Complete, bounded publication input for the descriptor-safe executor.
///
/// There is intentionally no removal list and no mutation API. The executor
/// can only inspect the canonical outputs and their aggregate bounds.
#[derive(Debug)]
pub(in crate::client) struct PreparedActiveReblitBootPublicationPlan {
    outputs: Vec<PlannedActiveReblitBootPublication>,
    logical_bytes: u64,
    generated_bytes: usize,
    path_bytes: usize,
    planning_work: usize,
}

impl PreparedActiveReblitBootPublicationPlan {
    pub(in crate::client) fn prepare(
        requests: impl IntoIterator<Item = ActiveReblitBootPublicationRequest>,
    ) -> Result<Self, ActiveReblitBootPublicationPlanError> {
        prepare_publication_plan(requests, PublicationPlanPolicy::production(), None)
    }

    pub(in crate::client) fn outputs(&self) -> &[PlannedActiveReblitBootPublication] {
        &self.outputs
    }

    pub(in crate::client) fn logical_bytes(&self) -> u64 {
        self.logical_bytes
    }

    pub(in crate::client) fn generated_bytes(&self) -> usize {
        self.generated_bytes
    }

    pub(in crate::client) fn path_bytes(&self) -> usize {
        self.path_bytes
    }

    pub(in crate::client) fn planning_work(&self) -> usize {
        self.planning_work
    }
}

#[derive(Debug, Error, Eq, PartialEq)]
pub(in crate::client) enum ActiveReblitBootPublicationPlanError {
    #[error("cannot represent the {timeout:?} boot publication planning deadline")]
    InvalidDeadline { timeout: Duration },
    #[error("boot publication planning exceeded its {timeout:?} deadline")]
    DeadlineExceeded { timeout: Duration },
    #[error("boot publication count {actual} exceeds limit {limit}")]
    PublicationCountLimit { limit: usize, actual: usize },
    #[error("boot publication path bytes {actual} exceed limit {limit}")]
    PathByteLimit { limit: usize, actual: usize },
    #[error("boot publication path {path:?} has {actual} bytes, exceeding limit {limit}")]
    SinglePathByteLimit { path: PathBuf, limit: usize, actual: usize },
    #[error("boot publication path {path:?} has {actual} components, exceeding limit {limit}")]
    PathComponentLimit { path: PathBuf, limit: usize, actual: usize },
    #[error("boot publication path is empty")]
    EmptyPath,
    #[error("boot publication path {path:?} is absolute")]
    AbsolutePath { path: PathBuf },
    #[error("boot publication path {path:?} contains an empty component")]
    EmptyPathComponent { path: PathBuf },
    #[error("boot publication path {path:?} contains a dot component")]
    DotPathComponent { path: PathBuf },
    #[error("boot publication path {path:?} contains a parent component")]
    ParentPathComponent { path: PathBuf },
    #[error("boot publication path {path:?} contains NUL")]
    NulPath { path: PathBuf },
    #[error("boot publication path {path:?} is not UTF-8")]
    NonUtf8Path { path: PathBuf },
    #[error("boot publication path {path:?} contains a control character")]
    ControlPathComponent { path: PathBuf },
    #[error("boot publication path {path:?} contains a non-ASCII component")]
    NonAsciiPathComponent { path: PathBuf },
    #[error("sealed boot output {path:?} has {actual} bytes, exceeding limit {limit}")]
    SealedSnapshotFileByteLimit { path: PathBuf, limit: u64, actual: u64 },
    #[error("generated boot output {path:?} has {actual} bytes, exceeding limit {limit}")]
    GeneratedFileByteLimit { path: PathBuf, limit: usize, actual: usize },
    #[error("generated boot output bytes {actual} exceed limit {limit}")]
    GeneratedTotalByteLimit { limit: usize, actual: usize },
    #[error("logical boot publication bytes {actual} exceed limit {limit}")]
    LogicalByteLimit { limit: u64, actual: u64 },
    #[error("boot publication planning work {actual} exceeds limit {limit}")]
    WorkLimit { limit: usize, actual: usize },
    #[error("generated boot output {path:?} digest does not match its owned bytes")]
    GeneratedDigestMismatch { path: PathBuf },
    #[error("boot publication path {path:?} is declared with conflicting content or role under {root:?}")]
    PublicationCollision {
        root: ActiveReblitBootDestinationRoot,
        path: PathBuf,
    },
    #[error("boot publication paths {first:?} and {second:?} collide case-insensitively under {root:?}")]
    CaseInsensitiveCollision {
        root: ActiveReblitBootDestinationRoot,
        first: PathBuf,
        second: PathBuf,
    },
}

#[derive(Clone, Copy)]
struct PublicationPlanPolicy {
    max_publications: usize,
    max_path_bytes: usize,
    max_single_path_bytes: usize,
    max_components: usize,
    max_logical_bytes: u64,
    max_sealed_file_bytes: u64,
    max_generated_bytes: usize,
    max_generated_file_bytes: usize,
    max_work: usize,
    timeout: Duration,
}

impl PublicationPlanPolicy {
    const fn production() -> Self {
        Self {
            max_publications: MAX_ACTIVE_REBLIT_BOOT_PUBLICATIONS,
            max_path_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_PATH_BYTES,
            max_single_path_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_SINGLE_PATH_BYTES,
            max_components: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_COMPONENTS,
            max_logical_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_LOGICAL_BYTES,
            max_sealed_file_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_SEALED_FILE_BYTES,
            max_generated_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_GENERATED_BYTES,
            max_generated_file_bytes: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_GENERATED_FILE_BYTES,
            max_work: MAX_ACTIVE_REBLIT_BOOT_PUBLICATION_WORK,
            timeout: ACTIVE_REBLIT_BOOT_PUBLICATION_TIMEOUT,
        }
    }
}

struct PublicationPlanBudget {
    policy: PublicationPlanPolicy,
    deadline: Instant,
    work: usize,
    publications: usize,
    path_bytes: usize,
    declared_generated_bytes: usize,
}

impl PublicationPlanBudget {
    fn new(
        policy: PublicationPlanPolicy,
        explicit_deadline: Option<Instant>,
    ) -> Result<Self, ActiveReblitBootPublicationPlanError> {
        let deadline = match explicit_deadline {
            Some(deadline) => deadline,
            None => Instant::now().checked_add(policy.timeout).ok_or(
                ActiveReblitBootPublicationPlanError::InvalidDeadline {
                    timeout: policy.timeout,
                },
            )?,
        };
        Ok(Self {
            policy,
            deadline,
            work: 0,
            publications: 0,
            path_bytes: 0,
            declared_generated_bytes: 0,
        })
    }

    fn step(&mut self) -> Result<(), ActiveReblitBootPublicationPlanError> {
        if Instant::now() > self.deadline {
            return Err(ActiveReblitBootPublicationPlanError::DeadlineExceeded {
                timeout: self.policy.timeout,
            });
        }
        self.work = self.work.checked_add(1).unwrap_or(usize::MAX);
        if self.work > self.policy.max_work {
            return Err(ActiveReblitBootPublicationPlanError::WorkLimit {
                limit: self.policy.max_work,
                actual: self.work,
            });
        }
        Ok(())
    }

    fn admit_request(&mut self, path: &Path) -> Result<(), ActiveReblitBootPublicationPlanError> {
        self.step()?;
        let publications = self.publications.saturating_add(1);
        if publications > self.policy.max_publications {
            return Err(ActiveReblitBootPublicationPlanError::PublicationCountLimit {
                limit: self.policy.max_publications,
                actual: publications,
            });
        }
        let path_bytes = self
            .path_bytes
            .checked_add(path.as_os_str().as_bytes().len())
            .unwrap_or(usize::MAX);
        if path_bytes > self.policy.max_path_bytes {
            return Err(ActiveReblitBootPublicationPlanError::PathByteLimit {
                limit: self.policy.max_path_bytes,
                actual: path_bytes,
            });
        }
        self.publications = publications;
        self.path_bytes = path_bytes;
        Ok(())
    }

    fn admit_generated(&mut self, path: &Path, bytes: usize) -> Result<(), ActiveReblitBootPublicationPlanError> {
        self.step()?;
        if bytes > self.policy.max_generated_file_bytes {
            return Err(ActiveReblitBootPublicationPlanError::GeneratedFileByteLimit {
                path: path.to_owned(),
                limit: self.policy.max_generated_file_bytes,
                actual: bytes,
            });
        }
        let total = self.declared_generated_bytes.checked_add(bytes).unwrap_or(usize::MAX);
        if total > self.policy.max_generated_bytes {
            return Err(ActiveReblitBootPublicationPlanError::GeneratedTotalByteLimit {
                limit: self.policy.max_generated_bytes,
                actual: total,
            });
        }
        self.declared_generated_bytes = total;
        Ok(())
    }
}

fn prepare_publication_plan(
    requests: impl IntoIterator<Item = ActiveReblitBootPublicationRequest>,
    policy: PublicationPlanPolicy,
    explicit_deadline: Option<Instant>,
) -> Result<PreparedActiveReblitBootPublicationPlan, ActiveReblitBootPublicationPlanError> {
    let mut budget = PublicationPlanBudget::new(policy, explicit_deadline)?;
    let mut outputs = Vec::<PlannedActiveReblitBootPublication>::new();
    let mut destinations = BTreeMap::<(ActiveReblitBootDestinationRoot, String), usize>::new();

    for request in requests {
        budget.admit_request(&request.relative_path)?;
        let relative_path = require_normalized_relative_path(&request.relative_path, &mut budget)?;
        require_valid_source(&relative_path, &request.source, &mut budget)?;
        budget.step()?;

        let folded = case_folded_path(&relative_path);
        let key = (request.root, folded);
        if let Some(existing_index) = destinations.get(&key).copied() {
            let existing = &outputs[existing_index];
            if exact_duplicate(existing, &request, &relative_path) {
                continue;
            }
            if existing.relative_path == relative_path {
                return Err(ActiveReblitBootPublicationPlanError::PublicationCollision {
                    root: request.root,
                    path: relative_path,
                });
            }
            return Err(ActiveReblitBootPublicationPlanError::CaseInsensitiveCollision {
                root: request.root,
                first: existing.relative_path.clone(),
                second: relative_path,
            });
        }

        destinations.insert(key, outputs.len());
        outputs.push(PlannedActiveReblitBootPublication {
            root: request.root,
            phase: request.phase,
            relative_path,
            source: request.source,
        });
    }

    budget.step()?;
    outputs.sort_by(|left, right| {
        (
            left.phase,
            left.root,
            case_folded_path(&left.relative_path),
            &left.relative_path,
        )
            .cmp(&(
                right.phase,
                right.root,
                case_folded_path(&right.relative_path),
                &right.relative_path,
            ))
    });

    let mut logical_bytes = 0u64;
    let mut generated_bytes = 0usize;
    let mut canonical_path_bytes = 0usize;
    for output in &outputs {
        budget.step()?;
        canonical_path_bytes = canonical_path_bytes
            .checked_add(output.relative_path.as_os_str().as_bytes().len())
            .expect("canonical path bytes are bounded by the admission budget");
        logical_bytes = logical_bytes.checked_add(output.source.length()).unwrap_or(u64::MAX);
        if logical_bytes > policy.max_logical_bytes {
            return Err(ActiveReblitBootPublicationPlanError::LogicalByteLimit {
                limit: policy.max_logical_bytes,
                actual: logical_bytes,
            });
        }
        if let Some(bytes) = output.source.generated_bytes() {
            generated_bytes = generated_bytes.checked_add(bytes.len()).unwrap_or(usize::MAX);
        }
    }

    Ok(PreparedActiveReblitBootPublicationPlan {
        outputs,
        logical_bytes,
        generated_bytes,
        path_bytes: canonical_path_bytes,
        planning_work: budget.work,
    })
}

fn require_normalized_relative_path(
    path: &Path,
    budget: &mut PublicationPlanBudget,
) -> Result<PathBuf, ActiveReblitBootPublicationPlanError> {
    let bytes = path.as_os_str().as_bytes();
    if bytes.is_empty() {
        return Err(ActiveReblitBootPublicationPlanError::EmptyPath);
    }
    if bytes.contains(&0) {
        return Err(ActiveReblitBootPublicationPlanError::NulPath { path: path.to_owned() });
    }
    let Some(text) = path.to_str() else {
        return Err(ActiveReblitBootPublicationPlanError::NonUtf8Path { path: path.to_owned() });
    };
    if path.is_absolute() || text.starts_with('/') {
        return Err(ActiveReblitBootPublicationPlanError::AbsolutePath { path: path.to_owned() });
    }
    if bytes.len() > budget.policy.max_single_path_bytes {
        return Err(ActiveReblitBootPublicationPlanError::SinglePathByteLimit {
            path: path.to_owned(),
            limit: budget.policy.max_single_path_bytes,
            actual: bytes.len(),
        });
    }

    let mut component_count = 0usize;
    for component in text.split('/') {
        budget.step()?;
        component_count = component_count.saturating_add(1);
        if component_count > budget.policy.max_components {
            return Err(ActiveReblitBootPublicationPlanError::PathComponentLimit {
                path: path.to_owned(),
                limit: budget.policy.max_components,
                actual: component_count,
            });
        }
        if component.is_empty() {
            return Err(ActiveReblitBootPublicationPlanError::EmptyPathComponent { path: path.to_owned() });
        }
        if component == "." {
            return Err(ActiveReblitBootPublicationPlanError::DotPathComponent { path: path.to_owned() });
        }
        if component == ".." {
            return Err(ActiveReblitBootPublicationPlanError::ParentPathComponent { path: path.to_owned() });
        }
        if component.chars().any(char::is_control) {
            return Err(ActiveReblitBootPublicationPlanError::ControlPathComponent { path: path.to_owned() });
        }
        if !component.is_ascii() {
            return Err(ActiveReblitBootPublicationPlanError::NonAsciiPathComponent { path: path.to_owned() });
        }
    }

    Ok(PathBuf::from(text))
}

fn require_valid_source(
    path: &Path,
    source: &ActiveReblitBootPublicationSource,
    budget: &mut PublicationPlanBudget,
) -> Result<(), ActiveReblitBootPublicationPlanError> {
    match source {
        ActiveReblitBootPublicationSource::SealedSnapshot { length, .. } => {
            budget.step()?;
            if *length > budget.policy.max_sealed_file_bytes {
                return Err(ActiveReblitBootPublicationPlanError::SealedSnapshotFileByteLimit {
                    path: path.to_owned(),
                    limit: budget.policy.max_sealed_file_bytes,
                    actual: *length,
                });
            }
            Ok(())
        }
        ActiveReblitBootPublicationSource::Generated { bytes, digest } => {
            budget.admit_generated(path, bytes.len())?;
            if xxhash_rust::xxh3::xxh3_128(bytes) != *digest {
                return Err(ActiveReblitBootPublicationPlanError::GeneratedDigestMismatch { path: path.to_owned() });
            }
            Ok(())
        }
    }
}

fn exact_duplicate(
    existing: &PlannedActiveReblitBootPublication,
    request: &ActiveReblitBootPublicationRequest,
    relative_path: &Path,
) -> bool {
    existing.root == request.root
        && existing.phase == request.phase
        && existing.relative_path == relative_path
        && existing.source == request.source
}

fn case_folded_path(path: &Path) -> String {
    path.to_str()
        .expect("validated publication paths are UTF-8")
        .to_ascii_lowercase()
}

#[cfg(test)]
#[path = "active_reblit_publication_plan_tests.rs"]
mod tests;
