use std::path::Path;

use declarative_config::{
    AbiCatalog, EngineAdapter, EngineId, Evaluation as CoreEvaluation, EvaluationDeadline,
    IdentityInputs, ImportRequest, LanguageId, LanguageSpec, Limits, ModuleView,
    NormalizedRelative, PreparedGraph, Source, SourceRoot, TypedDecoder,
    evaluate as evaluate_declaration, evaluate_file as evaluate_declaration_file,
    evaluate_with_inputs as evaluate_declaration_with_inputs,
};
use gluon::{
    RootedThread, ThreadExt,
    import::{Import, add_extern_module},
    query::CompilationBase,
    vm::{api::{Getable, VmType}, thread::ThreadInternal},
};

use crate::{
    Diagnostic, EvaluationFingerprint, GLUON_VERSION, ModuleFingerprint,
    decoder::GluonGetable,
    import::{
        ImportPolicy, PreparedImports, RestrictedImporter, discover_imports,
        normalize_relative_import,
    },
    runtime::run_until_deadline,
};

pub const GLUON_GENERATED_MARKER: &str = "// @generated by os-tools. DO NOT EDIT.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Evaluation<T> {
    pub value: T,
    pub fingerprint: EvaluationFingerprint,
}

impl<T> From<CoreEvaluation<T, EvaluationFingerprint>> for Evaluation<T> {
    fn from(evaluation: CoreEvaluation<T, EvaluationFingerprint>) -> Self {
        Self {
            value: evaluation.value,
            fingerprint: evaluation.identity,
        }
    }
}

/// The Gluon implementation of the shared declaration-engine contract.
#[derive(Debug, Clone)]
pub struct GluonEngine {
    limits: Limits,
    source_root: Option<SourceRoot>,
    import_policy: ImportPolicy,
    language_spec: LanguageSpec,
}

impl Default for GluonEngine {
    fn default() -> Self {
        Self::new(Limits::default())
    }
}

impl GluonEngine {
    pub fn new(limits: Limits) -> Self {
        let language_spec = LanguageSpec::new(
            LanguageId::new("gluon").expect("Gluon language identifier is canonical"),
            EngineId::new("gluon-vm", GLUON_VERSION)
                .expect("Gluon engine identifier is canonical"),
            "glu",
            "declaration-v1",
            GLUON_GENERATED_MARKER,
        )
        .expect("Gluon language profile is canonical");
        Self {
            limits,
            source_root: None,
            import_policy: ImportPolicy::default(),
            language_spec,
        }
    }

    pub fn with_source_root(mut self, source_root: SourceRoot) -> Self {
        self.source_root = Some(source_root);
        self
    }

    pub fn with_import_policy(mut self, import_policy: ImportPolicy) -> Self {
        self.import_policy = import_policy;
        self
    }

    pub fn import_policy(&self) -> &ImportPolicy {
        &self.import_policy
    }

    pub fn limits(&self) -> Limits {
        self.limits
    }

    pub fn language_spec(&self) -> &LanguageSpec {
        &self.language_spec
    }

    pub fn evaluate<T>(&self, source: &Source) -> Result<Evaluation<T>, Diagnostic>
    where
        T: VmType + Send,
        for<'vm, 'value> T: Getable<'vm, 'value>,
    {
        evaluate_declaration(self, source, GluonGetable::new()).map(Into::into)
    }

    pub fn evaluate_with_inputs<T>(
        &self,
        source: &Source,
        explicit_inputs: &[u8],
    ) -> Result<Evaluation<T>, Diagnostic>
    where
        T: VmType + Send,
        for<'vm, 'value> T: Getable<'vm, 'value>,
    {
        evaluate_declaration_with_inputs(
            self,
            source,
            explicit_inputs,
            GluonGetable::new(),
        )
        .map(Into::into)
    }

    pub fn evaluate_file<T>(
        &self,
        relative: impl AsRef<Path>,
    ) -> Result<Evaluation<T>, Diagnostic>
    where
        T: VmType + Send,
        for<'vm, 'value> T: Getable<'vm, 'value>,
    {
        evaluate_declaration_file(self, relative, GluonGetable::new()).map(Into::into)
    }

    fn build_vm(&self, imports: &PreparedImports) -> RootedThread {
        let vm = RootedThread::new();
        let import = Import::new(RestrictedImporter::allowing(imports.allowed_modules()));
        import.set_paths(Vec::new());
        vm.get_macros().insert("import".to_owned(), import);
        add_extern_module(&vm, "std.array.prim", gluon::vm::primitives::load_array);
        add_extern_module(&vm, "std.string.prim", gluon::vm::primitives::load_string);
        {
            let mut database = vm.get_database_mut();
            database.set_implicit_prelude(false);
            database.set_use_standard_lib(false);
            database.set_run_io(false);
            for (logical_name, source) in imports.module_sources() {
                database.add_module(logical_name.to_owned(), source);
            }
        }
        vm.set_memory_limit(self.limits.memory_bytes);
        vm.context().set_max_stack_size(self.limits.max_stack_size);
        vm
    }
}

impl EngineAdapter for GluonEngine {
    type Discovery = RootedThread;
    type Prepared = PreparedGraph;
    type Runtime = RootedThread;
    type Identity = EvaluationFingerprint;

    fn language_spec(&self) -> &LanguageSpec {
        &self.language_spec
    }

    fn limits(&self) -> Limits {
        self.limits
    }

    fn source_root(&self) -> Option<&SourceRoot> {
        self.source_root.as_ref()
    }

    fn abi_catalog(&self) -> &AbiCatalog {
        self.import_policy.catalog()
    }

    fn begin_discovery(
        &self,
        _deadline: EvaluationDeadline,
    ) -> Result<Self::Discovery, Diagnostic> {
        Ok(self.build_vm(&PreparedImports::empty()))
    }

    fn discover_imports(
        &self,
        discovery: &mut Self::Discovery,
        module: ModuleView<'_>,
        _deadline: EvaluationDeadline,
    ) -> Result<Vec<ImportRequest>, Diagnostic> {
        discover_imports(discovery, module)
    }

    fn normalize_relative(&self, requested: &str) -> Result<NormalizedRelative, String> {
        normalize_relative_import(&self.import_policy, requested)
    }

    fn build_identity(
        &self,
        inputs: IdentityInputs<'_>,
        deadline: EvaluationDeadline,
    ) -> Result<Self::Identity, Diagnostic> {
        let fingerprints = inputs
            .graph()
            .fingerprints()
            .map(|fingerprint| ModuleFingerprint {
                logical_name: fingerprint.logical_name.clone(),
                sha256: fingerprint.sha256.clone(),
            })
            .collect();
        let source_name = inputs.root().logical_name();
        let mut checkpoint = || deadline.check(source_name);
        EvaluationFingerprint::new_checked(
            inputs.root(),
            fingerprints,
            inputs.explicit_inputs(),
            &mut checkpoint,
        )
    }

    fn prepare(
        &self,
        discovery: Self::Discovery,
        graph: PreparedGraph,
        _deadline: EvaluationDeadline,
    ) -> Result<Self::Prepared, Diagnostic> {
        drop(discovery);
        Ok(graph)
    }

    fn create_runtime(
        &self,
        prepared: Self::Prepared,
        _deadline: EvaluationDeadline,
    ) -> Result<Self::Runtime, Diagnostic> {
        Ok(self.build_vm(&PreparedImports::from_graph(prepared)))
    }

    fn execute<D>(
        &self,
        runtime: Self::Runtime,
        source: &Source,
        deadline: EvaluationDeadline,
        decoder: D,
    ) -> Result<D::Output, Diagnostic>
    where
        D: TypedDecoder<Self::Runtime>,
    {
        run_until_deadline(runtime, source, deadline, decoder)
    }
}
