-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-custom-fixture-1.0.0.tar",
            sha256 = "76cf98a8eef6104059a60cd78e839f94c279ee2a415c36bc98bc3793b416838c"
        },
    },
}