-- @generated by cast. DO NOT EDIT.
return {
    schema_version = 2,
    sources = {
        {
            kind = "archive",
            order = 0,
            url = "https://fixtures.invalid/sources/cast-post-install-smoke-test-fixture-1.0.0.tar",
            sha256 = "76796dcbea00da45083634a3784f6a3ced54d1445f58f4777ebc2d8dc01c4a94"
        },
    },
}