-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-pgo-workload-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-pgo-workload-fixture",
        license = {
            "MPL-2.0"
        }
    },
    builder = {
        kind = "custom",
        spec = {
            required_tools = {
                {
                    kind = "binary",
                    value = "mkdir"
                },
                {
                    kind = "binary",
                    value = "clang"
                },
                {
                    kind = "binary",
                    value = "dash"
                },
                {
                    kind = "binary",
                    value = "install"
                }
            },
            environment = {},
            phases = {
                setup = {
                    steps = {
                        {
                            kind = "run",
                            program = {
                                path = "/usr/bin/mkdir",
                                requirement = {
                                    kind = "binary",
                                    value = "mkdir"
                                }
                            },
                            args = {
                                "-p",
                                "build"
                            }
                        }
                    }
                },
                build = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/dash",
                                requirement = {
                                    kind = "binary",
                                    value = "dash"
                                }
                            },
                            declared_programs = {
                                {
                                    path = "/usr/bin/clang",
                                    requirement = {
                                        kind = "binary",
                                        value = "clang"
                                    }
                                }
                            },
                            script = "set -eu\ncase \"${PGO_STAGE}\" in\n    ONE)\n        test ! -e build/stage1-only.marker\n        : > build/stage1-only.marker\n        ;;\n    USE)\n        test ! -e build/stage1-only.marker\n        ;;\n    *)\n        exit 1\n        ;;\nesac\n\"${CC}\" ${CFLAGS} -std=c11 -Wall -Wextra -Werror main.c ${LDFLAGS} -o build/cast-pgo-workload-fixture"
                        }
                    }
                },
                install = {
                    steps = {
                        {
                            kind = "shell",
                            interpreter = {
                                path = "/usr/bin/dash",
                                requirement = {
                                    kind = "binary",
                                    value = "dash"
                                }
                            },
                            declared_programs = {
                                {
                                    path = "/usr/bin/install",
                                    requirement = {
                                        kind = "binary",
                                        value = "install"
                                    }
                                }
                            },
                            script = "install -Dm755 build/cast-pgo-workload-fixture \"${CAST_INSTALL_ROOT}${CAST_BINDIR}/cast-pgo-workload-fixture\""
                        }
                    }
                },
                check = {
                    steps = {
                        {
                            kind = "run_built",
                            program = {
                                path = "build/cast-pgo-workload-fixture"
                            },
                            args = {
                                "--self-test"
                            }
                        }
                    }
                },
                workload = {
                    steps = {
                        {
                            kind = "run_built",
                            program = {
                                path = "build/cast-pgo-workload-fixture"
                            },
                            args = {
                                "--train",
                                "profile-guided-build-2026"
                            }
                        }
                    }
                }
            },
            supported_hooks = {
                setup = true,
                build = true,
                check = true,
                install = true,
                workload = true
            }
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Offline LLVM profile-guided optimization fixture"
            },
            description = {
                kind = "some",
                value = "A two-job custom build trained structurally before its isolated profile-use rebuild."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "exe",
                    path = "/usr/bin/cast-pgo-workload-fixture"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = false,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-pgo-workload-fixture-1.0.0.tar",
            hash = "84b8b4011b5cff63cb53cb1180cc4550d3e762233c121dfa8490d55fe4035f34",
            rename = {
                kind = "some",
                value = "cast-pgo-workload-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-pgo-workload-fixture"
            }
        }
    },
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}