-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "orbit-catalogs",
        version = "2026.07",
        release = 1,
        homepage = "https://example.invalid/orbit/translations",
        license = {
            "GPL-3.0-or-later"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "mkdir"
            },
            {
                kind = "binary",
                value = "msgfmt"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/mkdir",
                            requirement = {
                                kind = "binary",
                                value = "mkdir"
                            }
                        },
                        args = {
                            "-p",
                            "build/fr/LC_MESSAGES"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/mkdir",
                            requirement = {
                                kind = "binary",
                                value = "mkdir"
                            }
                        },
                        args = {
                            "-p",
                            "build/de/LC_MESSAGES"
                        }
                    }
                }
            },
            build = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/msgfmt",
                            requirement = {
                                kind = "binary",
                                value = "msgfmt"
                            }
                        },
                        args = {
                            "--check-format",
                            "--check-header",
                            "-o",
                            "build/fr/LC_MESSAGES/orbit.mo",
                            "po/fr.po"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/msgfmt",
                            requirement = {
                                kind = "binary",
                                value = "msgfmt"
                            }
                        },
                        args = {
                            "--check-format",
                            "--check-header",
                            "-o",
                            "build/de/LC_MESSAGES/orbit.mo",
                            "po/de.po"
                        }
                    }
                }
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/bash",
                            requirement = {
                                kind = "binary",
                                value = "bash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "install -Dm644 build/fr/LC_MESSAGES/orbit.mo \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/locale/fr/LC_MESSAGES/orbit.mo\"\ninstall -Dm644 build/de/LC_MESSAGES/orbit.mo \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/locale/de/LC_MESSAGES/orbit.mo\"\ninstall -Dm644 COPYING \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/doc/orbit-catalogs/COPYING\""
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/msgfmt",
                            requirement = {
                                kind = "binary",
                                value = "msgfmt"
                            }
                        },
                        args = {
                            "--check-format",
                            "--check-header",
                            "-o",
                            "build/check-fr.mo",
                            "po/fr.po"
                        }
                    },
                    {
                        kind = "run",
                        program = {
                            path = "/usr/bin/msgfmt",
                            requirement = {
                                kind = "binary",
                                value = "msgfmt"
                            }
                        },
                        args = {
                            "--check-format",
                            "--check-header",
                            "-o",
                            "build/check-de.mo",
                            "po/de.po"
                        }
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {},
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "French and German message catalogs for Orbit"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/locale/*/LC_MESSAGES/orbit.mo"
                }
            },
            conflicts = {}
        },
        {
            name = "docs",
            include_in_manifest = false,
            summary = {
                kind = "some",
                value = "License text for Orbit translations"
            },
            description = {
                kind = "none"
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/doc/orbit-catalogs"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://example.invalid/orbit-catalogs-2026.07.tar.xz",
            hash = "3456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef012",
            rename = {
                kind = "none"
            },
            strip_dirs = {
                kind = "none"
            },
            unpack = true,
            unpack_dir = {
                kind = "none"
            }
        }
    },
    architectures = {
        "native"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}