# SPDX-FileCopyrightText: 2023 AerynOS Developers
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate project

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          echo "/usr/lib/llvm-18/bin" >> $GITHUB_PATH
          echo "CC=/usr/lib/llvm-18/bin/clang" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Install typo checker
        run: cargo install typos-cli --locked --version '=1.43.5'

      - name: Check all workspace targets
        run: make check

      - name: Run canonical validation
        run: make test
