-- @generated by cast. DO NOT EDIT.
return {
    meta = {
        pname = "cast-font-family-fixture",
        version = "1.0.0",
        release = 1,
        homepage = "https://fixtures.invalid/cast-font-family-fixture",
        license = {
            "OFL-1.1"
        }
    },
    builder = {
        required_tools = {
            {
                kind = "binary",
                value = "dash"
            },
            {
                kind = "binary",
                value = "install"
            }
        },
        environment = {},
        phases = {
            setup = {
                steps = {}
            },
            build = {
                steps = {}
            },
            install = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/install",
                                requirement = {
                                    kind = "binary",
                                    value = "install"
                                }
                            }
                        },
                        script = "install -Dm644 fonts/CastAsterFixture-Regular.ttf \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/fonts/truetype/cast-aster-fixture/CastAsterFixture-Regular.ttf\"\ninstall -Dm644 fonts/CastAsterFixture-Bold.ttf \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/fonts/truetype/cast-aster-fixture/CastAsterFixture-Bold.ttf\"\ninstall -Dm644 OFL.txt \"${CAST_INSTALL_ROOT}${CAST_DATADIR}/licenses/cast-font-family-fixture/OFL.txt\""
                    }
                }
            },
            check = {
                steps = {
                    {
                        kind = "shell",
                        interpreter = {
                            path = "/usr/bin/dash",
                            requirement = {
                                kind = "binary",
                                value = "dash"
                            }
                        },
                        declared_programs = {
                            {
                                path = "/usr/bin/fc-scan",
                                requirement = {
                                    kind = "binary",
                                    value = "fc-scan"
                                }
                            }
                        },
                        script = "font_root=\"${CAST_INSTALL_ROOT}${CAST_DATADIR}/fonts/truetype/cast-aster-fixture\"\nregular=\"$font_root/CastAsterFixture-Regular.ttf\"\nbold=\"$font_root/CastAsterFixture-Bold.ttf\"\n[ \"$(fc-scan --format '%{family[0]}|%{style[0]}|%{fontformat}|%{fullname[0]}|%{postscriptname}\\n' \"$regular\")\" = 'Cast Aster Fixture|Regular|TrueType|Cast Aster Fixture Regular|CastAsterFixture-Regular' ]\n[ \"$(fc-scan --format '%{family[0]}|%{style[0]}|%{fontformat}|%{fullname[0]}|%{postscriptname}\\n' \"$bold\")\" = 'Cast Aster Fixture|Bold|TrueType|Cast Aster Fixture Bold|CastAsterFixture-Bold' ]\nset -- \"$font_root/\"*.ttf\n[ \"$#\" -eq 2 ]\nfor cache in \"$font_root/\"fonts.cache-* \"$font_root/fonts.dir\" \"$font_root/fonts.scale\"; do\n    [ ! -e \"$cache\" ]\ndone"
                    }
                }
            },
            workload = {
                steps = {}
            }
        },
        supported_hooks = {
            setup = true,
            build = true,
            check = true,
            install = true,
            workload = true
        }
    },
    hooks = {
        pre_setup = {},
        post_setup = {},
        pre_build = {},
        post_build = {},
        pre_check = {},
        post_check = {},
        pre_install = {},
        post_install = {},
        pre_workload = {},
        post_workload = {}
    },
    native_build_inputs = {},
    build_inputs = {},
    check_inputs = {
        {
            kind = "binary",
            value = "fc-scan"
        }
    },
    outputs = {
        {
            name = "out",
            include_in_manifest = true,
            summary = {
                kind = "some",
                value = "Deterministic install-only TrueType fixture"
            },
            description = {
                kind = "some",
                value = "A self-authored Regular and Bold font family with semantic metadata validation and no generated font cache."
            },
            provides_exclude = {},
            runtime_inputs = {},
            runtime_exclude = {},
            paths = {
                {
                    kind = "any",
                    path = "/usr/share/fonts/truetype/cast-aster-fixture"
                },
                {
                    kind = "any",
                    path = "/usr/share/licenses/cast-font-family-fixture/OFL.txt"
                }
            },
            conflicts = {}
        }
    },
    options = {
        toolchain = "llvm",
        cspgo = false,
        samplepgo = false,
        debug = true,
        strip = true,
        networking = false,
        compressman = false,
        lastrip = true
    },
    profiles = {},
    sources = {
        {
            kind = "archive",
            url = "https://fixtures.invalid/sources/cast-font-family-fixture-1.0.0.tar",
            hash = "8710f0728fbde240fd94ce8bce46c4e4d71336b8470416e8da7c0895dc2d700c",
            rename = {
                kind = "some",
                value = "cast-font-family-fixture.tar"
            },
            strip_dirs = {
                kind = "some",
                value = 1
            },
            unpack = true,
            unpack_dir = {
                kind = "some",
                value = "cast-font-family-fixture"
            }
        }
    },
    architectures = {
        "x86_64"
    },
    tuning = {},
    emul32 = false,
    mold = false,
}